apiVersion: v2
appVersion: 8.1.2
description: 'IBM DevOps Deploy is a versatile, enterprise-level continuous delivery
  solution which tackles everything from mainframe to microservices. DevOps Deploy
  is the tool for automating application deployments through multiple environments
  and is designed to facilitate continuous delivery while providing the audit trails,
  versioning, and approvals needed in production. License By installing this product
  you accept the following license terms: https://ibm.biz/devops-deploy-license.'
home: https://github.com/IBM/charts/blob/master/repo/ibm-helm/ibm-ucd-prod.md
icon: https://developer.ibm.com/urbancode/wp-content/uploads/sites/16/2017/09/ucdicon.png
keywords:
- ucd
- deploy
- amd64
- s390x
- ppc64le
- Commercial
- RHOCP
- ICPRHOCP
- IKS
- DevOps
- CI/CD
kubeVersion: '>=1.19.0-0'
maintainers:
- name: IBM
- name: IBM DevOps Deploy
name: ibm-ucd-prod
version: 8.0.18
