# Default values for ibm-ucd chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Globals for use with the DevOps Loop platform
global:
  domain: ""
  imageRegistry: "cp.icr.io/cp"
  externalImageRegistry: ""  # Airgap, location of "external" image(s) ie. MySQL
  imagePullSecrets: []
  ibmCertSecretName: ""
  rationalLicenseKeyServer: ""
  platform:
    enabled: false
    path: ""
    oidc:
      issuerPath: ""
      authorizationPath: ""
      tokenPath: ""
      userinfoPath: ""
      introspectionPath: ""
      jwksPath: ""
      logoutPath: ""

platform:
  oidc:
    clientId: ""
    clientSecret: ""

# DevOps Deploy Version
version: "8.1.2.0"

# Number of replicas/instances of the server and distributed-front-end
replicas:
  server: 1
  dfe: 0

image:
  pullPolicy: IfNotPresent
  secret: ""
  repository: ""

service:
  type: ClusterIP

database:
  type: "mysql"         # Ignored if database.createDatabase=true
  name: "deploydb"
  hostname: ""          # Ignored if database.createDatabase=true
  username: "dbuser"
  port: ""              # Ignored if database.createDatabase=true
  jdbcConnUrl: ""
  fetchDriver: true
  driverVersion: ""
  createDatabase: false  # Automatically create a MySQL database
  dbVolume:             # Only used if createDatabase is true
    storageClassName: ""
    size: "20Gi"

secureConnections:
  required: true
  tlsSecret: ""

secret:
  name: ""

license:
# Change license.accept to true to indicate you have read and agree to license agreements : https://ibm.biz/devops-deploy-license
  accept: false
  serverUrl: ""

persistence:
  enabled: true
  useDynamicProvisioning: true
  fsGroup: "1001"

extLibVolume:
  name: "ext-lib"
  existingClaimName: ""
  configMapName: ""
  storageClassName: ""
  size: ""
  accessMode: "ReadWriteOnce"

appDataVolume:
  name: "appdata"
  existingClaimName: ""
  storageClassName: ""
  size: "20Gi"
  accessMode: "ReadWriteOnce"

ingress:
  host: ""
  dfehost: ""
  wsshost: ""
  tlsSecret: ""
  path: "/"

resources:
  constraints: 
    enabled: true
  limits:
    cpu: 4000m
    memory: 8Gi
    ephemeral-storage: 2Gi
  requests:
    cpu: 200m
    memory: 600Mi
    ephemeral-storage: 500Mi

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 30
  failureThreshold: 10

livenessProbe:
  initialDelaySeconds: 179
  periodSeconds: 180
  failureThreshold: 3
