{{- include "devops-platform.checkRequiredValues" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-platform.componentFullname" (dict "componentName" "licensing" "context" .) }}
  labels:
      {{- include "devops-platform.labels" (dict "componentName" "licensing" "context" .) | nindent 6 }}
spec:
  replicas: {{ .Values.licensing.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "devops-platform.selectorLabels" (dict "componentName" "licensing" "context" .) | nindent 6 }}
  template:
    metadata:
      {{- with (mergeOverwrite (deepCopy .Values.platform.deploymentAnnotations) .Values.licensing.deploymentAnnotations) }}
      annotations:
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "devops-platform.labels" (dict "componentName" "licensing" "context" .) | nindent 8 }}
        {{- with (mergeOverwrite (deepCopy .Values.platform.podLabels) .Values.licensing.podLabels) }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "devops-platform.serviceAccountName" (dict "componentName" "licensing" "context" .) }} 
      {{- with (mergeOverwrite (deepCopy .Values.platform.podAnnotations) .Values.licensing.podAnnotations) }}
      annotations:
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
      securityContext:
        {{- with .Values.licensing.podSecurityContext | default .Values.platform.podSecurityContext }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      initContainers:
{{- $image := include "devops-platform.image" (dict "componentName" "licensing" "context" .) -}}
{{- template "devops-platform.initContainers.trust-store" (merge (dict "image" $image) . ) -}}
{{- "\n" }}{{- "containers:" | nindent 6 }}
        - name: {{ .Values.licensing.name }}
          {{- with .Values.licensing.securityContext | default .Values.platform.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "devops-platform.image" (dict "componentName" "licensing" "context" .) }}
          imagePullPolicy: {{ .Values.licensing.imagePullPolicy | default .Values.platform.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.licensing.service.port | default 8080}}
              protocol: TCP
          env:
            - name: BASE_NAME
              value: {{ .Values.global.platform.path | quote }}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.licensing.profile | default "prod" }}
            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "server": {
                    "servlet": {
                      "context-path" : "{{ .Values.licensing.ingress.path }}"
                    }
                  },
                  "spring": {
                    "security": {
                      "oauth2": {
                        "resourceserver": {
                          "jwt": {
                            "jwk-set-uri": "https://{{ .Values.global.domain }}{{ .Values.global.platform.oidc.jwksPath }}"
                          }
                        }
                      }
                    }
                  }
                }
            - name: NEXUS_LICENSING_VENDOR
              value: {{ default .Values.global.platform.brand .Values.licensing.vendor }}
            - name: NEXUS_LICENSING_LICENSE_SERVER_URL
              value: {{ ternary (.Values.global.hclLicensingURL | quote) (.Values.global.rationalLicenseKeyServer | quote) (eq .Values.global.platform.brand "HCL") }}
            {{- if .Values.global.hclLicensingID }}
            - name: NEXUS_LICENSING_LICENSE_SERVER_ID
              value: {{ .Values.global.hclLicensingID | quote }}
            {{- end }}
          {{- with .Values.licensing.livenessProbe | default .Values.platform.livenessProbe }}
          {{- if .enabled }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- with (.Values.licensing.readinessProbe) | default .Values.platform.readinessProbe }}
          {{- if .enabled }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.licensing.resources | nindent 12 }}
{{- "volumeMounts:" | nindent 10 }}
{{- template "devops-platform.volumeMounts.trust-store" $ }}

      {{- with .Values.licensing.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.licensing.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.licensing.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
{{- template "devops-platform.volumes.tmp-volume" $ }}
{{- template "devops-platform.volumes.keycloak-init-sh" $ }}
{{- template "devops-platform.volumes.trust-store" $ }}
