{{- if include "testhub.rm.enabled" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: rm
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-rm'
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: '{{ .Release.Name }}'
      app.kubernetes.io/name: rm
      app.kubernetes.io/part-of: '{{ .Chart.Name }}'
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        productID: e3e180b0faae4301b54c5c9b37319e5c
        productMetric: FLOATING_USER
        productName: IBM Rational Test Automation Server Basic
        productVersion: "11.0.5"
        cloudpakName : IBM DevOps for IBM Cloud Paks
        cloudpakId : dedb7a9445a44fb88c927c1658243cd1
        cloudpakMetric : RESOURCE_UNIT
        productCloudpakRatio : "1:1"
        productChargedContainers : All
      labels:
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/name: rm
        app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
{{- if .Values.priorityClassName }}
      priorityClassName: '{{ .Values.priorityClassName }}'
{{- end }}
      containers:
      - env:
        - name: OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: oauth-client-secret
              name: '{{ .Release.Name }}-rm'
        - name: INGRESS_DOMAIN
          value: '{{ .Values.global.domain }}'
        - name: SPRING_APPLICATION_JSON
          value: >
            {
              "server": {
                "forward-headers-strategy": "NATIVE",
                "servlet": {
                  "context-path" : "{{ .Values.ingress.path }}"
                }
              },
              "spring": {
                "datasource": {
                  "url": "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/rm",
                  "username": "rm"
                },
                "rabbitmq": {
                  "host": "{{ .Release.Name }}-rabbitmq",
                  "port": "5672",
                  "username": "user"
                },
                "security": {
                  "oauth2": {
                    "client": {
                      "registration": {
                        "internal": {
                          "authorization-grant-type": "client_credentials",
                          "client-id": "testserver-rm",
                          "client-secret": "$(OAUTH_CLIENT_SECRET)",
                          "provider": "keycloak"
                        }
                      },
                      "provider": {
                        "keycloak": {
                          "token-uri": "https://$(INGRESS_DOMAIN){{ .Values.keycloak.path }}/realms/{{ .Values.keycloak.realm }}/protocol/openid-connect/token"
                        }
                      }
                    },
                    "resourceserver": {
                      "jwt": {
                        "jwk-set-uri": "https://$(INGRESS_DOMAIN){{ .Values.keycloak.path }}/realms/{{ .Values.keycloak.realm }}/protocol/openid-connect/certs"
                      }
                    }
                  }
                }
              }
            }
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgresql-password
              name: '{{ .Release.Name }}-rm'
        - name: SPRING_PROFILES_ACTIVE
          value: prod,swagger
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              key: rabbitmq-password
              name: '{{ .Release.Name }}-rabbitmq'
{{- range $key, $value := .Values.rm.extraEnv }}
        - name: {{ $key }}
          value: {{ tpl $value $ | quote }}
{{- end }}
        image: '{{ (default (default .Values.imageRegistry .Values.global.imageRegistry) .Values.rm.registry) }}/{{ regexReplaceAll .Values.imageRepoRegex .Values.rm.image .Values.imageRepoRepl }}'
        imagePullPolicy: IfNotPresent
        startupProbe:
          failureThreshold: 20
          httpGet:
            path: '{{ .Values.ingress.path }}/management/health'
            port: http
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: '{{ .Values.ingress.path }}/management/health'
            port: http
        readinessProbe:
          httpGet:
            path: '{{ .Values.ingress.path }}/management/health'
            port: http
        name: main
        ports:
        - containerPort: 8097
          name: http
          protocol: TCP
{{- if .Values.rm.resources }}
        resources: {{- toYaml .Values.rm.resources | nindent 10 }}
{{- end }}
{{- template "testhub.container.security-context" .Values.containerSecurityContext }}
        volumeMounts:
{{- template "testhub.volumeMounts.trust-store" $ }}
{{- if include "testhub.ibmImagePullSecret" . }}
      imagePullSecrets:
      - name: '{{ include "testhub.ibmImagePullSecret" . }}'
{{- end }}
      initContainers:
{{- template "testhub.initContainers.trust-store" $ }}
      - name: keycloak
        command:
        - sh
        - -ec
        - |
          ./wait.sh $KEYCLOAK_URL/realms/$REALM_NAME/
          ./client-create.sh
        env:
{{- template "testhub.container.keycloak-init-sh-env" $ }}
        - name: CLIENT_ID
          value: testserver-rm
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: oauth-client-secret
              name: '{{ .Release.Name }}-rm'
{{- template "testhub.container.keycloak-init-sh-trailer" $ }}
{{- template "testhub.initContainers.pg-isready" (merge (dict "dbName" "rm") .) }}
{{- template "testhub.initContainers.liquibase-update" (merge (dict "svc" "rm" "dbName" "rm") .) }}
      hostIPC: false
      hostNetwork: false
      hostPID: false
{{- template "testhub.pod.security-context" $ }}
      serviceAccountName: '{{ .Release.Name }}-rm'
      volumes:
{{- template "testhub.volumes.trust-store" $ }}
{{- template "testhub.volumes.keycloak-init-sh" $ }}
{{- if eq .Values.global.cmdKubectl "oc" }}
      - name: service-ca
        configMap:
          name: {{ .Release.Name }}-service-ca
          items:
            - key: service-ca.crt
              path: ca.crt
{{- end }}
{{- end }}
