{{- if include "testhub.rm.enabled" . }}
{{- if eq .Values.global.cmdKubectl "oc" }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: stub-metrics
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-stub-metrics'
spec:
  podMetricsEndpoints:
  - interval: 30s
    port: metrics
    scheme: http
  selector:
    matchLabels:
      execution-type: execution-stubs
{{- end }}
{{- end }}
