apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: keycloak-init-sh
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-keycloak-init-sh'
data:
  admin-token.sh: |-
    {{- .Files.Get "lib/keycloak/admin-token.sh" | nindent 4 }}
  client-delete.sh: |-
    {{- .Files.Get "lib/keycloak/client-delete.sh" | nindent 4 }}
  client-id.sh: |-
    {{- .Files.Get "lib/keycloak/client-id.sh" | nindent 4 }}
  client-create.sh: |-
    {{- .Files.Get "lib/keycloak/client-create.sh" | nindent 4 }}
  realm-create.sh: |-
    {{- .Files.Get "lib/keycloak/realm-create.sh" | nindent 4 }}
  user-create.sh: |-
    {{- .Files.Get "lib/keycloak/user-create.sh" | nindent 4 }}
  user-delete.sh: |-
    {{- .Files.Get "lib/keycloak/user-delete.sh" | nindent 4 }}
  user-offline-token.sh: |-
    {{- .Files.Get "lib/keycloak/user-offline-token.sh" | nindent 4 }}
  user-token.sh: |-
    {{- .Files.Get "lib/keycloak/user-token.sh" | nindent 4 }}
  wait.sh: |-
    {{- .Files.Get "lib/keycloak/wait.sh" | nindent 4 }}
