apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: '20'
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: keycloak-init
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-keycloak-init'
spec:
  template:
    metadata:
      annotations:
        productID: e3e180b0faae4301b54c5c9b37319e5c
        productMetric: FLOATING_USER
        productName: IBM Rational Test Automation Server Basic
        productVersion: "11.0.5"
        cloudpakName : IBM DevOps for IBM Cloud Paks
        cloudpakId : dedb7a9445a44fb88c927c1658243cd1
        cloudpakMetric : RESOURCE_UNIT
        productCloudpakRatio : "1:1"
        productChargedContainers : All
      labels:
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/managed-by: '{{ .Release.Service }}'
        app.kubernetes.io/name: keycloak-init
        app.kubernetes.io/part-of: '{{ .Chart.Name }}'
        app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
        helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - name: main
{{- template "testhub.container.security-context" .Values.containerSecurityContext }}
        command:
        - bash
        - -c
        - |
          ./wait.sh $KEYCLOAK_URL/realms/master/

{{- if .Values.keycloak.migrate.enabled }}
          if ! curl -sfo /dev/null $CAFILE "$KEYCLOAK_URL/realms/$REALM_NAME/"; then
            LEGACY_REALM={{ .Values.keycloak.migrate.realm }}
            if [ "$REALM_NAME" != "$LEGACY_REALM" ] && curl -sfo /dev/null $CAFILE "$KEYCLOAK_URL/realms/$LEGACY_REALM/"; then
              . admin-token.sh
              curl -si $CAFILE -X PUT "$KEYCLOAK_URL/admin/realms/$LEGACY_REALM" \
                -H 'Content-Type: application/json' \
                -H "Authorization: Bearer $ADMIN_TOKEN" \
                -d @-<<EOF
          {"realm":"$REALM_NAME"}
          EOF
            fi
          fi
{{- end }}

          if curl -sfo /dev/null $CAFILE "$KEYCLOAK_URL/realms/$REALM_NAME/"; then
            . admin-token.sh

            curl -i $CAFILE -X PUT "$KEYCLOAK_URL/admin/realms/$REALM_NAME" \
                  -H 'Content-Type: application/json' \
                  -H "Authorization: Bearer $ADMIN_TOKEN" \
                  -d @-<<EOF
            {"loginTheme":"$REALM_THEME",
            "accountTheme":"$REALM_THEME"}
            EOF

            client_id="$(CLIENT_ID=realm-management ADMIN_TOKEN=$ADMIN_TOKEN ./client-id.sh)"

            _get_id () {
              curl -si $CAFILE "$KEYCLOAK_URL/admin/realms/$REALM_NAME/$1" \
                -H 'Accept: application/json' \
                -H "Authorization: Bearer $ADMIN_TOKEN" |
              sed -r -n 's/.*"id":"([^"]*)".*/\1/p'
            }

            role_admin_id=$(_get_id clients/$client_id/roles/realm-admin)
            role_default_id=$(_get_id roles?search=default-roles-$REALM_NAME)

            curl -si $CAFILE -X DELETE "$KEYCLOAK_URL/admin/realms/$REALM_NAME/roles-by-id/$role_default_id/composites" \
              -H 'Content-Type: application/json' \
              -H "Authorization: Bearer $ADMIN_TOKEN" \
              -d @-<<EOF
          [{"id":"$role_admin_id"}]
          EOF

            exit 0
          fi

          ./realm-create.sh
        env:
        - name: SIGNUP
          value: '{{ ternary "true" "false" .Values.signup }}'
        - name: REALM_THEME
          value: test
{{- template "testhub.container.keycloak-init-sh-env" $ }}
{{- template "testhub.container.keycloak-init-sh-trailer" $ }}
{{- if include "testhub.ibmImagePullSecret" . }}
      imagePullSecrets:
      - name: '{{ include "testhub.ibmImagePullSecret" . }}'
{{- end }}
      restartPolicy: Never
      hostIPC: false
      hostNetwork: false
      hostPID: false
{{- template "testhub.pod.security-context" $ }}
      serviceAccountName: '{{ print .Release.Name "-ssocloak" | trunc 20 | trimSuffix "-" }}'
      volumes:
      - name: ingress
        secret:
          optional: {{ ternary "false" "true" .Values.ingress.cert.selfSigned }}
          secretName: '{{ ternary .Values.global.ibmCertSecretName "none" .Values.ingress.cert.selfSigned }}'
{{- template "testhub.volumes.keycloak-init-sh" $ }}
