apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-keycloak'
type: Opaque
data:
{{- if .Values.keycloak.existingPassword }}
  password: {{ .Values.keycloak.existingPassword | b64enc | quote }}
{{- else }}
  password: {{ print (default .Release.Name (default .Values.global.passwordSeed .Values.passwordSeed)) "keycloak-admin-password" | sha256sum | b64enc | quote }}
{{- end }}
{{- if .Values.keycloak.existingPostgresqlPassword }}
  postgresql-password: {{ .Values.keycloak.existingPostgresqlPassword | b64enc | quote }}
{{- else }}
  postgresql-password: {{ print (default .Release.Name (default .Values.global.passwordSeed .Values.passwordSeed)) "keycloak-postgresql" | sha256sum | b64enc | quote }}
{{- end }}
