preflight:
  validateHostPattern: true
global:
  cmdKubectl: kubectl
  rationalLicenseKeyServer: ''
  domain: ''
  ibmCertSecretName: ingress
  ibmImagePullSecret: ''
  ibmImagePullUsername: cp
  ibmImagePullPassword: ''
  ibmImagePullEmail: 'not-required@test'
  persistence:
    rwxAccessMode: 'ReadWriteMany'
    rwxStorageClass: ''
  platform:
    enabled: false
    oidc:
      logoutPath: '{{ .Values.keycloak.path }}/realms/{{ .Values.keycloak.realm }}/protocol/openid-connect/logout'
    path: /devops-platform
    links:
      embed: '{{ .Values.global.platform.path }}/embed?path='
# Change license to true to indicate you have read and agree to license agreements : http://ibm.biz/rtas-license
license: false
rationalLicenseKeyServer: ''
ingress:
  path: '/test'
  type: mapping
  cert:
    create: true
    selfSigned: false
  host:
    enabled: true
imageRepoRegex: ':[^/]+@'
imageRepoRepl: '@'
imageRegistry: cp.icr.io/cp
userCertsSecretName: usercerts
networkPolicy:
  enabled: false
  egress:
    enabled: false
    cidrs:
      # private addresses
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
      # SOME of github.com IPs can be found using: (with some codeload.github.com IPs missed 2022/03/10)
      #   curl https://api.github.com/meta 2>/dev/null | jq -r .web[] | grep -v : | sort -g | sed 's/^/    - /'
  ingress:
    enabled: true
    podLabel: ''
    podValue: ''

priorityClassName: ''
#priorityClassValue: 1000

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  fsGroup: 1001
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext:
  capabilities:
    drop:
      - ALL
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
clusterDomain: cluster.local
script:
  image: ibm-devops-test-runtime:d4641f1d81@sha256:7bc1428b2405b7e22541671f2c13e3ac88a8d405a015ddf088564ab06f1bf446
  chrome:
    image: ibm-devops-test-runtime-chrome:d4641f1d81@sha256:58806ec446a107ed9ac0f472bf37eae19307b733e3c3f8b27a5b7d68a415d2e4
  edge:
    image: ibm-devops-test-runtime-edge:d4641f1d81@sha256:657f611fabc5b1841a5047798ad83071d4e274c42ad69aeb1ec70a578fe01c2a
scriptInstall:
  image: ibm-devops-testhub-runtime-install:d4641f1d81@sha256:e5369e3bcb8c015617755783b4786cf4f359a1269017fe489f28df0bbf01c781
  resources:
    limits:
      memory: 262Mi
      ephemeral-storage: 160Mi
    requests:
      cpu: 25m
      memory: 262Mi
      ephemeral-storage: 160Mi
extensions:
  api:
    image: ibm-devops-test-virtualization:d4641f1d81@sha256:e3ddf426ffe40f1fc62618d28df1f2a6c47a5cb8e3dfcdbce638aeb7eb4bbb0e
  azure:
    enabled: true
  codesweep:
    enabled: true
    image: ibm-devops-test-codesweep:d4641f1d81@sha256:6bcddfcf9156c16ff4a9e25c4c39c7a616f90610aec4c24675b8b75e5d2dcf54
  plan:
    enabled: true
  etm:
    enabled: true
  jira:
    enabled: true
  ai:
    enabled: true
  jmeter:
    enabled: true
    image: ibm-devops-test-jmeter:d4641f1d81@sha256:27f6d50f8a0e351621abd47870d8f9d77a7b51068e479226c622bc8ea633f9b9
  junit:
    enabled: true
    image: ibm-devops-test-junit:d4641f1d81@sha256:74b4270102bc6c182097afe5e039fdf37ade11e46aa8a83d75d59e3df43dbcb5
  postman:
    enabled: true
    image: ibm-devops-test-postman:d4641f1d81@sha256:191245446f98f86631cb95c012a83f7c7265bf137f708b91e5b06576663989cb
  script:
    enabled: true
  workbench:
    image: ibm-devops-test-workbench:d4641f1d81@sha256:e01103aeb44f1c8639154c5122198fd373b2f46894db4fb42b83fea3805a400f
  existingPostgresqlPassword: ''
  image: ibm-devops-testhub-extensions:d4641f1d81@sha256:5024dbebf596fb606e7d8eaf787199c5eda0d29aaf994b1a80f94695f6af81f1
  resources:
    limits:
      memory: 515Mi
      ephemeral-storage: 512Mi
    requests:
      cpu: 25m
      memory: 285Mi
      ephemeral-storage: 1Mi
cdis:
  enabled: true
  image: ibm-devops-testhub-cdis:d4641f1d81@sha256:865a008c21de38622d313fecddbaa5fa92166b8521e4eb2a23eebc9af8a0fb6a
  resources:
    limits:
      memory: 2708Mi
    requests:
      cpu: 25m
      memory: 1491Mi
datasets:
  existingPostgresqlPassword: ''
  image: ibm-devops-testhub-datasets:d4641f1d81@sha256:fa8e052b114e7bf6d0d7f8f8a9f8d4f860d12b11e88fa3a75924a9843ea734f3
  extraEnv: {}
  resources:
    limits:
      memory: 692Mi
      ephemeral-storage: 512Mi
    requests:
      cpu: 25m
      memory: 440Mi
      ephemeral-storage: 1Mi
execution:
  enginePullPolicy: IfNotPresent
  existingPostgresqlPassword: ''
  image: ibm-devops-testhub-execution:d4641f1d81@sha256:00e8b33d397afc27f4690c814924a2a240a2b8d0c4407071bfb990d8c65d4a0e
  ingress:
    hostPattern: ''
  nodePorts:
    enabled: true
  priorityClassName: ''
  #priorityClassValue: -1000
  nodeSelector: {}
  template:
    fetch:
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 50m
          memory: 128Mi
    resources:
      limits:
        memory: 3242Mi
        ephemeral-storage: 3Gi
      requests:
        cpu: 50m
        memory: 777Mi
        ephemeral-storage: 1Gi
  toleration: {}
  extraEnv: {}
  resources:
    limits:
      memory: 1511Mi
      ephemeral-storage: 1Gi
    requests:
      cpu: 25m
      memory: 366Mi
      ephemeral-storage: 5Mi
frontend:
  image: ibm-devops-testhub-frontend:d4641f1d81@sha256:b7638d658058e277f25c2cb18add50f7c849a589a68a2db83a75763bfb003c88
  headers:
    #X-Foo: '${INGRESS_DOMAIN}'
    Content-Security-Policy: frame-ancestors 'self'
    X-Frame-Options: SAMEORIGIN
  resources:
    limits:
      memory: 318Mi
      ephemeral-storage: 2000Mi
    requests:
      cpu: 25m
      memory: 64Mi
      ephemeral-storage: 2000Mi
core:
  existingOauthClientSecret: ''
  existingPostgresqlPassword: ''
  existingSecretsStorageKey: ''
  image: ibm-devops-testhub-core:d4641f1d81@sha256:6c7850d5c4943e0fc5e9c4ee20e3e59a0d1bb0fae7f9736826ee8c17f191676e
  replicaCount: 1
  extraEnv: {}
  resources:
    limits:
      memory: 600Mi
      ephemeral-storage: 512Mi
    requests:
      cpu: 49m
      memory: 367Mi
      ephemeral-storage: 32Mi
router:
  existingAddOnRegistrationSecret: ''
  image: ibm-devops-testhub-router:d4641f1d81@sha256:88a0260448bb2bb1973f66a9d672ad7b1a456316e18dd38cecb6fd28948fd438
  contentSecurityPolicyExternalList: ''
  extraEnv: {}
  resources:
    limits:
      memory: 482Mi
      ephemeral-storage: 512Mi
    requests:
      cpu: 25m
      memory: 366Mi
      ephemeral-storage: 32Mi
  rateLimit:
    #    entries:
    # # Example 1
    #      - paths: /rest/asserts/**
    #        rates: # 1/sec
    #          - limit: 1
    #            durationInSeconds: 1
    # # Example 2
    #      - paths: /rest/example/*/test/**
    #        rates: # 10/min and no more that 1/sec
    #          - limit: 10
    #            durationInSeconds: 60
    #          - limit: 1
    #            durationInSeconds: 1
    # # Example 3
    #      - paths: /rest/results/**
    #        rates: # 100/min burst refilling allowance at 25/min
    #          - limit: 100
    #            durationInSeconds: 60
    #            refill: 25
    # # Example 4
    # # paths share their rate allowance
    #      - paths: /example1/**, /example2/**
    #        rates: # 1/sec
    #          - limit: 1
    #            durationInSeconds: 1
    # # Example 5
    # # paths without rates defined share the defaultRates allowance
    #      - paths: /example3/**
    # # default rates only applies to entries without rates
    defaultRates: # 100/sec
      - limit: 100
        durationInSeconds: 1
init:
  image: ibm-devops-test-jdk17:d4641f1d81@sha256:de8e26ce5f76c8584e420bd60aa72e651e9c520275e480261e143666bfaf5529
  liquibase:
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 150m
        memory: 400Mi
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi
keycloak:
  image: ibm-devops-test-keycloak:d4641f1d81@sha256:87d19c3f4d8d08152b7a5cc0dd93e641e9351a77d57606639381f60e6deaa3f7
  existingPassword: ''
  existingPostgresqlPassword: ''
  job:
    resources:
      limits:
        memory: 64Mi
        ephemeral-storage: 4Mi
      requests:
        cpu: 50m
        memory: 64Mi
        ephemeral-storage: 4Mi
  truststoreFileHostnameVerificationPolicy: DEFAULT
  path: /auth # buildtime constant
  proxyHeaders: xforwarded
  migrate:
    enabled: true
    realm: testserver
  username: keycloak
  realm: platform
  resources:
    limits:
      memory: 984Mi
      ephemeral-storage: 512Mi
    requests:
      cpu: 25m
      memory: 725Mi
      ephemeral-storage: 8Mi
postgresql:
  existingPassword: ''
  image: ibm-devops-test-postgresql:d4641f1d81@sha256:293f8b61d65e185fc042dca899305eced3cce1fedf11baa65ba1fac40d9c145a
  migrate:
    enabled: false
    image: ibm-devops-test-postgresql-migrate:d4641f1d81@sha256:d42ebc79a465f5a73759471a6fb6fff288ea0d22d59507ac59c1446deff6406e
  dbs:
    datasets:
      connections: 11
    execution:
      connections: 11
    extensions:
      connections: 5
    gateway:
      secret: '{{ .Release.Name }}-core'
      connections: 11
    keycloak:
      connections: 21
    results:
      connections: 21
    rm:
      connections: 11
    testassets:
      secret: '{{ .Release.Name }}-tam'
      connections: 51
    testlog:
      owner: results
      extensions:
        - hstore
        - ltree
        - lo
    analytics:
      state: absent
    upload:
      state: absent
  job:
    resources:
      limits:
        memory: 64Mi
        ephemeral-storage: 1Mi
      requests:
        cpu: 50m
        memory: 64Mi
        ephemeral-storage: 1Mi
  resources:
    limits:
      memory: 9011Mi
      ephemeral-storage: 50Mi
    requests:
      cpu: 163m
      memory: 2923Mi
      ephemeral-storage: 50Mi
rabbitmq:
  existingPassword: ''
  existingCookie: ''
  image: ibm-devops-test-rabbitmq:d4641f1d81@sha256:d6822620796f8d9fdd2b5416b06e4aa880728ff57d184fb1b44c499d854b3ebf
  resources:
    limits:
      memory: 600Mi
      ephemeral-storage: 100Mi
    requests:
      cpu: 247m
      memory: 158Mi
      ephemeral-storage: 100Mi
results:
  previewEnabled: false
  jaegerAgent: ''
  jaegerDashboard: ''
  existingPostgresqlPassword: ''
  image: ibm-devops-testhub-results:d4641f1d81@sha256:76e8261b42f928a7769d9de78bc387961106f02ecfbc07de7832090c669eefdc
  extraEnv: {}
  resources:
    limits:
      memory: 886Mi
      ephemeral-storage: 512Mi
    requests:
      cpu: 25m
      memory: 459Mi
      ephemeral-storage: 1Mi
rm:
  enabled: true
  existingPostgresqlPassword: ''
  image: ibm-devops-testhub-rm:d4641f1d81@sha256:9614413bf971ebce03edf1f1040dda8ccf74945dceddd0f573361a0dbfce6865
  extraEnv: {}
  resources:
    limits:
      memory: 541Mi
      ephemeral-storage: 512Mi
    requests:
      cpu: 25m
      memory: 282Mi
      ephemeral-storage: 1Mi
signup: false
tam:
  existingPostgresqlPassword: ''
  image: ibm-devops-testhub-tam:d4641f1d81@sha256:a515e4f8b2fff18bec6c6c95913f992c7887b4159cf9267528e411174a3fca80
  extraEnv: {}
  resources:
    limits:
      memory: 4968Mi
      ephemeral-storage: 512Mi
    requests:
      cpu: 49m
      memory: 1447Mi
      ephemeral-storage: 32Mi
tests:
  pull:
    api: false
  main:
    command: run --tls-ca-path=tmp --verbose all.dts.yaml
    extraEnv:
      ENV_REPO_COMMIT: 789c61e
      ENV_DELETE_PROJECT: 'true'
    resources:
      limits:
        memory: 510Mi
        ephemeral-storage: 32Mi
      requests:
        cpu: 500m
        memory: 362Mi
        ephemeral-storage: 32Mi
userlibs:
  resources:
    limits:
      memory: 64Mi
      ephemeral-storage: 64Mi
    requests:
      cpu: 25m
      memory: 64Mi
      ephemeral-storage: 1Mi
