global:
  cmdKubectl: oc
ingress:
  type: route

networkPolicy:
  enabled: true
  ingress:
    namespaceLabel: network.openshift.io/policy-group
    namespaceValue: ingress

securityContext:
  fsGroup: 'null'
  runAsUser: 'null'

execution:
  ingress:
    hostPattern: '{{ regexReplaceAll "^([^.]*)" .Values.global.domain "$1-*" }}'
