ingress:
  cert:
    selfSigned: true

networkPolicy:
  enabled: true
  ingress:
    namespaceLabel: kubernetes.io/metadata.name
    namespaceValue: emissary

execution:
  ingress:
    hostPattern: 'in-*.{{ .Values.global.domain }}'
