# Default values for ibm-devops-code-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  imagePullSecrets: []
  persistence:
    rwoStorageClass: ""
    rwxStorageClass: ""
  imageRegistry: ""  
  domain: ""
  platform:
    path: ""
    oidc:
      issuerPath: ""
      clientId: ""

clientimage:
  imageName: ibm-devops-automation-code-client
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.2"
  replicaCount: 1
  platformIssuerPath: http://localhost:8080/auth/realms/Code-Realtime # Get the actual value from platform helm chart
  platformFqdm: http://devops-code.com # Get the actual value from platform helm chart
  clientId: React-codert-auth # Get the actual value from platform helm chart

containermgrimage:
  imageName: ibm-devops-automation-code-container-mgr
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.2"
  replicaCount: 1

clientservice:
  type: ClusterIP
  port: 5000
  host: devops-code.com
  
containermgrservice:
  type: ClusterIP
  port: 3005

service:
  port: 5000  

platform:
    oidc:
      clientId: ""
      logoutPath: /logout

ingress:
    path: /  