apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ibm-devops-pipelinerun
  namespace: default
spec:
  pipelineRef:
    name: ibm-devops-pipeline
  taskRunTemplate:
    podTemplate:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
