apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: tam
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-tam'
type: Opaque
data:
{{- if include "testhub.tam.enabled" . }}
{{- if .Values.tam.existingOauthClientSecret }}
  oauth-client-secret: {{ .Values.tam.existingOauthClientSecret | b64enc | quote }}
{{- else }}
  oauth-client-secret: {{ print (default .Release.Name (default .Values.global.passwordSeed .Values.passwordSeed)) "tam-oauth-client-secret" | sha256sum | b64enc | quote }}
{{- end }}
{{- end }}
{{- if .Values.tam.existingPostgresqlPassword }}
  postgresql-password: {{ .Values.tam.existingPostgresqlPassword | b64enc | quote }}
{{- else }}
  postgresql-password: {{ print (default .Release.Name (default .Values.global.passwordSeed .Values.passwordSeed)) "tam-postgresql" | sha256sum | b64enc | quote }}
{{- end }}
