{{- if include "testhub.tam.enabled" . }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: tam
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-tam'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: '{{ .Release.Name }}'
      app.kubernetes.io/name: tam
      app.kubernetes.io/part-of: '{{ .Chart.Name }}'
  serviceName: tam
  template:
    metadata:
      annotations:
        productID: e3e180b0faae4301b54c5c9b37319e5c
        productMetric: FLOATING_USER
        productName: IBM Rational Test Automation Server Basic
        productVersion: "11.0.5"
        cloudpakName : IBM DevOps for IBM Cloud Paks
        cloudpakId : dedb7a9445a44fb88c927c1658243cd1
        cloudpakMetric : RESOURCE_UNIT
        productCloudpakRatio : "1:1"
        productChargedContainers : All
      labels:
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/name: tam
        app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
{{- if .Values.priorityClassName }}
      priorityClassName: '{{ .Values.priorityClassName }}'
{{- end }}
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
        - name: OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: oauth-client-secret
              name: '{{ .Release.Name }}-tam'
        - name: INGRESS_DOMAIN
          value: '{{ .Values.global.domain }}'
        - name: SPRING_APPLICATION_JSON
          value: >
            {
              "server": {
                "forward-headers-strategy": "NATIVE",
                "servlet": {
                  "context-path" : "{{ .Values.ingress.path }}"
                }
              },
              "spring": {
                "datasource": {
                  "url": "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/testassets",
                  "username": "testassets"
                },
                "rabbitmq": {
                  "host": "{{ .Release.Name }}-rabbitmq",
                  "port": "5672",
                  "username": "user"
                },
                "security": {
                  "oauth2": {
                    "resourceserver": {
                      "jwt": {
                        "jwk-set-uri": "https://$(INGRESS_DOMAIN){{ .Values.keycloak.path }}/realms/{{ .Values.keycloak.realm }}/protocol/openid-connect/certs"
                      }
                    },
                    "client": {
                      "registration": {
                        "internal": {
                          "authorization-grant-type": "client_credentials",
                          "client-id": "testserver-tam",
                          "client-secret": "$(OAUTH_CLIENT_SECRET)",
                          "provider": "keycloak"
                        }
                      },
                      "provider": {
                        "keycloak": {
                          "token-uri": "https://$(INGRESS_DOMAIN){{ .Values.keycloak.path }}/realms/{{ .Values.keycloak.realm }}/protocol/openid-connect/token"
                        }
                      }
                    }
                  }
                }
              }
            }
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgresql-password
              name: '{{ .Release.Name }}-tam'
        - name: SPRING_PROFILES_ACTIVE
          value: prod,swagger
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              key: rabbitmq-password
              name: '{{ .Release.Name }}-rabbitmq'
        - name: XDG_CONFIG_HOME
          value: '/app/target/content/'
{{- range $key, $value := .Values.tam.extraEnv }}
        - name: {{ $key }}
          value: {{ tpl $value $ | quote }}
{{- end }}
        image: '{{ (default (default .Values.imageRegistry .Values.global.imageRegistry) .Values.tam.registry) }}/{{ regexReplaceAll .Values.imageRepoRegex .Values.tam.image .Values.imageRepoRepl }}'
        imagePullPolicy: IfNotPresent
        startupProbe:
          failureThreshold: 20
          httpGet:
            path: '{{ .Values.ingress.path }}/management/health'
            port: http
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: '{{ .Values.ingress.path }}/management/health'
            port: http
        readinessProbe:
          httpGet:
            path: '{{ .Values.ingress.path }}/management/health'
            port: http
        name: main
        ports:
        - containerPort: 8900
          name: http
          protocol: TCP
{{- if .Values.tam.resources }}
        resources: {{- toYaml .Values.tam.resources | nindent 10 }}
{{- end }}
{{- template "testhub.container.security-context" .Values.containerSecurityContext }}
        volumeMounts:
{{- template "testhub.volumeMounts.trust-store" $ }}
        - mountPath: /app/target
          name: data
        - mountPath: /extlibs/TAM
          name: extlibs
          subPath: tam-ext
        - mountPath: /tmp
          name: tmp
{{- if (or (or (or (or (or .Values.extensions.jmeter.enabled) .Values.extensions.postman.enabled) .Values.extensions.junit.enabled) .Values.extensions.codesweep.enabled) .Values.extensions.script.enabled) }}
        - mountPath: /internal-ext
          name: internal-ext
{{- end }}
{{- if include "testhub.ibmImagePullSecret" . }}
      imagePullSecrets:
      - name: '{{ include "testhub.ibmImagePullSecret" . }}'
{{- end }}
      initContainers:
{{- template "testhub.initContainers.trust-store" $ }}
      - name: keycloak
        command:
        - sh
        - -ec
        - |
          ./wait.sh $KEYCLOAK_URL/realms/$REALM_NAME/
          ./client-create.sh
        env:
{{- template "testhub.container.keycloak-init-sh-env" $ }}
        - name: CLIENT_ID
          value: testserver-tam
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: oauth-client-secret
              name: '{{ .Release.Name }}-tam'
{{- template "testhub.container.keycloak-init-sh-trailer" $ }}
{{- template "testhub.initContainers.pg-isready" (merge (dict "dbName" "testassets" "secret" (printf "%s-tam" .Release.Name)) .) }}
{{- template "testhub.initContainers.liquibase-update" (merge (dict "svc" "tam" "dbName" "testassets") .) }}
{{- if .Values.extensions.jmeter.enabled }}
{{- template "testhub.initContainers.add-plugin" (merge (dict "plugin" "jmeter" "host" "tam" "pluginImage" "extensions") .) }}
{{- end }}
{{- if .Values.extensions.postman.enabled }}
{{- template "testhub.initContainers.add-plugin" (merge (dict "plugin" "postman" "host" "tam" "pluginImage" "extensions") .) }}
{{- end }}
{{- if .Values.extensions.junit.enabled }}
{{- template "testhub.initContainers.add-plugin" (merge (dict "plugin" "junit" "host" "tam" "pluginImage" "extensions") .) }}
{{- end }}
{{- if .Values.extensions.codesweep.enabled }}
{{- template "testhub.initContainers.add-plugin" (merge (dict "plugin" "codesweep" "host" "tam" "pluginImage" "extensions") .) }}
{{- end }}
{{- if .Values.extensions.script.enabled }}
{{- template "testhub.initContainers.add-plugin" (merge (dict "plugin" "script" "host" "tam" "pluginImage" "extensions") .) }}
{{- end }}
      - command:
        - java
        - '-jar'
        - /app/app.jar
        args:
        - post-migration
        env:
        - name: URL
          value: "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/testassets"
        - name: JAVA_OPTS
          value: -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
        - name: OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: oauth-client-secret
              name: '{{ .Release.Name }}-tam'
        - name: INGRESS_DOMAIN
          value: '{{ .Values.global.domain }}'
        - name: SPRING_APPLICATION_JSON
          value: >
            {
              "server": {
                "forward-headers-strategy": "NATIVE",
                "servlet": {
                  "context-path" : "{{ .Values.ingress.path }}"
                }
              },
              "spring": {
                "datasource": {
                  "url": "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/testassets",
                  "username": "testassets"
                },
                "rabbitmq": {
                  "host": "{{ .Release.Name }}-rabbitmq",
                  "port": "5672",
                  "username": "user"
                },
                "security": {
                  "oauth2": {
                    "resourceserver": {
                      "jwt": {
                        "jwk-set-uri": "https://$(INGRESS_DOMAIN){{ .Values.keycloak.path }}/realms/{{ .Values.keycloak.realm }}/protocol/openid-connect/certs"
                      }
                    },
                    "client": {
                      "registration": {
                        "internal": {
                          "authorization-grant-type": "client_credentials",
                          "client-id": "testserver-tam",
                          "client-secret": "$(OAUTH_CLIENT_SECRET)",
                          "provider": "keycloak"
                        }
                      },
                      "provider": {
                        "keycloak": {
                          "token-uri": "https://$(INGRESS_DOMAIN){{ .Values.keycloak.path }}/realms/{{ .Values.keycloak.realm }}/protocol/openid-connect/token"
                        }
                      }
                    }
                  }
                }
              }
            }
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgresql-password
              name: '{{ .Release.Name }}-tam'
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              key: rabbitmq-password
              name: '{{ .Release.Name }}-rabbitmq'
        - name: XDG_CONFIG_HOME
          value: '/app/target/content/'
{{- range $key, $value := .Values.tam.extraEnv }}
        - name: {{ $key }}
          value: {{ tpl $value $ | quote }}
{{- end }}
        image: '{{ (default (default .Values.imageRegistry .Values.global.imageRegistry) .Values.tam.registry) }}/{{ regexReplaceAll .Values.imageRepoRegex .Values.tam.image .Values.imageRepoRepl }}'
        imagePullPolicy: IfNotPresent
        name: post-migration
{{- if .Values.tam.resources }}
        resources: {{- toYaml .Values.tam.resources | nindent 10 }}
{{- end }}
{{- template "testhub.container.security-context" .Values.containerSecurityContext }}
        volumeMounts:
{{- template "testhub.volumeMounts.trust-store" $ }}
        - mountPath: /tmp
          name: tmp
        - mountPath: /app/target
          name: data
        - mountPath: /extlibs/TAM
          name: extlibs
          subPath: tam-ext
{{- if (or (or (or (or (or .Values.extensions.jmeter.enabled) .Values.extensions.postman.enabled) .Values.extensions.junit.enabled) .Values.extensions.codesweep.enabled) .Values.extensions.script.enabled) }}
        - mountPath: /internal-ext
          name: internal-ext
{{- end }}
      hostIPC: false
      hostNetwork: false
      hostPID: false
{{- template "testhub.pod.security-context" $ }}
      serviceAccountName: '{{ .Release.Name }}-tam'
      volumes:
{{- template "testhub.volumes.trust-store" $ }}
{{- template "testhub.volumes.keycloak-init-sh" $ }}
      - name: extlibs
        persistentVolumeClaim:
          claimName: data-{{ .Release.Name }}-userlibs-0
{{- if (or (or (or (or (or .Values.extensions.jmeter.enabled) .Values.extensions.postman.enabled) .Values.extensions.junit.enabled) .Values.extensions.codesweep.enabled) .Values.extensions.script.enabled) }}
      - emptyDir: {}
        name: internal-ext
{{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
{{- if .Values.global.persistence.rwoStorageClass }}
      storageClassName: '{{ .Values.global.persistence.rwoStorageClass }}'
{{- end }}
      resources: #storage
        requests:
          storage: 32Gi
{{- end }}
