charts:
  - archive: 'file:velocity-se-ibm-5.1.6-helm.tgz'
    repository-keys:
      - image.repository
images:
  - image: 'ibm-ucv-application-api:5.1.6.6'
    references:
      - repository: 'ibm-ucv-application-api:5.1.6.6'
        pull-repository: 'cp.icr.io/cp/ibm-ucv-application-api:5.1.6.6'
        platform:
          os: linux
          architecture: amd64
        pull-authorization:
          username:
            env: ENTITLEMENT_REGISTRY_USER
          password:
            env: ENTITLEMENT_REGISTRY_PASSWORD
  - image: 'ibm-ucv-continuous-release-consumer:5.1.6.6'
    references:
      - repository: 'ibm-ucv-continuous-release-consumer:5.1.6.6'
        pull-repository: 'cp.icr.io/cp/ibm-ucv-continuous-release-consumer:5.1.6.6'
        platform:
          os: linux
          architecture: amd64
        pull-authorization:
          username:
            env: ENTITLEMENT_REGISTRY_USER
          password:
            env: ENTITLEMENT_REGISTRY_PASSWORD
  - image: 'ibm-ucv-continuous-release-poller:5.1.6.6'
    references:
      - repository: 'ibm-ucv-continuous-release-poller:5.1.6.6'
        pull-repository: 'cp.icr.io/cp/ibm-ucv-continuous-release-poller:5.1.6.6'
        platform:
          os: linux
          architecture: amd64
        pull-authorization:
          username:
            env: ENTITLEMENT_REGISTRY_USER
          password:
            env: ENTITLEMENT_REGISTRY_PASSWORD
  - image: 'ibm-ucv-continuous-release-ui:5.1.6.6'
    references:
      - repository: 'ibm-ucv-continuous-release-ui:5.1.6.6'
        pull-repository: 'cp.icr.io/cp/ibm-ucv-continuous-release-ui:5.1.6.6'
        platform:
          os: linux
          architecture: amd64
        pull-authorization:
          username:
            env: ENTITLEMENT_REGISTRY_USER
          password:
            env: ENTITLEMENT_REGISTRY_PASSWORD
  - image: 'ibm-ucv-multi-app-pipeline-api:5.1.6.6'
    references:
      - repository: 'ibm-ucv-multi-app-pipeline-api:5.1.6.6'
        pull-repository: 'cp.icr.io/cp/ibm-ucv-multi-app-pipeline-api:5.1.6.6'
        platform:
          os: linux
          architecture: amd64
        pull-authorization:
          username:
            env: ENTITLEMENT_REGISTRY_USER
          password:
            env: ENTITLEMENT_REGISTRY_PASSWORD
  - image: 'ibm-ucv-rcl-client:1.4.0.46'
    references:
      - repository: 'ibm-ucv-rcl-client:1.4.0.46'
        pull-repository: 'cp.icr.io/cp/ibm-ucv-rcl-client:1.4.0.46'
        platform:
          os: linux
          architecture: amd64
        pull-authorization:
          username:
            env: ENTITLEMENT_REGISTRY_USER
          password:
            env: ENTITLEMENT_REGISTRY_PASSWORD
  - image: 'ibm-ucv-release-events-api:5.1.6.6'
    references:
      - repository: 'ibm-ucv-release-events-api:5.1.6.6'
        pull-repository: 'cp.icr.io/cp/ibm-ucv-release-events-api:5.1.6.6'
        platform:
          os: linux
          architecture: amd64
        pull-authorization:
          username:
            env: ENTITLEMENT_REGISTRY_USER
          password:
            env: ENTITLEMENT_REGISTRY_PASSWORD
  - image: 'ibm-ucv-release-events-ui:5.1.6.6'
    references:
      - repository: 'ibm-ucv-release-events-ui:5.1.6.6'
        pull-repository: 'cp.icr.io/cp/ibm-ucv-release-events-ui:5.1.6.6'
        platform:
          os: linux
          architecture: amd64
        pull-authorization:
          username:
            env: ENTITLEMENT_REGISTRY_USER
          password:
            env: ENTITLEMENT_REGISTRY_PASSWORD
  - image: 'ibm-ucv-reporting-consumer:5.1.6.6'
    references:
      - repository: 'ibm-ucv-reporting-consumer:5.1.6.6'
        pull-repository: 'cp.icr.io/cp/ibm-ucv-reporting-consumer:5.1.6.6'
        platform:
          os: linux
          architecture: amd64
        pull-authorization:
          username:
            env: ENTITLEMENT_REGISTRY_USER
          password:
            env: ENTITLEMENT_REGISTRY_PASSWORD
  - image: 'ibm-ucv-security-api:5.1.6.6'
    references:
      - repository: 'ibm-ucv-security-api:5.1.6.6'
        pull-repository: 'cp.icr.io/cp/ibm-ucv-security-api:5.1.6.6'
        platform:
          os: linux
          architecture: amd64
        pull-authorization:
          username:
            env: ENTITLEMENT_REGISTRY_USER
          password:
            env: ENTITLEMENT_REGISTRY_PASSWORD
  - image: 'rabbitmq:3.13.4'
    references:
      - repository: 'rabbitmq:3.13.4'
        pull-repository: 'bitnami/rabbitmq:3.13.4'
        platform:
          os: linux
          architecture: amd64
  - image: 'nginx:1.27.1'
    references:
      - repository: 'nginx:1.27.1'
        pull-repository: 'bitnami/nginx:1.27.1'
        platform:
          os: linux
          architecture: amd64
  - image: 'opencontent-common-utils:1.1.2'
    references:
      - repository: 'opencontent-common-utils:1.1.2'
        pull-repository: 'ibmcom/opencontent-common-utils:1.1.2'
        platform:
          os: linux
          architecture: amd64
  - image: 'alpine:3'
    references:
      - repository: 'alpine:3'
        pull-repository: 'alpine:3'
        platform:
          os: linux
          architecture: amd64
  - image: 'ibm-ucv-generator-rabbitmq:5.0.0.3'
    references:
      - repository: 'ibm-ucv-generator-rabbitmq:<rabbit_gen_version>'
        pull-repository: 'cp.icr.io/cp/ibm-ucv-generator-rabbitmq:<rabbit_gen_version>'
        platform:
          os: linux
          architecture: amd64
        pull-authorization:
          username:
            env: ENTITLEMENT_REGISTRY_USER
          password:
            env: ENTITLEMENT_REGISTRY_PASSWORD
