apiVersion: v2
appVersion: 7.1.0
description: IBM UrbanCode Build is a distributed, multi-platform, enterprise-scale
  build management tool. IBM UrbanCode Build uses a template-driven system to configure
  and run builds. Projects are created from project templates and are configured by
  assigning other templates to them, such as process and workflow templates. The templates
  can define standard build processes, source control rules, and testing and reporting
  processes.
maintainers:
- name: IBM
- name: IBM DevOps Build
name: ibm-devops-build
version: 1.0.1
