global:
  domain: "" #Required
  serviceDomainPrefix: ""
  imagePullSecrets: []
  imageRegistry:
  persistence:
    rwoStorageClass: ""
    rwxStorageClass: ""
  ibmCertSecretName: #Optional; used if Ingress requires a secret or to terminate TLS in Emissary directly

  ambassadorId: ""

  cmdKubectl: 

  rationalLicenseKeyServer: ""
  hclLicensingURL: 
  hclLicensingID: ""

  platform:
    enabled:  #Must be enabled

    path: 
    embedPath: #relative to path

    oidc:
      logoutPath: 

      issuerPath: 
      authorizationPath:
      tokenPath:
      userinfoPath:
      introspectionPath:
      jwksPath:

    smtp:
      sender: "" #Required
      host: "" #Required
      port: "" #Required - should be an integer
      username: "" #Optional, leave blank if not needed
      password: "" #Optional, leave blank if not needed
      startTLS: false
      smtps: false

    emissary:
      listener:
        securityModel: 
        l7Depth: #Layer 7 depth; auto-incremented if Ingress forwarding is enabled
      ingressForwarding:
        #Set to true to enable Ingress forwarding
        #Set false to disable Ingress forwarding if an ingress controller is installed 
        #and you need to use Emmissary ingress directly
        enabled:
        className: "" #Optional; set to the name of the IngressClass to use if necessary

# DevOps Build version
version: "7.1.0-1178647"

license:
  accept: true

image:
  repoDigests: false

secret:
  name: ""

deploy:
  enabled: true

readinessProbe:
  initialDelaySeconds: 180
  periodSeconds: 30
  failureThreshold: 10

livenessProbe:
  initialDelaySeconds: 300
  periodSeconds: 180
  failureThreshold: 3

volumes:
  accessMode: ReadWriteOnce
  conf:
    storage: 100Mi
  libExt:
    storage: 100Mi
  plugin:
    storage: 500Mi
  var:
    storage: 15Gi

server:
  home: /opt/devops-build-server
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent #Change before pushing
  service:
    name: devops-build-server
    timeout_ms: 20000 #20 seconds
    ports:
      https: 8443
      http: 8080
      agent: 7919

agent:
  enabled: true
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent
  env: 
    REMOTE_HOST_URL: "devops-build-server"
    REMOTE_HOST_PORT: "7919"
  service:
    name: devops-build-agent
    ports:
      agent: 7919

mysql:
  replicaCount: 1
  database: "devops_build"
  user: "devops_build"
  password: "password"
  service:
    name: devops-build-mysql # Change to dynamically update to ucd-database, REMOVE SOMETIME LATER
    port: 3306
  pvc:
    storage: "1Gi"

platform:
  oidc:
    clientId: devopsbuild
    clientSecret: '{{ tpl (index .Values "ibm-devops-build" "platform" "oidc" "clientSecret") . }}'

ingress:
  path: "/"
  className: nginx