{{- if .Values.logstash.service -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ccm.fullname" . }}-logstash-configmap
  labels:
    {{- include "ccm.labels" . | nindent 4 }}
data:
  logstash.conf: |-
    input {
      http {
        port => {{ .Values.logstash.port }}
        codec => multiline {
          pattern => "^%{TIMESTAMP_ISO8601}"
          negate => true
          what => "previous"
        }
      }
    }
    output {
      opensearch { 
        hosts => ["https://{{ include "ccm.fullname" . }}-opensearch:9200"] 
        ssl => true
        ssl_certificate_verification => false
      {{- if .Values.logstash.username }}
        user => {{ .Values.logstash.username }}
      {{- end }}
      {{- if .Values.logstash.password }}
        password => {{ .Values.logstash.password }}
      {{- end }}
        index => "logstash-ccm-logs-in-%{+YYYY.MM.dd}"
      }
      stdout { 
      } 
    }
{{- end -}}
