{{- if .Values.logstash.service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ccm.fullname" . }}-logstash
  labels:
    {{- include "ccm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - name: http
      port: {{ .Values.logstash.port }}
      protocol: TCP
      targetPort: {{ .Values.logstash.port }}
  selector:
    app.kubernetes.io/name: {{ include "ccm.name" . }}-logstash
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
