{{- if (.Capabilities.APIVersions.Has "getambassador.io/v2") }}
{{- if .Values.emissary.host.enabled }}
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: {{ include "devops-platform.componentFullname" (dict "componentName" "https-listener" "context" .) }}
  labels:
    {{- include "devops-platform.labels" (dict "componentName" "https-listener" "context" .) | nindent 4 }}
spec:
{{- if .Values.global.ambassadorID }}
  ambassador_id: [ '{{ .Values.emissary.ambassadorID }}' ]
{{- end }}
  port: {{ .Values.emissary.listener.httpsPort }}
  protocol: HTTPS
  hostBinding:
    namespace:
      from: SELF
  securityModel: {{ .Values.global.platform.emissary.listener.securityModel }}
  l7Depth: {{ .Values.global.platform.emissary.listener.l7Depth }}
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: {{ include "devops-platform.componentFullname" (dict "componentName" "wss-listener" "context" .) }}
  labels:
    {{- include "devops-platform.labels" (dict "componentName" "wss-listener" "context" .) | nindent 4 }}
spec:
{{- if .Values.global.ambassadorID }}
  ambassador_id: [ '{{ .Values.emissary.ambassadorID }}' ]
{{- end }}
  port: {{ .Values.emissary.listener.wssPort }}
  protocol: TCP
  hostBinding:
    namespace:
      from: SELF
  securityModel: {{ .Values.global.platform.emissary.listener.securityModel }}
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: {{ include "devops-platform.componentFullname" (dict "componentName" "ssh-listener" "context" .) }}
  labels:
    {{- include "devops-platform.labels" (dict "componentName" "ssh-listener" "context" .) | nindent 4 }}
spec:
{{- if .Values.global.ambassadorID }}
  ambassador_id: [ '{{ .Values.emissary.ambassadorID }}' ]
{{- end }}
  port: {{ .Values.emissary.listener.sshPort }}
  protocol: TCP
  hostBinding:
    namespace:
      from: SELF
  securityModel: {{ .Values.global.platform.emissary.listener.securityModel }}
{{- if .Values.global.platform.emissary.ingressForwarding.enabled }}
---
{{- $l7Depth := .Values.global.platform.emissary.listener.l7Depth }}
{{- if .Values.global.platform.emissary.ingressForwarding.enabled }}
{{- $l7Depth = add $l7Depth 1 }}
{{- end }}

apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: {{ include "devops-platform.componentFullname" (dict "componentName" "http-listener" "context" .) }}
  labels:
    {{- include "devops-platform.labels" (dict "componentName" "http-listener" "context" .) | nindent 4 }}
spec:
{{- if .Values.global.ambassadorID }}
  ambassador_id: [ '{{ .Values.emissary.ambassadorID }}' ]
{{- end }}
  port: {{ .Values.emissary.listener.httpPort }}
  protocol: HTTP
  hostBinding:
    namespace:
      from: SELF
  securityModel: {{ .Values.global.platform.emissary.listener.securityModel }}
  l7Depth: {{ $l7Depth }}
{{- end }}
{{- end }}
{{- end }}