{{- if (.Capabilities.APIVersions.Has "getambassador.io/v2") }}
{{- if .Values.emissary.host.enabled }}

{{- $prefix := .Values.global.serviceDomainPrefix | default "" -}}
 
{{- if $prefix }}
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: {{ include "devops-platform.componentFullname" (dict "componentName" "service-host" "context" .) }}
  labels: {{- include "devops-platform.labels" (dict "componentName" "service-host" "context" .) | nindent 4 }}
spec:
{{- if .Values.global.ambassadorID }}
  ambassador_id: [ '{{ .Values.global.ambassadorID }}' ]
{{- end }}
  hostname: {{ (printf "%s%s" $prefix .Values.global.domain ) }}
  acmeProvider:
    authority: {{ .Values.emissary.host.authority }}
  requestPolicy:
    insecure:
      action: Redirect 
{{- end }}
{{- end }}
{{- end }}