{{- if not .Values.backupRestore.enabled}}
{{- if .Values.persistence.enabled }}
{{- if .Values.persistence.search.enabled -}}
---
{{- if and .Values.persistence.search.config.enabled (not .Values.persistence.search.config.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-{{ template "ccm.fullname" . }}-search
{{- with .Values.search.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
{{ include "ccm.labels" . | indent 4 }}
spec:
  accessModes:
  {{ toYaml .Values.persistence.search.config.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.search.config.size | quote }}
{{- if .Values.persistence.search.storageClass }}
  storageClassName: '{{ .Values.persistence.search.storageClass }}'
{{- else if .Values.persistence.storageClass }}
  storageClassName: '{{ .Values.persistence.storageClass }}'
{{- else if .Values.global.persistence.rwoStorageClass }}
  storageClassName: {{ .Values.global.persistence.rwoStorageClass | quote }}
{{- else if .Values.global.persistence.rwxStorageClass }}
  storageClassName: {{ .Values.global.persistence.rwxStorageClass | quote }}
{{- end }}
{{- end }}

---
{{- if and .Values.persistence.search.share.enabled (not .Values.persistence.search.share.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: share-{{ template "ccm.fullname" . }}-search
{{- with .Values.search.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
{{ include "ccm.labels" . | indent 4 }}
spec:
  accessModes:
  {{ toYaml .Values.persistence.search.share.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.search.share.size | quote }}
{{- if .Values.persistence.search.storageClass }}
  storageClassName: '{{ .Values.persistence.search.storageClass }}'
{{- else if .Values.persistence.storageClass }}
  storageClassName: '{{ .Values.persistence.storageClass }}'
{{- else if .Values.global.persistence.rwoStorageClass }}
  storageClassName: {{ .Values.global.persistence.rwoStorageClass | quote }}
{{- else if .Values.global.persistence.rwxStorageClass }}
  storageClassName: {{ .Values.global.persistence.rwxStorageClass | quote }}
{{- end }}
{{- end }}

{{- end }}
{{- end -}}
{{- end -}}
