# Default values for devops-platform.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  domain: "" #Required
  serviceDomainPrefix: "service-"
  imagePullSecret: ibm-entitlement-key
  imagePullSecrets:
  - name: ibm-entitlement-key
  imageRegistry: cp.icr.io/cp

  ibmCertSecretName: #Optional; used if Ingress requires a secret or to terminate TLS in Host or Route directly

  ambassadorId: ""

  cmdKubectl: kubectl

  rationalLicenseKeyServer: ""
  hclLicensingURL: https://cls.hcl-software.com
  hclLicensingID: ""

  platform:
    enabled: true #Must be enabled

    path: /automation
    embedPath: /embed?path= #relative to path

    brand: IBM

    oidc:
      logoutPath: /auth/realms/devops-automation/protocol/openid-connect/logout

      issuerPath: /auth/realms/devops-automation
      authorizationPath: /auth/realms/devops-automation/protocol/openid-connect/auth
      tokenPath: /auth/realms/devops-automation/protocol/openid-connect/token
      userinfoPath: /auth/realms/devops-automation/protocol/openid-connect/userinfo
      introspectionPath: /auth/realms/devops-automation/protocol/openid-connect/introspect
      jwksPath: /auth/realms/devops-automation/protocol/openid-connect/certs

    smtp:
      sender: "" #Required
      host: "" #Required
      port: "" #Required - should be an integer
      username: "" #Optional, leave blank if not needed
      password: "" #Optional, leave blank if not needed
      startTLS: false
      smtps: false

    emissary:
      ingressClassName: "ambassador"
      listener:
        securityModel: XFP
        l7Depth: 0 #Layer 7 depth; auto-incremented if Ingress forwarding is enabled
      ingressForwarding:
        #Set to true to enable Ingress forwarding
        #Set false to disable Ingress forwarding if an ingress controller is installed 
        #and you need to use Emmissary ingress directly
        enabled: true
        className: "" #Optional; set to the name of the IngressClass to use if necessary

# Change license to true to indicate you have read and agree to license agreements : https://ibm.biz/devops-automation-license
license: false

emissary:
  host:
    enabled: true
    authority: none

  service:
    name: emissary-ingress #Name of Emissary ingress service
    namespace: emissary #Namespace for Emissary ingress service
    httpPort: 80 #Http forward port for Emissary ingress service

  listener:
    httpsPort: 8443
    httpPort: 8080
    wssPort: 7919
    sshPort: 9022

  ingressForwarding:
    nginx:
      proxyBufferSize: 32k
      proxyBuffersNumber: 8
      proxyBusyBuffersSize: 32k

frontend:
  replicaCount: 1
  image: ibm-devops-automation-frontend:f736907
  name: devops-automation-frontend
  service:
    port: 8080

  ingress:
    timeout: 10000

  serviceAccount:
    create: true
    annotations: {}

  #Standard labels and annotations will automatically be applied
  deploymentAnnotations: {}
  podAnnotations: {}
  podLabels: {}

  resources: {}

tenant:
  replicaCount: 1
  image: ibm-devops-automation-tenant:1da485b
  name: devops-automation-tenant
  service:
    port: 8080

  apiPath: /rest

  platform:
    oidc:
      clientId: "devopstenant"
      clientSecret: '{{ .Release.Name }}-ibm-devops-platform-tenant-oauth'
      clientRoles: realm-management:manage-realm:manage-clients:manage-authorization:view-users:query-users:impersonation:manage-users devopstenant:ROLE_ADMIN:ROLE_USER:ROLE_SYSTEM

  ingress:
    path: /tenant
    timeout: 60000

  existingPostgresqlPassword: ''

  serviceAccount:
    create: true
    annotations: {}

  #Standard labels and annotations will automatically be applied
  deploymentAnnotations: {}
  podAnnotations: {}
  podLabels: {}

  resources: {}

analyticsai:
  replicaCount: 1
  image: ibm-devops-automation-analyticsai:9f75260
  name: devops-automation-analyticsai
  service:
    port: 8080
  apiPath: /rest
  platform:
    oidc:
      clientId: "devopsanalyticsai"
      clientSecret: '{{ .Release.Name }}-ibm-devops-platform-analyticsai-oauth'
      clientRoles: devopsanalyticsai:ROLE_ADMIN:ROLE_USER:ROLE_SYSTEM

  ingress:
    path: /analyticsai
    timeout: 60000

  existingPostgresqlPassword: ''

  serviceAccount:
    create: true
    annotations: {}

  #Standard labels and annotations will automatically be applied
  deploymentAnnotations: {}
  podAnnotations: {}
  podLabels: {}

  resources: {}

loop:
  replicaCount: 1
  image: ibm-devops-automation-loop:268ebec
  name: devops-automation-loop
  service:
    port: 8080

  apiPath: /rest

  platform:
    oidc:
      clientId: "devopsloop"
      clientSecret: '{{ .Release.Name }}-ibm-devops-platform-loop-oauth'
      clientRoles: devopsloop:ROLE_ADMIN:ROLE_USER:ROLE_SYSTEM

  ingress:
    path: /loop
    timeout: 60000

  existingPostgresqlPassword: ''

  serviceAccount:
    create: true
    annotations: {}

  #Standard labels and annotations will automatically be applied
  deploymentAnnotations: {}
  podAnnotations: {}
  podLabels: {}

  resources: {}

licensing:
  replicaCount: 1
  image: ibm-devops-automation-licensing:3b697ac
  name: devops-automation-licensing
  service:
    port: 8080

  apiPath: /rest

  ingress:
    path: /license
    timeout: 60000

  serviceAccount:
    create: true
    annotations: {}

  #Standard labels and annotations will automatically be applied
  deploymentAnnotations: {}
  podAnnotations: {}
  podLabels: {}

  resources: {}

keycloak-init:
  serviceAccount:
    create: true
    annotations: {}

  #Standard labels and annotations will automatically be applied
  deploymentAnnotations: {}
  podAnnotations: {}
  podLabels: {}

  resources: {}

init:
  image: ibm-devops-automation-jdk17:1.0.4

keycloak:
  realmTheme: isv
  #Realm roles and groups are defined below. Note: DevOps Test also creates ROLE_ADMIN. Defining it here is redundant, but retained for consistency.
  realmRoles: '[{"name":"ROLE_USER","description":"User role"},{"name":"ROLE_ADMIN","description":"Admin role"},{"name":"ROLE_SYSTEM","description":"System role"}]'
  realmGroups: '[{"name":"Users","realmRoles":["ROLE_USER"]},{"name":"Admins","realmRoles":["ROLE_ADMIN"]}]'

platform:
  redirectRoot: true

  imagePullPolicy: IfNotPresent
  #imageRegistry: "some repo" # Overrides global image registry

  oidc:
    clientId: devopsautomation
    logoutPath: /logout #Fixed value

  deploy:
    enabled: true

  plan:
    enabled: true

  velocity:
    enabled: true
    plugins:
      #BRAND: These plugin images are for IBM, the HCL images reside in the Jenkinsfile. Be sure to update the sed if changing these!
      plan:
        image: urbancode/ucv-ext-compass:1.1.58
      control:
        image: urbancode/ucv-ext-control:1.0.5
      test:
        image: urbancode/ucv-ext-onetest-server:1.0.27
      deploy:
        image: urbancode/ucv-ext-ucd:4.0.9

  code:
    enabled: true

  build:
    enabled: true

  # this is the featureflag which enables and disable the loop disable feature   
  disable:
    enabled: false

  # this is for intervals and attempts for loop tasks
  loopSettings:
    interval: 6000
    maxRetries: 200

  # this is the featureflag which enables and disable the loop and teamspace edit feature   
  manage_users_teamspace:
    enabled: true
  manage_users_loop:
    enabled: true

  # this is the featureflag which enables and disable the loop and teamspace members delete icon feature in edit page
  delete_user:
    enabled: false

  podSecurityContext:
    fsGroup: 1001
    runAsUser: 1001
    runAsNonRoot: true
  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault

  livenessProbe:
    enabled: false
    httpGet:
      path: /
      port: http

  readinessProbe:
    httpGet:
      path: /
      port: http

  #Standard labels and annotations will automatically be applied
  deploymentAnnotations: {}
  podAnnotations: {}
  podLabels: {}

#DevOps Test
ibm-devops-prod:
  ingress:
    path: '/test'
    host:
      enabled: false
    cert:
      create: false
      selfSigned: false
  license: true
  keycloak:
    realm: devops-automation
  # Configure devops-prod to add a postgres DB and user for Control
  # (this chart provides the secret)
  postgresql:
    dbs:
      tenant:
        connections: 21
        secret: '{{ .Release.Name }}-tenant-postgres-password'
      analyticsai:
        connections: 21
        secret: '{{ .Release.Name }}-analyticsai-postgres-password'
      loop:
        connections: 21
        secret: '{{ .Release.Name }}-loop-postgres-password'
      control:
        connections: 21
        secret: '{{ .Release.Name }}-control-postgres-password'

#DevOps Deploy
ibm-ucd-prod:
  platform:
    oidc:
      clientId: "devopsdeploy"
      logoutPath: /tasks/LoginTasks/logout #Fixed value
  ingress:
    path: "/deploy"
  license:
    accept: true
  database:
    createDatabase: true
    name: ucdtest
    username: ucduser
  secureConnections:
    # Do TLS termination at the Route/Ingress
    required: false

## DevOps Plan
ibm-devopsplan-prod:
  platform:
    oidc:
      clientId: "devopsplan"
      logoutPath: /#/ccmweb/logoff
    opensearch:
      oidc:
        clientId: opensearch
        clientSecret: '{{ .Release.Name }}-ibm-devops-platform-opensearch-oauth'
        rolesClaim: "roles"
        enableIDToken: true
  keycloak:
    realmName: "devops-automation"
    username: "keycloak"
    authServerPath: /auth
  keycloaksrv:
    enabled: false
  ingress:
    path: /plan
    type: mapping
    cert:
      selfSigned: false
  dashboards:
    basePath: "/opensearch-dashboards"

  llama:
    enabled: false

  nameOverride: "ibm-devopsplan-prod"

  ## Control (subchart of Plan)
  control:
    enabled: true
    ingress:
      path: '/control'
    existingPostgresqlPassword: ''
    platform:
      # webhook_allowed_host_list: "host1,host2,ipaddr1,ipaddr2"
      oidc:
        clientId: control
        clientSecret: '{{ .Release.Name }}-ibm-devops-platform-control-oauth'
        logoutPath: /user/logout #Fixed value
    postgresql:
      enabled: false # Use the DB configured above by ibm-devops-prod
      nameOverride: controldb
    gitea:
      oauth:
      - name: 'DevOps Loop'
        provider: 'openidConnect'
        existingSecret: 'replaced during helm processing'
        autoDiscoverUrl: 'also replaced during helm processing'
        skipLocal2fa: true
        adminGroup: ROLE_ADMIN
        groupClaimName: groups
        scopes: "openid microprofile-jwt"

ibm-ucv-prod:
  license: "accept"
  platform:
    oidc:
      clientId: devopsvelocity
      clientSecret: '{{ .Release.Name }}-ibm-devops-platform-devopsvelocity-oauth'
      logoutPath: /logout #Fixed value
  ingress:
    path: /velocity
  secrets:
    database: mongodb-url-secret
  imageRegistry:
    velocityPath: /ibm-ucv-


## DevOps Code
ibm-devopscode:
  platform:
    oidc:
      clientId: "devopscode"
      logoutPath: /logout
  ingress:
    path: /code

# DevOps Build
ibm-devops-build:
  platform:
    oidc:
      clientId: devopsbuild
      clientSecret: '{{ .Release.Name }}-ibm-devops-platform-devopsbuild-oauth'
      logoutpath: /logout
  ingress:
    path: /build
