frontend:
  image: ibm-devops-automation-frontend

init:
  image: ibm-devops-automation-jdk17

licensing:
  image: ibm-devops-automation-licensing

loop:
  image: ibm-devops-automation-loop

tenant:
  image: ibm-devops-automation-tenant

analyticsai:
  image: ibm-devops-automation-analyticsai