global:
  cmdKubectl: oc

  ingress:
    enabled: false

emissary:
  host:
    enabled: false

platform:
  podSecurityContext:
    fsGroup:
    runAsUser:


ibm-devops-prod:
  ingress:
    type: route

  networkPolicy:
    enabled: true
    ingress:
      namespaceLabel: network.openshift.io/policy-group
      namespaceValue: ingress

  securityContext:
    fsGroup: 'null'
    runAsUser: 'null'

  execution:
    ingress:
      hostPattern: '{{ regexReplaceAll "^([^.]*)" .Values.global.domain "$1-*" }}'

ibm-devopsplan-prod:
  ingress:
    enabled: true
    type: route

  control:
    ingress:
      type: route

    networkPolicy:
      enabled: true
      ingress:
        namespaceLabel: network.openshift.io/policy-group
        namespaceValue: ingress

    containerSecurityContext:
      capabilities:
        # un-do default SYS_CHROOT which OpenShift blocks.  may break SSH. Or
        # it may not.
        add: []
      seccompProfile:
        type: RuntimeDefault
      # "null" is specially processed so we skip adding it, and let
      # OpenShift use its own values
      runAsUser: "null"
      runAsGroup: "null"
    podSecurityContext:
      fsGroup: "null"

    execution:
      ingress:
        hostPattern: '{{ regexReplaceAll "^([^.]*)" .Values.global.domain "$1-*" }}'

    serviceAccount:
      create: true

    service:
      ssh:
        # Can't use default LoadBalancer port 9022, it's not in the NodePort
        # allowed range.  By using NodePort, we'll get a failure to deploy to
        # OpenShift if the port is in use...in which case, supply these
        # values separately to the helm command line.
        nodePort: 30328
        type: NodePort
    gitea:
      config:
        server:
          SSH_PORT: 30328

    strategy:
      type: "Recreate"
    persistence:
      accessModes:
      - ReadWriteOnce

ibm-ucv-prod:
  runAsUser: 'null'
