springfox.documentation.swagger.v2.path=/api-docs
spring.main.allow-circular-references=true
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
server.servlet.context-path=/
server.port=8190
server.error.path=/error
server.error.whitelabel.enabled=false
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=keypass
server.ssl.keyStoreType=PKCS12
server.ssl.keyAlias=tomcat
server.ssl.enabled-protocols=TLSv1.2
server.error.include-message=always
spring.jackson.date-format=com.hcl.ccm.rest.RFC3339DateFormat
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
server.qualified.url.path=https://localhost:8190
jwt-token-validity-ms=1800000
jwt-refresh-token-validity-ms=21600000
jwt-invitation-token-lifetime-days=7
log-stats-time-ms=300000
default-page-size=10
result-set-timeout=30
attachments-audit-time=15
session-audit-time-ms=480000
session-timeout-ms=600000
interactive-edit-timeout-ms=1800000
repos-refresh-time-ms=900000
view-url=/index.html
spring.servlet.multipart.max-file-size=104857600
spring.servlet.multipart.max-request-size=106954752
webhook-publish-retries=10
webhook-configuration-data-poll=1
webhook-configuration-poll=15
## SYSTEM LOGINS BEGIN
hook-user-name=system_hooks
SYSTEM_GROUP_SCM=SCMIntegrationAdmins
SYSTEM_USER_SCM=SCMIntegrationUser
system-session-audit-time-ms=480000
system-session-timeout-ms=600000
## SYSTEM LOGINS END
## SCM BEGIN
logging.level.com.hcl.ccm.rest.scm=INFO
GITLAB_TREE_PATH=/-/tree/
# global flag to specify if hooks are to be handled synchronously (true/false)
scm-synchronous=true
## SCM END
logging.level.com.hcl.ccm=INFO
logging.level.org.springframework.web=INFO
spring.mvc.log-request-details=false
spring.web.resources.cache.cachecontrol.max-age=365d
spring.web.resources.chain.strategy.content.enabled=true
spring.web.resources.chain.strategy.content.paths=/**

################################
# Keycloak configuration BEGIN

#global falg to enable disable Keycloak integration (true/false)
keycloak.enabled=false
#Max number of users to retrieve from Keycloak at one time
keycloak-max-user-retrieval=2000
keycloak-config-file=keycloak.json

#Keycloak field name which contains IDP/Fed name (compass_identity_provider)
keycloak-identity-provider-field-name=compass_identity_provider

#List of allowed IDP/Feds
#Empty means all are allowed
#keycloak-identity-provider-values=IDP1,IDP2,LDAP1
keycloak-identity-provider-values=

# possible mapping fields: preferred_username or email
keycloak-mapping-field=preferred_username

logging.level.org.keycloak=INFO

# Keycloak configuration END
################################

# enable actuator metrics
management.endpoints.web.exposure.include=metrics,elastic
management.metrics.export.elastic.enabled=false
management.metrics.export.elastic.step=5m
management.metrics.export.elastic.index=ccm-metrics
management.metrics.export.elastic.auto-create-index=false
management.metrics.export.elastic.host=https://localhost:9200
management.metrics.export.elastic.userName=admin
management.metrics.export.elastic.password=admin
management.metrics.tags.host=localhost
management.metrics.tags.application=ccm
management.metrics.export.elastic.sslVerify=false

#################################
# Togglz Configurtation
togglz.console.enabled=true
togglz.console.path=/compass-features
togglz.console.secured=false
logging.level.org.togglz=trace
togglz.console.use-management-port=false
togglz.features-file=file:./features.properties
# END
#################################


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email
spring.mail.password=your_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

##################################
cors.allowedOrigins=
##################################


###############Email Relay Configuration ########

#value in milli-seconds
email-configuration-data-poll-ms=60000
# Compass user name used for reading data
system-user-name=SYSTEM_ANALYTICS
#########################################

###############Feedback Configuration ########

feedback.hostname=8/JWXwIYG2p8wxTqxZugdep8tdhVM/bbW6Nli8SXlujwDIOaL17M+Dm8KRivuLko
feedback.username=kNqP7hKQwzQNGIU5vhcJsj8wWYP1b0Cu2G0eOcnPPCQ=
feedback.password=SmaUxXk3Q50a5QsCwjXzX+rYEgJRrwJLm9GJCl74oiyShVnS9KPEb0ubr+azL5UM
feedback.to.emailaddress=
feedback.from.emailaddress=
#########################################