{{- if include "testhub.extensions.enabled" . }}
{{- if (or (or (or (or (or (or (or (or (or .Values.extensions.jmeter.enabled .Values.extensions.junit.enabled) .Values.extensions.postman.enabled) .Values.extensions.codesweep.enabled) .Values.extensions.script.enabled) .Values.extensions.azure.enabled) .Values.extensions.etm.enabled) .Values.extensions.jira.enabled) .Values.extensions.plan.enabled) .Values.extensions.ai.enabled)}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: extensions
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-extensions'
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: '{{ .Release.Name }}'
      app.kubernetes.io/name: extensions
      app.kubernetes.io/part-of: '{{ .Chart.Name }}'
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        productID: e3e180b0faae4301b54c5c9b37319e5c
        productMetric: FLOATING_USER
        productName: IBM Rational Test Automation Server Basic
        productVersion: "11.0.5"
        cloudpakName : IBM DevOps for IBM Cloud Paks
        cloudpakId : dedb7a9445a44fb88c927c1658243cd1
        cloudpakMetric : RESOURCE_UNIT
        productCloudpakRatio : "1:1"
        productChargedContainers : All
      labels:
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/name: extensions
        app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
{{- if .Values.priorityClassName }}
      priorityClassName: '{{ .Values.priorityClassName }}'
{{- end }}
      containers:
      - env:
        - name: all-extensions-add-on.registrationApiKey
          valueFrom:
            secretKeyRef:
              key: addon-registration-secret
              name: '{{ .Release.Name }}-router'
        - name: OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: oauth-client-secret
              name: '{{ .Release.Name }}-extensions'
        - name: INGRESS_DOMAIN
          value: '{{ .Values.global.domain }}'
        - name: SPRING_APPLICATION_JSON
          value: >
            {
              "server": {
                "forward-headers-strategy": "NATIVE",
                "servlet": {
                  "context-path" : "{{ .Values.ingress.path }}"
                }
              },
              "extensions": {
                "jmeter": {
                  "enabled" : "{{.Values.extensions.jmeter.enabled }}"
                },
                "junit": {
                  "enabled" : "{{.Values.extensions.junit.enabled }}"
                },
                "postman": {
                  "enabled" : "{{.Values.extensions.postman.enabled }}"
                },
                "codesweep": {
                  "enabled" : "{{.Values.extensions.codesweep.enabled }}"
                },
                "script": {
                  "enabled" : "{{.Values.extensions.script.enabled }}"
                },                
                "azure": {
                  "enabled" : "{{.Values.extensions.azure.enabled }}"
                },
                "plan": {
                  "enabled" : "{{.Values.extensions.plan.enabled }}"
                },
                "etm": {
                  "enabled" : "{{.Values.extensions.etm.enabled }}"
                },
                "jira": {
                  "enabled" : "{{.Values.extensions.jira.enabled }}"
                },
                "ai": {
                  "enabled" : "{{.Values.extensions.ai.enabled }}"
                }
              },
              "spring": {
                "datasource": {
                  "url": "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/extensions",
                  "username": "extensions"
                },
                "rabbitmq": {
                  "host": "{{ .Release.Name }}-rabbitmq",
                  "port": "5672",
                  "username": "user"
                },
                "security": {
                  "oauth2": {
                    "client": {
                      "registration": {
                        "internal": {
                          "authorization-grant-type": "client_credentials",
                          "client-id": "testserver-extensions",
                          "client-secret": "$(OAUTH_CLIENT_SECRET)",
                          "provider": "keycloak"
                        }
                      },
                      "provider": {
                        "keycloak": {
                          "token-uri": "https://$(INGRESS_DOMAIN){{ .Values.keycloak.path }}/realms/{{ .Values.keycloak.realm }}/protocol/openid-connect/token"
                        }
                      }
                    },
                    "resourceserver": {
                      "jwt": {
                        "jwk-set-uri": "https://$(INGRESS_DOMAIN){{ .Values.keycloak.path }}/realms/{{ .Values.keycloak.realm }}/protocol/openid-connect/certs"
                      }
                    }
                  }
                }
              }
            }
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgresql-password
              name: '{{ .Release.Name }}-extensions'
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              key: rabbitmq-password
              name: '{{ .Release.Name }}-rabbitmq'
        image: '{{ (default (default .Values.imageRegistry .Values.global.imageRegistry) .Values.extensions.registry) }}/{{ regexReplaceAll .Values.imageRepoRegex .Values.extensions.image .Values.imageRepoRepl }}'
        imagePullPolicy: IfNotPresent
        startupProbe:
          failureThreshold: 20
          httpGet:
            path: '{{ .Values.ingress.path }}/management/health'
            port: http
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: '{{ .Values.ingress.path }}/management/health'
            port: http
        readinessProbe:
          httpGet:
            path: '{{ .Values.ingress.path }}/management/health'
            port: http
        name: main
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
{{- if .Values.extensions.resources }}
        resources: {{- toYaml .Values.extensions.resources | nindent 10 }}
{{- end }}
{{- template "testhub.container.security-context" .Values.containerSecurityContext }}
        volumeMounts:
        - name: extensions-tmp
          mountPath: /tmp
{{- template "testhub.volumeMounts.trust-store" $ }}
{{- if include "testhub.ibmImagePullSecret" . }}
      imagePullSecrets:
      - name: '{{ include "testhub.ibmImagePullSecret" . }}'
{{- end }}
      initContainers:
{{- template "testhub.initContainers.trust-store" $ }}
      - name: keycloak
        command:
        - sh
        - -ec
        - |
          ./wait.sh $KEYCLOAK_URL/realms/$REALM_NAME/
          ./client-create.sh
        env:
{{- template "testhub.container.keycloak-init-sh-env" $ }}
        - name: CLIENT_ID
          value: testserver-extensions
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: oauth-client-secret
              name: '{{ .Release.Name }}-extensions'
{{- template "testhub.container.keycloak-init-sh-trailer" $ }}
{{- template "testhub.initContainers.pg-isready" (merge (dict "dbName" "extensions") .) }}
{{- template "testhub.initContainers.liquibase-update" (merge (dict "svc" "extensions" "dbName" "extensions") .) }}
{{- template "testhub.initContainers.gateway-isready" $ }}
      hostIPC: false
      hostNetwork: false
      hostPID: false
{{- template "testhub.pod.security-context" $ }}
      serviceAccountName: '{{ .Release.Name }}-extensions'
      volumes:
      - name: extensions-tmp
        emptyDir: {}
{{- template "testhub.volumes.trust-store" $ }}
{{- template "testhub.volumes.keycloak-init-sh" $ }}
{{- end }}
{{- end }}
