{{- if not .Values.global.platform.enabled }}
{{- if (and (or (eq .Values.ingress.type "mapping") (eq .Values.ingress.type "route")) (eq .Values.control.enabled true) (not .Values.control.postgresql.host)) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "ccm.fullname" . }}-postgresql'
  labels:
    {{- include "ccm.labels" . | nindent 4 }}
data:
  postgresql.conf: |
    # Actual max RAM = shared_buffers + (temp_buffers + work_mem) * max_connections
    shared_buffers = '12MB'
    work_mem = '1MB'
    log_lock_waits = on
    lock_timeout = 1min
    deadlock_timeout = 30s
{{- if .Values.postgresql.debugEnabled }}
    pg_stat_statements.max = 10000
    pg_stat_statements.track = all
{{- end }}
{{- end }}
{{- end }}
