{{- if .Values.devopsplan.service }}
apiVersion: v1
kind: Secret
metadata:
metadata:
  name: '{{ include "plan.fullname" . }}-postgresql'
  labels:
    {{- include "ccm.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.postgresql.enabled -}}
{{- if and  .Values.spring.datastore.password .Values.tenant.datastore.password }}
  spring-datastore-password: {{ default "" .Values.spring.datastore.password | b64enc | quote }}
  tenant-datastore-password: {{ default "" .Values.tenant.datastore.password | b64enc | quote }}
{{- if .Values.postgresql.existingPassword }}
  spring-datastore-existingPassword: {{ .Values.postgresql.existingPassword | b64enc | quote }}
  tenant-datastore-existingPassword: {{ .Values.postgresql.existingPassword | b64enc | quote }}
{{- end }}
{{- else }}
{{- if .Values.postgresql.existingPassword }}
  spring-datastore-password: {{ .Values.postgresql.existingPassword | b64enc | quote }}
  tenant-datastore-password: {{ .Values.postgresql.existingPassword | b64enc | quote }}
{{- else }}
  spring-datastore-password: {{ print (default .Release.Name .Values.global.passwordSeed) "postgresql" | sha256sum | b64enc | quote }}
  tenant-datastore-password: {{ print (default .Release.Name .Values.global.passwordSeed) "postgresql" | sha256sum | b64enc | quote }}
{{- end }}
{{- end }}
{{- else }}
  spring-datastore-password: {{ default "" .Values.spring.datastore.password | b64enc | quote }}
  tenant-datastore-password: {{ default "" .Values.tenant.datastore.password | b64enc | quote }}
{{- if .Values.postgresql.existingPassword }}
  spring-datastore-existingPassword: {{ .Values.postgresql.existingPassword | b64enc | quote }}
  tenant-datastore-existingPassword: {{ .Values.postgresql.existingPassword | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
