{{- if or (eq .Values.postgresql.enabled true) (and (or (eq .Values.ingress.type "mapping") (eq .Values.ingress.type "route")) (eq .Values.control.enabled true) (not .Values.control.postgresql.host)) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plan.fullname" . }}-postgresql
  labels:
    {{- include "ccm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgresql.service.type }}
  sessionAffinity: ClientIP
  ports:
    - name: tcp-postgresql
      port: 5432
    {{- if or (eq "NodePort" .Values.postgresql.service.type ) (eq "LoadBalancer" .Values.postgresql.service.type ) }}
    {{- if .Values.postgresql.service.exposePort  }}
      nodePort: {{ .Values.postgresql.service.exposePort }}
    {{- end }}
    {{- end }}
      protocol: TCP
      targetPort: 5432
  selector:
    app.kubernetes.io/name: {{ include "plan.fullname" . }}-postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
