{{- if or (eq .Values.postgresql.enabled true) (and (or (eq .Values.ingress.type "mapping") (eq .Values.ingress.type "route")) (eq .Values.control.enabled true) (not .Values.control.postgresql.host) ) -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "plan.fullname" . }}-postgresql
  labels:
    {{- include "ccm.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "plan.fullname" . }}-postgresql
  replicas: {{ .Values.postgresql.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "plan.fullname" . }}-postgresql
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "plan.fullname" . }}-postgresql
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      annotations:
  {{- if eq "IBM" .Values.global.devopsPlanBrand }}
        productName: {{ .Values.annotations.ibm.productName }}
        productID: {{ .Values.annotations.ibm.productID }}
        productVersion: {{ .Values.annotations.ibm.productVersion }}
        productMetric: {{ .Values.annotations.ibm.productMetric }}
        productChargedContainers: {{ .Values.annotations.ibm.productChargedContainers }}
  {{ else }}
        productName: {{ .Values.annotations.hcl.productName }}
        productVersion: {{ .Values.annotations.hcl.productVersion }}
  {{- end }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.postgresql.nodeAffinity.key }}
                operator: In
                values:
                - {{ .Values.postgresql.nodeAffinity.values }}
  {{- if .Values.postgresql.topologySpreadConstraints.enabled }}
      topologySpreadConstraints:
        - maxSkew: {{ .Values.postgresql.topologySpreadConstraints.maxSkew }}
          topologyKey: {{ .Values.postgresql.topologySpreadConstraints.topologyKey }}
          whenUnsatisfiable: {{ .Values.postgresql.topologySpreadConstraints.whenUnsatisfiable }}
          labelSelector:
            matchLabelKeys:
              app.kubernetes.io/name: {{ include "ccm.name" . }}-postgresql
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- end }}
  {{- if or (.Values.global.imagePullSecret) (.Values.global.imagePullSecrets) }}
      imagePullSecrets:
  {{- if .Values.global.imagePullSecret }}
      - name: {{ .Values.global.imagePullSecret }}
  {{- end }}
      {{- range .Values.global.imagePullSecrets }}
      - name: {{ . }}
      {{- end }}
  {{- end }}
      securityContext:
        runAsNonRoot: true
  {{- if not (.Capabilities.APIVersions.Has "security.openshift.io/v1") }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
  {{- end }}
  {{- if .Values.persistence.enabled }}
  {{- if .Values.persistence.postgresql.enabled }}
      initContainers:
  {{- if and  .Values.spring.datastore.password .Values.tenant.datastore.password .Values.postgresql.existingPassword }}
        - name: init-postgres-pass
     {{- if .Values.image.repoDigests }}
          image: "{{ include "ccm.ccmImageRepo" . }}/{{ .Values.postgresql.repository }}@{{ .Values.postgresql.tag }}"
     {{- else }}
          image: "{{ include "ccm.ccmImageRepo" . }}/{{ .Values.postgresql.repository }}:{{ .Values.postgresql.tag }}"
     {{- end }}
          imagePullPolicy: {{ .Values.postgresql.pullPolicy }}
    {{- if .Values.postgresql.initResources }}
          resources: {{- toYaml .Values.ccm.initResources | nindent 10 }}
    {{- end }}
          securityContext:
            runAsNonRoot: true
    {{- if not (.Capabilities.APIVersions.Has "security.openshift.io/v1") }}
            runAsUser: {{ .Values.securityContext.runAsUser }}
    {{- end }}
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          env:
      {{- if .Values.tenant.datastore.dbname  }}
          - name: POSTGRESQL_DATABASE
            value: "{{ .Values.tenant.datastore.dbname }}"
      {{- end }}
          - name: POSTGRESQL_USERNAME
            value: postgres
          - name: POSTGRESQL_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: {{ include "plan.fullname" . }}-postgresql
                  key: spring-datastore-password
          - name: POSTGRES_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: {{ include "plan.fullname" . }}-postgresql
                  key: spring-datastore-password
      {{- if and  .Values.spring.datastore.password .Values.tenant.datastore.password .Values.postgresql.existingPassword }}
          - name: POSTGRES_EXISTING_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: {{ include "plan.fullname" . }}-postgresql
                  key: spring-datastore-existingPassword
      {{- end }}

          - name: PGDATA
            value: /bitnami/postgresql/data/
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRESQL_CLIENT_MIN_MESSAGES
            value: error
          - name: POSTGRESQL_ENABLE_LDAP
            value: 'no'
          - name: POSTGRESQL_ENABLE_TLS
            value: 'no'
          - name: POSTGRESQL_LOG_CONNECTIONS
            value: '{{ .Values.postgresql.logConnections }}'
          - name: POSTGRESQL_LOG_DISCONNECTIONS
            value: '{{ .Values.postgresql.logDisconnections }}'
          - name: POSTGRESQL_LOG_HOSTNAME
            value: '{{ .Values.postgresql.logHostname }}'
          - name: POSTGRESQL_PGAUDIT_LOG_CATALOG
            value: '{{ .Values.postgresql.aduditLogCatalog }}'
          - name: POSTGRESQL_PORT_NUMBER
            value: '5432'
          - name: POSTGRESQL_SHARED_PRELOAD_LIBRARIES
            value: pgaudit
          - name: POSTGRESQL_VOLUME_DIR
            value: /bitnami/postgresql
          - name: POSTGRESQL_MAX_CONNECTIONS
            value: '{{ .Values.postgresql.maxConnection }}'
          - name: POSTGRESQL_LOG_LINE_PREFIX
            value: '{{ .Values.postgresql.LogLinePrefix }}'
          command:
          - /bin/sh
          - -c
          - echo $(hostname);cat /etc/hosts;PGPASSWORD=$POSTGRES_EXISTING_PASSWORD psql -U postgres -h $(hostname) -c "ALTER ROLE postgres with password '$POSTGRES_PASSWORD'"
          volumeMounts:
            - name: data
              mountPath: /ccm/postgresql
  {{- end }}
  {{- end }}
  {{- end }}
      hostname:  "{{ .Values.postgresql.hostname }}"
      serviceAccount: {{ include "ccm.fullname" . }}-sa
      containers:
      - name: {{ include "plan.fullname" . }}-postgresql
      {{- if and .Values.global.hclPreviewImageRegistry .Values.postgresql.previewTag }}
        image: "{{ .Values.global.hclPreviewImageRegistry }}/{{ .Values.postgresql.repository }}:{{ .Values.postgresql.previewTag }}"
      {{- else }}
      {{- if .Values.image.repoDigests }}
        image: "{{ include "ccm.ccmImageRepo" . }}/{{ .Values.postgresql.repository }}@{{ .Values.postgresql.tag }}"
      {{- else }}
        image: "{{ include "ccm.ccmImageRepo" . }}/{{ .Values.postgresql.repository }}:{{ .Values.postgresql.tag }}"
      {{- end }}
##        image: "bitnami/postgresql:15-debian-11"
        {{- end }}
        imagePullPolicy: {{ .Values.postgresql.pullPolicy }}
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        ports:
          - name: tcp-postgresql
            containerPort: 5432
            protocol: TCP
       {{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.Version }}
       {{- if .Values.probes.startup.postgresql.enabled }}
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
          initialDelaySeconds: {{ .Values.probes.startup.postgresql.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.startup.postgresql.periodSeconds }}
          timeoutSeconds: {{ .Values.probes.startup.postgresql.timeoutSeconds }}
          successThreshold: {{ .Values.probes.startup.postgresql.successThreshold }}
          failureThreshold: {{ .Values.probes.startup.postgresql.failureThreshold }}
      {{- end }}
      {{- end }}
       {{- if .Values.probes.readiness.postgresql.enabled }}
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - -e
            - |
              exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
              [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
          initialDelaySeconds: {{ .Values.probes.readiness.postgresql.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.readiness.postgresql.periodSeconds }}
          timeoutSeconds: {{ .Values.probes.readiness.postgresql.timeoutSeconds }}
          successThreshold: {{ .Values.probes.readiness.postgresql.successThreshold }}
          failureThreshold: {{ .Values.probes.readiness.postgresql.failureThreshold }}
       {{- end }}
       {{- if .Values.probes.liveness.postgresql.enabled }}
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
          initialDelaySeconds: {{ .Values.probes.liveness.postgresql.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.liveness.postgresql.periodSeconds }}
          timeoutSeconds: {{ .Values.probes.liveness.postgresql.timeoutSeconds }}
          successThreshold: {{ .Values.probes.liveness.postgresql.successThreshold }}
          failureThreshold: {{ .Values.probes.liveness.postgresql.failureThreshold }}
      {{- end }}
##      {{- if and  .Values.spring.datastore.password .Values.tenant.datastore.password .Values.postgresql.existingPassword }}
##        lifecycle:
##          postStart:
##            exec:
##              command:
##              - /bin/sh
##              - -c
##              - PGPASSWORD=$POSTGRES_EXISTING_PASSWORD psql -U postgres -h $(hostname) -c "ALTER ROLE postgres with password '$POSTGRES_PASSWORD'"
##        command: ["/bin/bash"]
##        args: ["-c", "PGPASSWORD=$POSTGRES_EXISTING_PASSWORD psql -U postgres -h localhost -c "ALTER ROLE postgres with password '$POSTGRES_PASSWORD'""]
##      {{- end }}
        env:
      {{- if .Values.tenant.datastore.dbname  }}
          - name: POSTGRESQL_DATABASE
            value: "{{ .Values.tenant.datastore.dbname }}"
      {{- end }}
          - name: POSTGRESQL_USERNAME
            value: postgres
          - name: POSTGRESQL_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: {{ include "plan.fullname" . }}-postgresql
                  key: spring-datastore-password
          - name: POSTGRES_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: {{ include "plan.fullname" . }}-postgresql
                  key: spring-datastore-password
      {{- if and  .Values.spring.datastore.password .Values.tenant.datastore.password .Values.postgresql.existingPassword }}
          - name: POSTGRES_EXISTING_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: {{ include "plan.fullname" . }}-postgresql
                  key: spring-datastore-existingPassword   
      {{- end }}

          - name: PGDATA
            value: /bitnami/postgresql/data/
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRESQL_CLIENT_MIN_MESSAGES
            value: error
          - name: POSTGRESQL_ENABLE_LDAP
            value: 'no'
          - name: POSTGRESQL_ENABLE_TLS
            value: 'no'
          - name: POSTGRESQL_LOG_CONNECTIONS
            value: '{{ .Values.postgresql.logConnections }}'
          - name: POSTGRESQL_LOG_DISCONNECTIONS
            value: '{{ .Values.postgresql.logDisconnections }}'
          - name: POSTGRESQL_LOG_HOSTNAME
            value: '{{ .Values.postgresql.logHostname }}'
          - name: POSTGRESQL_PGAUDIT_LOG_CATALOG
            value: '{{ .Values.postgresql.aduditLogCatalog }}'
          - name: POSTGRESQL_PORT_NUMBER
            value: '5432'
          - name: POSTGRESQL_SHARED_PRELOAD_LIBRARIES
            value: pgaudit
          - name: POSTGRESQL_VOLUME_DIR
            value: /bitnami/postgresql
          - name: POSTGRESQL_MAX_CONNECTIONS
            value: '{{ .Values.postgresql.maxConnection }}'
          - name: POSTGRESQL_LOG_LINE_PREFIX
            value: '{{ .Values.postgresql.LogLinePrefix }}'
      {{- if .Values.persistence.enabled }}
      {{- if .Values.persistence.postgresql.enabled }}
        volumeMounts:
        - mountPath: /bitnami/postgresql
          name: data
      {{- end }}
      {{- end }}
        resources:
          {{- toYaml .Values.postgresql.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- if .Values.persistence.enabled }}
{{- if .Values.persistence.postgresql.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app.kubernetes.io/name: {{ include "plan.fullname" . }}-postgresql
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.persistence.annotations  }}
      annotations:
{{ toYaml . | indent 8 }}
    {{- end }}
    spec:
      accessModes:
      {{ toYaml .Values.persistence.postgresql.accessModes | indent 4 }}
{{- if .Values.persistence.postgresql.storageClass }}
      storageClassName: '{{ .Values.persistence.postgresql.storageClass }}'
{{- else if .Values.persistence.storageClass }}
      storageClassName: '{{ .Values.persistence.storageClass }}'
{{- else if .Values.global.persistence.rwoStorageClass }}
      storageClassName: {{ .Values.global.persistence.rwoStorageClass | quote }}
{{- else if .Values.global.persistence.rwxStorageClass }}
      storageClassName: {{ .Values.global.persistence.rwxStorageClass | quote }}
{{- end }}
      resources:
        requests:
          storage: "{{ .Values.persistence.postgresql.size }}"
{{- end -}}
{{- end -}}
{{- end -}}

