{{- if (.Capabilities.APIVersions.Has "getambassador.io/v2") }}
apiVersion: getambassador.io/v2
kind: TCPMapping
metadata:
  name: {{ .Release.Name }}-build-agent-tcpmapping
  labels:
{{ include "ibm-devops-build.labels" . | indent 4 }}
spec:
  service: {{ .Values.server.service.name }}:{{ .Values.server.service.ports.agent }}
  port: 7920
{{- end }}