{{- if not .Values.deploy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.service.name }}
  labels:
{{ include "ibm-devops-build.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.mysql.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mysql.service.name }}
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.service.name }}
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      containers:
      - name: {{ .Values.mysql.service.name }}
        image: mysql:8.0
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-build-secrets
              key: dbpassword
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-devops-build-pvc
{{- end }}