{{- if not .Values.deploy.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-devops-build-pvc
  labels:
{{ include "ibm-devops-build.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.pvc.storage }}
{{- end }}