apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-properties-config
  labels:
{{ include "ibm-devops-build.labels" . | indent 4 }}

data:
  installed.properties: |
    global.domain={{ .Values.global.domain }}
    global.platform.enabled={{ .Values.global.platform.enabled }}
    global.rationalLicenseKeyServer={{ .Values.global.rationalLicenseKeyServer }}
    global.platform.path={{ .Values.global.platform.path }}
    global.platform.oidc.issuerPath=https://{{ .Values.global.domain }}{{ .Values.global.platform.oidc.issuerPath }}
    global.platform.oidc.authorizationPath=https://{{ .Values.global.domain }}{{ .Values.global.platform.oidc.authorizationPath }}
    global.platform.oidc.tokenPath=https://{{ .Values.global.domain }}{{ .Values.global.platform.oidc.tokenPath }}
    global.platform.oidc.userinfoPath=https://{{ .Values.global.domain }}{{ .Values.global.platform.oidc.userinfoPath }}
    global.platform.oidc.introspectionPath=https://{{ .Values.global.domain }}{{ .Values.global.platform.oidc.introspectionPath }}
    global.platform.oidc.jwksPath=https://{{ .Values.global.domain }}{{ .Values.global.platform.oidc.jwksPath }}
    global.platform.oidc.logoutPath=https://{{ .Values.global.domain }}{{ .Values.global.platform.oidc.logoutPath }}
    global.ibmCertSecretName={{ .Values.global.ibmCertSecretName }}
    platform.oidc.clientId={{ .Values.platform.oidc.clientId }}
    ####################################################################################################
    # Specify these as-is
    ####################################################################################################
    java.io.tmpdir=/opt/devops-build-server/var/temp
    install.java.home=/opt/ibm/java/jre
    automatic.server.upgrade.enabled=true
    install.server.brokerUrl=failover\:(ah3\://{{ .Values.server.service.name }}\:7919?soTimeout\=60000&daemon\=true)
    install.server.brokerConfigUrl=xbean\:activemq.xml
    install.server.startBroker=false
    server.appdata.dir=..
    install.server.launchBrokerProcess=true
    install.server.web.ip=0.0.0.0
    install.server.automation.redirect=true

    # Keystore location should not change. The actual keystore files (if needed), will be mounted in
    # the container and shadow the default file.
    install.server.keystore=../conf/server.keystore
    encryption.keystore.file=../conf/encryption.keystore

    automatic.keystore.generation.enabled=true
    automatic.server.upgrade.enabled=true
    ####################################################################################################

    ####################################################################################################
    # Bring your own value
    ####################################################################################################
    install.server.db.type=mysql
    {{- if .Values.deploy.enabled }}
    install.server.db.url=jdbc\:mysql\://{{ .Release.Name }}-ibm-ucd-prod-mysql\:3306/{{ .Values.mysql.database }}?useUnicode\=true&characterEncoding\=UTF-8
    {{- else }}
    install.server.db.url=jdbc\:mysql\://{{ .Values.mysql.service.name }}\:3306/{{ .Values.mysql.database }}?useUnicode\=true&characterEncoding\=UTF-8
    {{- end }}
    install.server.db.user={{ .Values.mysql.user }}
    install.server.db.driver=com.mysql.cj.jdbc.Driver

    install.server.external.web.url=https\://{{ .Values.global.domain }}{{ .Values.ingress.path }}
    install.server.web.host={{ .Values.global.domain }}
    install.server.web.port={{ .Values.server.service.ports.http }}
    install.server.web.https.port={{ .Values.server.service.ports.https }}
    install.server.jms.port={{ .Values.server.service.ports.agent }}
    install.server.jms.mutualAuth=false
    install.server.web.always.secure=n
    install.server.context.path={{ .Values.ingress.path }}

    install.rcl.server=null

    install.server.keystore.password=changeit
    install.server.keystore.key.password=changeit

    encryption.keystore.alias=aes128keyimkp
    encryption.keystore.password=changeit

    install.server.tomcat.keystore.password=changeit
    install.server.tomcat.key.password=changeit