apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-build-scripts
  labels:
{{ include "ibm-devops-build.labels" . | indent 4 }}
data:
  init-mysql.sh: |
    #!/bin/bash
    set -euo pipefail

    # TODO: Change DB_HOST to dynamically take value using global values.yaml once that is implemented
    {{- if .Values.deploy.enabled }}
    DB_HOST="{{ .Release.Name }}-ibm-ucd-prod-mysql"
    {{- else }}
    DB_HOST="{{ .Values.mysql.service.name }}"
    {{- end }}
    DB_NAME="{{ .Values.mysql.database }}"
    DB_USER="{{ .Values.mysql.user }}"
    DB_PASS=${DEVOPSBUILD_DB_PASS}

    # Wait for MySQL
    for i in {1..30}; do
      if mysql -h "$DB_HOST" -uroot -e "SELECT 1"; then
        break
      fi
      echo "Waiting for MySQL (attempt $i/30)..."
      sleep 2
      [ $i -eq 30 ] && echo "MySQL timeout" && exit 1
    done

    # Execute SQL
    mysql -h "$DB_HOST" -uroot <<EOF
    CREATE DATABASE IF NOT EXISTS \`$DB_NAME\`;
    CREATE USER IF NOT EXISTS '$DB_USER'@'%' IDENTIFIED BY '$DB_PASS';
    GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'%';
    FLUSH PRIVILEGES;
    EOF

  import-certificate.sh: |
    #!/bin/bash
    set -euo pipefail
    
    rm -rf /security-dir/*
    cp -r $JAVA_HOME/jre/lib/security/* /security-dir/
    chmod 644 /security-dir/cacerts
    keytool -import -trustcacerts \
      -keystore /security-dir/cacerts \
      -storepass changeit \
      -alias keycloak2 \
      -file /tls-secret-volume/ca.crt \
      -noprompt

  download-jdbc-connector.sh: |
    #!/bin/bash

    set -euo pipefail
    echo "********* running script to copy JDBC driver files *********"
    VERSION=8.1.0
    CONNECTOR=mysql-connector-j-$VERSION.jar
    DOWNLOAD_URL=https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/$VERSION/$CONNECTOR
    if [ ! -f "/etc/libext/$CONNECTOR" ]; then
        wget -U "My User Agent" -P /etc/libext $DOWNLOAD_URL
    fi

  allow-http-traffic.sh: |
    #!/bin/bash
    set -euo pipefail

    sed -i '/<filter-name>CsrfFilter<\/filter-name>/{n;s|<url-pattern>/tasks/\*</url-pattern>|<url-pattern>/build/*</url-pattern>|}' /opt/devops-build-server/opt/tomcat/webapps/ROOT/WEB-INF/web.xml
    echo "Changed /tasks to /build for CSRF filter"

    sed -i 's/redirectPort="[^"]*"//g' /opt/devops-build-server/opt/tomcat/conf/server.xml
    echo "Removed redirectPort from server.xml"

    sed -i 's/<transport-guarantee>CONFIDENTIAL<\/transport-guarantee>/<transport-guarantee>NONE<\/transport-guarantee>/g' /opt/devops-build-server/opt/tomcat/webapps/ROOT/WEB-INF/web.xml
    echo "Changed transport-guarantee to NONE in web.xml"

  server-start.sh: |
    #!/bin/bash
    set -euo pipefail
    SERVER_HOME={{ .Values.server.home }}

    VERSION=8.1.0
    mkdir -p ${SERVER_HOME}/lib/ext/
    cp /etc/libext/mysql-connector-j-$VERSION.jar ${SERVER_HOME}/lib/ext/mysql-connector-j-$VERSION.jar

    mkdir -p ${SERVER_HOME}/conf/server
    touch ${SERVER_HOME}/conf/server/installed.properties
    echo "installed.properties created at ${SERVER_HOME}/conf/server/installed.properties"
    cat /etc/config/installed.properties > ${SERVER_HOME}/conf/server/installed.properties;
    echo "platform.oidc.clientSecret=${PLATFORM_OIDC_CLIENT_SECRET}" >> ${SERVER_HOME}/conf/server/installed.properties;
    echo "install.server.db.password=${DEVOPSBUILD_DB_PASS}" >> ${SERVER_HOME}/conf/server/installed.properties;

    bash /etc/scripts/allow-http-traffic.sh

    VAR_DIR="/opt/devops-build-server/var"
    #Count entries except lost+found and . and ..
    ENTRY_COUNT=$(find "$VAR_DIR" -mindepth 1 -not -name 'lost+found' | wc -l)
    if [ "$ENTRY_COUNT" -eq 0 ]; then
      VAR_CHECK="$VAR_DIR"
    else
      VAR_CHECK=""
    fi
    if [ -z "$VAR_CHECK" ]; then
      echo "Adding ant-launcher.jar to library path"
      cp "/usr/local/apache-ant/lib/ant-launcher.jar" "/opt/devops-build-server/lib/"
    fi

    cp -r /opt/devops-build-server-plugin-backup/. /opt/devops-build-server/plugin/

    sh devops_build_server_entrypoint.sh