{{- if not .Values.secret.name }}
{{- $previous := lookup "v1" "Secret" .Release.Namespace (tpl "{{ .Release.Name }}-build-secrets" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-build-secrets
  labels:
{{ include "ibm-devops-build.labels" . | indent 4 }}
type: Opaque
data:
  {{- if $previous }}
  initpassword: {{ $previous.data.initpassword }}
  dbpassword: {{ $previous.data.dbpassword }}
  keystorepassword: {{ $previous.data.keystorepassword }}
  {{- else }}
  initpassword: {{ randAlphaNum 16 | b64enc | quote }}
  dbpassword: {{ randAlphaNum 16 | b64enc | quote }}
  keystorepassword: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
{{- end }}