{{- if include "testhub.execution.enabled" . }}
{{- if not .Values.networkPolicy.enabled }}
{{- if .Values.execution.nodePorts.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: execution-intercepts
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-execution-intercepts-{{ .Release.Namespace }}'
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: '{{ .Release.Name }}-execution-intercepts-{{ .Release.Namespace }}'
subjects:
- kind: ServiceAccount
  name: '{{ .Release.Name }}-execution'
  namespace: '{{ .Release.Namespace }}'
{{- end }}
{{- end }}
{{- end }}
