####################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2019. All rights reserved.
#
# * Trademark of HCL Technologies Limited
####################################################################
{{- if .Values.global.sofySolutionContext }}
{{- if .Values.global.domain }}
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: crd-{{ include "ccm.fullname" . }}
spec:
  prefix: /.*
  host: {{ include "ccm.fullname" . }}.{{ .Values.global.domain }}
  ambassador_id: [ '{{ .Values.global.emissaryID }}' ]
  case_sensitive: false
  host_regex: true
  prefix_regex: true
  rewrite: ""
  timeout_ms: 10000
  bypass_auth: {{ .Values.disableAccessControl }}
  service: https://{{ include "ccm.fullname" . }}:8190
  resolver: devopsplanendpoint
  load_balancer:
    policy: ring_hash
    cookie:
      name: {{ include "ccm.fullname" . }}-affinity-cookie
      ttl: 86400s
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: crd-{{ include "ccm.fullname" . }}-dropwww
spec:
  prefix: /.*
  host: www.{{ include "ccm.fullname" . }}.{{ .Values.global.domain }}
  ambassador_id: [ '{{ .Values.global.emissaryID }}' ]
  case_sensitive: false
  host_regex: true
  prefix_regex: true
  rewrite: ""
  bypass_auth: {{ .Values.disableAccessControl }}
  timeout_ms: 10000
  service: {{ include "ccm.fullname" . }}.{{ .Values.global.domain }}
---
{{- if .Values.analytics.service }}
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: crd-{{ include "ccm.fullname" . }}-analytics
spec:
  prefix: /.*
  host: {{ include "ccm.fullname" . }}-analytics.{{ .Values.global.domain }}
  ambassador_id: [ '{{ .Values.global.emissaryID }}' ]
  case_sensitive: false
  host_regex: true
  prefix_regex: true
  rewrite: ""
  timeout_ms: 10000
  bypass_auth: {{ .Values.disableAccessControl }}
  service: https://{{ include "ccm.fullname" . }}-analytics:8290
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: crd-{{ include "ccm.fullname" . }}-analytics-dropwww
spec:
  prefix: /.*
  host: www.{{ include "ccm.fullname" . }}-analytics.{{ .Values.global.domain }}
  ambassador_id: [ '{{ .Values.global.emissaryID }}' ]
  case_sensitive: false
  host_regex: true
  prefix_regex: true
  rewrite: ""
  bypass_auth: {{ .Values.disableAccessControl }}
  timeout_ms: 10000
  service: {{ include "ccm.fullname" . }}-analytics.{{ .Values.global.domain }}
---
{{- end }}
{{- if .Values.nginx.service }}
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: crd-{{ include "ccm.fullname" . }}-nginx
spec:
  prefix: /.*
  host: {{ include "ccm.fullname" . }}-nginx.{{ .Values.global.domain }}
  ambassador_id: [ '{{ .Values.global.emissaryID }}' ]
  case_sensitive: false
  host_regex: true
  prefix_regex: true
  rewrite: ""
  timeout_ms: 10000
  bypass_auth: {{ .Values.disableAccessControl }}
  service: https://{{ include "ccm.fullname" . }}-nginx:5602
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: crd-{{ include "ccm.fullname" . }}-nginx-dropwww
spec:
  prefix: /.*
  host: www.{{ include "ccm.fullname" . }}-nginx.{{ .Values.global.domain }}
  ambassador_id: [ '{{ .Values.global.emissaryID }}' ]
  case_sensitive: false
  host_regex: true
  prefix_regex: true
  rewrite: ""
  bypass_auth: {{ .Values.disableAccessControl }}
  timeout_ms: 10000
  service: {{ include "ccm.fullname" . }}-nginx.{{ .Values.global.domain }}
---
{{- end }}
{{- if .Values.keycloak.service }}
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: crd-{{ include "ccm.fullname" . }}-keycloak
spec:
  prefix: /.*
  host: {{ include "ccm.fullname" . }}-keycloak.{{ .Values.global.domain }}
  ambassador_id: [ '{{ .Values.global.emissaryID }}' ]
  case_sensitive: false
  host_regex: true
  prefix_regex: true
  rewrite: ""
  timeout_ms: 10000
  bypass_auth: {{ .Values.disableAccessControl }}
  service: https://{{ include "ccm.fullname" . }}-keycloak:8443
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: crd-{{ include "ccm.fullname" . }}-keycloak-dropwww
spec:
  prefix: /.*
  host: www.{{ include "ccm.fullname" . }}-keycloak.{{ .Values.global.domain }}
  ambassador_id: [ '{{ .Values.global.emissaryID }}' ]
  case_sensitive: false
  host_regex: true
  prefix_regex: true
  rewrite: ""
  bypass_auth: {{ .Values.disableAccessControl }}
  timeout_ms: 10000
  service: {{ include "ccm.fullname" . }}-keycloak.{{ .Values.global.domain }}
---
{{- end }}
{{- if .Values.postgresql.enabled }}
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: crd-{{ include "ccm.fullname" . }}-postgresql
spec:
  prefix: /.*
  host: {{ include "ccm.fullname" . }}-postgresql.{{ .Values.global.domain }}
  ambassador_id: [ '{{ .Values.global.emissaryID }}' ]
  case_sensitive: false
  host_regex: true
  prefix_regex: true
  rewrite: ""
  timeout_ms: 10000
  bypass_auth: {{ .Values.disableAccessControl }}
  service: https://{{ include "ccm.fullname" . }}-postgresql:5432
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: crd-{{ include "ccm.fullname" . }}-postgresql-dropwww
spec:
  prefix: /.*
  host: www.{{ include "ccm.fullname" . }}-postgresql.{{ .Values.global.domain }}
  ambassador_id: [ '{{ .Values.global.emissaryID }}' ]
  case_sensitive: false
  host_regex: true
  prefix_regex: true
  rewrite: ""
  bypass_auth: {{ .Values.disableAccessControl }}
  timeout_ms: 10000
  service: {{ include "ccm.fullname" . }}-postgresql.{{ .Values.global.domain }}
---
{{- end }}
{{- else}}
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: crd-{{ include "ccm.fullname" . }}
spec:
  prefix: /.*
  host: {{ include "ccm.fullname" . }}\..*
  ambassador_id: [ '{{ .Values.global.emissaryID }}' ]
  case_sensitive: false
  host_regex: true
  prefix_regex: true
  rewrite: ""
  timeout_ms: 10000
  service: https://{{ include "ccm.fullname" . }}:8190
  resolver: devopsplanendpoint
  bypass_auth: {{ .Values.disableAccessControl }}
  load_balancer:
    policy: ring_hash
    cookie:
      name: {{ include "ccm.fullname" . }}-affinity-cookie
      ttl: 86400s
{{- if .Values.analytics.service }}
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: crd-{{ include "ccm.fullname" . }}-analytics
spec:
  prefix: /.*
  host: {{ include "ccm.fullname" . }}-analytics\..*
  ambassador_id: [ '{{ .Values.global.emissaryID }}' ]
  case_sensitive: false
  host_regex: true
  prefix_regex: true
  rewrite: ""
  timeout_ms: 10000
  service: https://{{ include "ccm.fullname" . }}-analytics:8290
  resolver: devopsplanendpoint
  bypass_auth: {{ .Values.disableAccessControl }}
{{- end }}
{{- if .Values.nginx.service }}
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: crd-{{ include "ccm.fullname" . }}-nginx
spec:
  prefix: /.*
  host: {{ include "ccm.fullname" . }}-nginx\..*
  ambassador_id: [ '{{ .Values.global.emissaryID }}' ]
  case_sensitive: false
  host_regex: true
  prefix_regex: true
  rewrite: ""
  timeout_ms: 10000
  service: https://{{ include "ccm.fullname" . }}-nginx:5602
  resolver: devopsplanendpoint
  bypass_auth: {{ .Values.disableAccessControl }}
{{- end }}
{{- if .Values.keycloak.service }}
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: crd-{{ include "ccm.fullname" . }}-keycloak
spec:
  prefix: /.*
  host: {{ include "ccm.fullname" . }}-keycloak\..*
  ambassador_id: [ '{{ .Values.global.emissaryID }}' ]
  case_sensitive: false
  host_regex: true
  prefix_regex: true
  rewrite: ""
  timeout_ms: 10000
  service: https://{{ include "ccm.fullname" . }}-keycloak:8443
  resolver: devopsplanendpoint
  bypass_auth: {{ .Values.disableAccessControl }}
{{- end }}
{{- if .Values.postgresql.enabled }}
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: crd-{{ include "ccm.fullname" . }}-postgresql
spec:
  prefix: /.*
  host: {{ include "ccm.fullname" . }}-postgresql\..*
  ambassador_id: [ '{{ .Values.global.emissaryID }}' ]
  case_sensitive: false
  host_regex: true
  prefix_regex: true
  rewrite: ""
  timeout_ms: 10000
  service: https://{{ include "ccm.fullname" . }}-postgresql:5432
  resolver: devopsplanendpoint
  bypass_auth: {{ .Values.disableAccessControl }}
{{- end }}
{{- end }}
---
apiVersion: getambassador.io/v3alpha1
kind: KubernetesEndpointResolver
metadata:
  name: devopsplanendpoint
spec:
  ambassador_id: [ '{{ .Values.global.emissaryID }}' ]  
---
{{- end }}
