{{- if or .Values.global.sofySolutionContext (and .Values.ingress.enabled (eq .Values.ingress.type "mapping")) }}
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: {{ include "ccm.fullname" . }}
spec:
{{- if .Values.global.ambassadorID }}
  ambassador_id: [ '{{ .Values.global.emissaryID }}' ]
{{- end }}
  bypass_auth: {{ .Values.disableAccessControl }}
  case_sensitive: false
  host_regex: true
{{- if .Values.global.platform.enabled }}
  host: {{ .Values.global.domain }}
  prefix: '{{ .Values.ingress.path }}.*'
  service: http://{{ include "ccm.fullname" . }}:8191
{{- else }}
  host: {{ include "ccm.fullname" . }}{{ .Values.ingress.suffix }}.{{ default ".*" .Values.global.domain }}
  prefix: /.*
  service: https://{{ include "ccm.fullname" . }}:8190
{{- end }}
  resolver: {{ include "ccm.fullname" . }}
  load_balancer:
    policy: ring_hash
    cookie:
      name: {{ include "ccm.fullname" . }}-affinity-cookie
{{- if .Values.global.platform.enabled }}
      path: /plan
{{- end }}
      ttl: 86400s
  prefix_regex: true
  rewrite: ""
  timeout_ms: {{ .Values.ccm.ingressMapping.timeout_ms }}
  connect_timeout_ms: {{ .Values.ccm.ingressMapping.connect_timeout_ms }}
{{- end }}
