{{- if .Values.devopsplan.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ccm.fullname" . }}
  labels:
    {{- include "ccm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: ClientIP
  ports:
{{- if .Values.global.platform.enabled }}
    - name: http
      port: 8191
      targetPort: {{ .Values.service.targetPortPlatform }}
{{- end }}
    - name: https
      port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.targetPort }}
    {{- if .Values.service.exposePort }}
      nodePort: {{ .Values.service.exposePort }}
    {{- end }}
      protocol: TCP

  selector:
    app.kubernetes.io/name: {{ include "ccm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
