{{- if .Values.devopsplan.service }}
{{- if .Values.persistence.enabled -}}
{{- if .Values.persistence.ccm.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ccm.fullname" . }}-configmap
  labels:
    {{- include "ccm.labels" . | nindent 4 }}
data:
  data-config-properties.sh: |-
    #!/bin/bash
    CCM_PATH="/opt/devops/plan"
    REST_SERVER_API_PATH="$CCM_PATH/devopsplan-rest-server-distribution"
    DATA_PATH="$REST_SERVER_API_PATH/data"
    CONFIG_PATH="$REST_SERVER_API_PATH/config"
    SHARE_PATH="$REST_SERVER_API_PATH/share"
    CONFIG_TMP_PATH="/opt/tmp/config"
    DATA_TMP_PATH="/opt/tmp/data"
    SHARE_TMP_PATH="/opt/tmp/share"
    count=0
    DATA_COMPLETED=0
    CONFIG_COMPLETED=0
    SHARE_COMPLETED=0
    sleep 5
    while [ $count -le 5 ]
    do
      echo "oraignal folders"
      ls -l $DATA_PATH
      ls -l $CONFIG_PATH
      ls -l $SHARE_PATH
      echo "TMP Folders"
      ls -l $DATA_TMP_PATH
      ls -l $CONFIG_TMP_PATH
      ls -l $SHARE_TMP_PATH
      if [[ -d "$DATA_PATH" ]] && [[ -n "$(ls -A "$DATA_PATH")" ]]; then
        if [[ -d "$DATA_TMP_PATH" ]] && [[ -z "$(ls -A "$DATA_TMP_PATH")" ]]; then
          echo "Copy $DATA_PATH to $DATA_TMP_PATH"
          cp -r $DATA_PATH/* $DATA_TMP_PATH/.
          ls -l $DATA_TMP_PATH
          DATA_COMPLETED=1
        fi
      fi
      if [[ -d "$CONFIG_PATH" ]] && [[ -n "$(ls -A "$CONFIG_PATH")" ]]; then
        if [[ -d "$CONFIG_TMP_PATH" ]] && [[ -z "$(ls -A "$CONFIG_TMP_PATH")" ]]; then
          echo "Copy $CONFIG_PATH to $CONFIG_TMP_PATH"
          cp -r $CONFIG_PATH/* $CONFIG_TMP_PATH/.
          ls -l $CONFIG_TMP_PATH
          CONFIG_COMPLETED=1
        fi
      fi
      if [[ -d "$SHARE_PATH" ]] && [[ -n "$(ls -A "$SHARE_PATH")" ]]; then
        if [[ -d "$SHARE_TMP_PATH" ]] && [[ -z "$(ls -A "$SHARE_TMP_PATH")" ]]; then
          echo "Copy $SHARE_PATH to $SHARE_TMP_PATH"
          cp -r $SHARE_PATH/* $SHARE_TMP_PATH/.
          ls -l $SHARE_TMP_PATH
          SHARE_COMPLETED=1
        fi
      fi
      if [[ $DATA_COMPLETED -le 1 ]] && [[  $CONFIG_COMPLETED -le 1 ]] && [[  $SHARE_COMPLETED -le 1 ]]; then
         break
      fi
      sleep 5
      count=$(( count+1 ))
    done
{{- end -}}
{{- end -}}
{{- end -}}
