{{- if or (eq .Values.persistence.properties.application.enabled true) (eq .Values.persistence.properties.analytics.enabled true) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ccm.fullname" . }}-application-configmap
  labels:
    {{- include "ccm.labels" . | nindent 4 }}
data:
{{ if .Values.persistence.properties.application.enabled }}
{{ (.Files.Glob "config/application.properties").AsConfig | indent 2 }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ccm.fullname" . }}-analytics-configmap
  labels:
    {{- include "ccm.labels" . | nindent 4 }}
data:
{{ if .Values.persistence.properties.analytics.enabled }}
{{ (.Files.Glob "config/analytics.properties").AsConfig | indent 2 }}
{{- end }}
{{- end }}

