{{- if not .Values.backupRestore.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ccm.fullname" . }}-db-secret
  labels:
    {{- include "ccm.labels" . | nindent 4 }}
type: Opaque
data:
{{- if or (.Values.spring.mail.password) (.Values.global.platform.smtp.password) }}
{{- if .Values.global.platform.smtp.password }}
  spring-mail-password: {{ default "" .Values.global.platform.smtp.password | b64enc | quote }}
{{- else if .Values.spring.mail.password }}
  spring-mail-password: {{ default "" .Values.spring.mail.password | b64enc | quote }}
{{- end }}
{{- end }}
{{ if .Values.db.service }}
  db-connection-set: {{ default "" .Values.db.connectionSet | b64enc | quote }}
{{- end }}
{{ if .Values.sso.enabled }}
  sso-config-set: {{ default "" .Values.sso.configSet | b64enc | quote }}
{{- end }}
{{ if .Values.ssl.enabled }}
  ssl-password: {{ default "" .Values.ssl.password | b64enc | quote }}
{{- end }}
{{ if .Values.keycloak.enabled }}
  dashboardsClient-secret: {{ default "" .Values.keycloak.dashboardsClientSecret | b64enc | quote }}
{{- end }}
{{ if .Values.logstash.service }}
  logstash-password: {{ default "" .Values.logstash.password | b64enc | quote }}
{{- end }}
{{- end }}
