{{- if or .Values.global.sofySolutionContext (and .Values.ingress.enabled (eq .Values.ingress.type "mapping")) }}
apiVersion: getambassador.io/v3alpha1
kind: KubernetesEndpointResolver
metadata:
  name: {{ include "ccm.fullname" . }}
{{- if .Values.global.ambassadorID }}
spec:
  ambassador_id: [ '{{ .Values.global.emissaryID }}' ]
{{- end }}
{{- end }}
