{{- if not .Values.global.platform.enabled }}
{{- if (eq .Values.ingress.type "mapping") }}
#HCL-ONLY-BEGIN
{{- if not .Values.global.sofySolutionContext }}
#HCL-ONLY-END
{{- if .Values.ingress.host.enabled }}
apiVersion: getambassador.io/v2
kind: Host
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Release.Name }}-wildcard'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-wildcard'
spec:
{{- if .Values.global.ambassadorID }}
  ambassador_id: [ '{{ .Values.global.ambassadorID }}' ]
{{- end }}
  hostname: '*'
  tlsSecret:
    name: '{{ .Values.global.certSecretName }}'
  tls:
    min_tls_version: v1.2
    cipher_suites:
      - '[ECDHE-ECDSA-AES128-GCM-SHA256|ECDHE-ECDSA-CHACHA20-POLY1305]'
      - '[ECDHE-RSA-AES128-GCM-SHA256|ECDHE-RSA-CHACHA20-POLY1305]'
      - ECDHE-ECDSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-GCM-SHA384
  requestPolicy:
    insecure:
      action: Redirect
{{- end }}
#HCL-ONLY-BEGIN
{{- end }}
#HCL-ONLY-END
{{- end }}
{{- end }}
