{{- if not .Values.global.platform.enabled }}
{{- if (eq .Values.ingress.type "mapping") }}
#HCL-ONLY-BEGIN
{{- if not .Values.global.sofySolutionContext }}
#HCL-ONLY-END
{{- if .Values.ingress.host.enabled }}
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Release.Name }}-https'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-https'
spec:
{{- if .Values.global.ambassadorID }}
  ambassador_id: [ '{{ .Values.global.ambassadorID }}' ]
{{- end }}
  port: {{ .Values.ingress.listenerPort }}
  protocol: HTTPS
  securityModel: XFP
  hostBinding:
    namespace:
      from: SELF
{{- end }}
#HCL-ONLY-BEGIN
{{- end }}
#HCL-ONLY-END
{{- end }}
{{- end }}

