{{- if .Values.devopsplan.service }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "ccm.fullname" . }}-networkpolicy
  labels:
    {{- include "ccm.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      devopsplancomp: {{ include "ccm.fullname" . }}-ccm
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.service.targetPortPlatform }}
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
  policyTypes:
  - Ingress
{{- end -}}
