{{- if .Values.devopsplan.service }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ccm.fullname" . }}-sa
  labels:
    {{- include "ccm.labels" . | nindent 4 }}
{{- if or (.Values.global.imagePullSecret) (.Values.global.imagePullSecrets) }}
imagePullSecrets:
  - name: ibm-entitlement-key
  - name: sa-{{ .Release.Namespace }}
{{- if .Values.global.imagePullSecret }}
  - name: {{ .Values.global.imagePullSecret }}
{{- end }}
{{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
{{- end }}
