{{- if (.Capabilities.APIVersions.Has "getambassador.io/v2") }}
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  labels:
    {{- include "devops-platform.labels" (dict "componentName" "velocity-mapping" "context" .) | nindent 4 }}
  name: {{ include "devops-platform.componentFullname" (dict "componentName" "velocity" "context" .) }}
spec:
{{- if .Values.global.ambassadorID }}
  ambassador_id: [ '{{ .Values.global.ambassadorID }}' ]
{{- end }}
  bypass_auth: true
  host: {{ .Values.global.domain }}
  prefix: {{ index .Values "ibm-ucv-prod" "ingress" "path" }}
  rewrite: '/'
  service: {{- if eq (include "devops-platform.brand" .) "IBM" }}
    http://velocity-router:8080
  {{- else }}
    http://accelerate-router:8080
  {{- end }}
  timeout_ms: 10000
  use_websocket: true
{{- end }}
