{{- if include "testhub.datasets.enabled" . }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: datasets
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: datasets
spec:
  ports:
  - name: http
    port: 8093
    targetPort: http
  selector:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/name: datasets
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
{{- end }}
