apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: control
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ tpl (index .Values "ibm-devopsplan-prod" "control" "platform" "oidc" "clientSecret") . }}'
type: Opaque
data:
{{- if (index .Values "ibm-devopsplan-prod" "control" "existingOauthClientSecret") }}
  oauth-client-secret: {{ index .Values "ibm-devopsplan-prod" "control" "existingOauthClientSecret" | b64enc | quote }}
{{- else }}
  oauth-client-secret: {{ print (default .Release.Name .Values.global.passwordSeed) "control-oauth-client-secret" | sha256sum | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: control
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ tpl (index .Values "ibm-devops-prod" "postgresql" "dbs" "control" "secret") . }}'
type: Opaque
data:
{{ include "devops-platform.postgresql-password-b64" (dict "context" . "existingPwd" (index .Values "ibm-devopsplan-prod" "control" "existingPostgresqlPassword") "passwordSeed" .Values.global.passwordSeed "componentName" "control") }}
