apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: core
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-core'
type: Opaque
data:
{{- if include "testhub.core.enabled" . }}
{{- if .Values.core.existingOauthClientSecret }}
  oauth-client-secret: {{ .Values.core.existingOauthClientSecret | b64enc | quote }}
{{- else }}
  oauth-client-secret: {{ print (default .Release.Name (default .Values.global.passwordSeed .Values.passwordSeed)) "gateway-oauth-client-secret" | sha256sum | b64enc | quote }}
{{- end }}
{{- end }}
{{- if .Values.core.existingPostgresqlPassword }}
  postgresql-password: {{ .Values.core.existingPostgresqlPassword | b64enc | quote }}
{{- else }}
  postgresql-password: {{ print (default .Release.Name (default .Values.global.passwordSeed .Values.passwordSeed)) "gateway-postgresql" | sha256sum | b64enc | quote }}
{{- end }}
{{- if include "testhub.core.enabled" . }}
{{- if .Values.core.existingSecretsStorageKey }}
  secrets-storage-key: {{ .Values.core.existingSecretsStorageKey | b64enc | quote }}
{{- else }}
  secrets-storage-key: {{ print (default .Release.Name (default .Values.global.passwordSeed .Values.passwordSeed)) "secrets-master-password" | sha256sum | b64enc | quote }}
{{- end }}
{{- end }}
