{{- if not .Values.global.platform.enabled }}
{{- if (and (or (eq .Values.ingress.type "mapping") (eq .Values.ingress.type "route")) (eq .Values.control.enabled true)) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: control
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: {{ .Release.Name }}-control-postgres-password
type: Opaque
data:
{{- if and  .Values.control.postgresql.password }}
  postgresql-password: {{ default "" .Values.control.postgresql.password | b64enc | quote }}
{{- else }}
{{- if .Values.control.postgresql.existingPassword }}
  postgresql-password: {{ .Values.control.postgresql.existingPassword | b64enc | quote }}
{{- else }}
  postgresql-password: {{ print (default .Release.Name .Values.global.passwordSeed) "control" "postgresql" | sha256sum | b64enc | quote }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-control-ini-secrets
type: Opaque
stringData:
  database: |
{{- if .Values.control.postgresql.username }}
    USER={{ .Values.control.postgresql.username }}
{{- else }}
    USER=control
{{- end }}
{{- if and  .Values.control.postgresql.password }}
    PASSWD={{ default "" .Values.control.postgresql.password }}
{{- else }}
{{- if .Values.control.postgresql.existingPassword }}
    PASSWD={{ .Values.control.postgresql.existingPassword }}
{{- else }}
    PASSWD={{ print (default .Release.Name .Values.global.passwordSeed) "control" "postgresql" | sha256sum }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
