{{- if not .Values.global.platform.enabled }}
{{- if (eq .Values.ingress.type "mapping") }}
{{- if not .Values.global.sofySolutionContext }}
apiVersion: getambassador.io/v2
kind: Host
metadata:
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
  name: {{ template "ollama.fullname" . }}
  namespace: {{ include "ollama.namespace" . }}
spec:
  hostname: '*'
  acmeProvider:
    authority: none
  tlsSecret:
    name: '{{ .Values.global.certSecretName }}'
  requestPolicy:
    insecure:
      action: Redirect
{{- end }}
{{- end }}
{{- end }}
