apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: velocity-database
  namespace: {{ NAMESPACE }}
  labels:
    app: velocity
    app.kubernetes.io/instance: velocity
    app.kubernetes.io/managed-by: User
    app.kubernetes.io/name: velocity
stringData:
  password: mongodb://user:password@mongo-host:27017