{{- if .Values.opensearch.service -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ccm.fullname" . }}-opensearch
  labels:
    {{- include "ccm.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "ccm.fullname" . }}-opensearch
  replicas: {{ .Values.opensearch.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ccm.name" . }}-opensearch
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ccm.name" . }}-opensearch
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      annotations:
  {{- if eq "IBM" .Values.global.devopsPlanBrand }}
        productName: {{ .Values.annotations.ibm.productName }}
        productID: {{ .Values.annotations.ibm.productID }}
        productVersion: {{ .Values.annotations.ibm.productVersion }}
        productMetric: {{ .Values.annotations.ibm.productMetric }}
        productChargedContainers: {{ .Values.annotations.ibm.productChargedContainers }}
  {{ else }}
        productName: {{ .Values.annotations.hcl.productName }}
        productVersion: {{ .Values.annotations.hcl.productVersion }}
  {{- end }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.opensearch.nodeAffinity.key }}
                operator: In
                values:
                - {{ .Values.opensearch.nodeAffinity.values }}
  {{- if .Values.opensearch.topologySpreadConstraints.enabled }}
      topologySpreadConstraints:
        - maxSkew: {{ .Values.opensearch.topologySpreadConstraints.maxSkew }}
          topologyKey: {{ .Values.opensearch.topologySpreadConstraints.topologyKey }}
          whenUnsatisfiable: {{ .Values.opensearch.topologySpreadConstraints.whenUnsatisfiable }}
          labelSelector:
            matchLabelKeys:
              app.kubernetes.io/name: {{ include "ccm.name" . }}-opensearch
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- end }}
  {{- if or (.Values.global.imagePullSecret) (.Values.global.imagePullSecrets) }}
      imagePullSecrets:
  {{- if .Values.global.imagePullSecret }}
      - name: {{ .Values.global.imagePullSecret }}
  {{- end }}
      {{- range .Values.global.imagePullSecrets }}
      - name: {{ . }}
      {{- end }}
  {{- end }}
      securityContext:
        runAsNonRoot: true
  {{- if not (.Capabilities.APIVersions.Has "security.openshift.io/v1") }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
  {{- end }}
      volumes:
      {{ if .Values.persistence.enabled }}
      {{- if .Values.persistence.opensearch.enabled }}
        - name: configmap-data
          configMap:
            name: ccm-ek-configmap
            defaultMode: 0700
            name: {{ include "ccm.fullname" . }}-opensearch-configmap
      {{- end }}
      {{- end }}
      {{- if .Values.opensearch.hash }}
        - name: opensearch-users
          configMap:
            name: {{ include "ccm.fullname" . }}-opensearch-users-configmap
      {{- end }}
      {{- if .Values.global.platform.enabled }}
        - name: opensearch-config-temp
          configMap:
            name: {{ include "ccm.fullname" . }}-opensearch-configmap
        - name: opensearch-config
          emptyDir: {}
        - name: opensearch-roles-mapping
          configMap:
            name: {{ include "ccm.fullname" . }}-opensearch-roles-mapping-configmap
        - name: opensearch-roles
          configMap:
            name: {{ include "ccm.fullname" . }}-opensearch-roles-configmap
      {{- if eq (include "mychart.caCertExists" .) "true" }}
        - name: tls-secrets
          secret:
      {{- if eq "IBM" .Values.global.devopsPlanBrand }}
            secretName: {{ .Values.global.ibmCertSecretName }}
      {{- else }}
            secretName: {{ .Values.global.hclCertSecretName }}
      {{- end }}
            items:
              - key: ca.crt
                path: devops_loop.pem
        - name: opensearch-ca
          emptyDir: {}
      {{- end }}
      {{- end }}
      initContainers:
      {{- if .Values.keycloak.enabled }}
      {{- if or ( and (eq .Values.keycloak.service.enabled true) (eq .Values.keycloaksrv.enabled true)) (eq .Values.global.platform.enabled true) }}
        - name: init-keycloak
      {{- if .Values.global.platform.enabled }}
          image: "curlimages/curl:7.76.1"
          imagePullPolicy: IfNotPresent
          env:
          - name: KEYCLOAK_URL
            value: "https://{{ .Values.global.domain }}/auth/realms/{{ .Values.keycloak.realmName }}"
          command: ["sh", "-c", "while [[ $(curl -s -k -o /dev/null -w '%{http_code}' $KEYCLOAK_URL) != 200 ]]; do sleep 1; echo $(date +'%Y-%m-%d_%H%M%S'): Keycloak $(KEYCLOAK_URL) is not ready; done"]
      {{- else }}
          image: "curlimages/curl:7.76.1"
          imagePullPolicy: IfNotPresent
          env:
          - name: KEYCLOAK_URL
            value: "https://{{ .Release.Name }}-keycloaksrv/realms/master"
          command: ["sh", "-c", "while [[ $(curl -s -k -o /dev/null -w '%{http_code}' $KEYCLOAK_URL) != 200 ]]; do sleep 1; echo $(date +'%Y-%m-%d_%H%M%S'): Keycloak $(KEYCLOAK_URL) is not ready; done"]
      {{- end }}
      {{- if .Values.ccm.initResources }}
          resources: {{- toYaml .Values.ccm.initResources | nindent 12 }}
      {{- end }}
          securityContext:
            runAsNonRoot: true
      {{- if not (.Capabilities.APIVersions.Has "security.openshift.io/v1") }}
            runAsUser: {{ .Values.securityContext.runAsUser }}
##            fsGroup: {{ .Values.securityContext.fsGroup }}
      {{- end }}
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
      {{- end }}
      {{- end }}
      {{- if .Values.global.platform.enabled }}
        - name: init-opensearch
      {{- if .Values.image.repoDigests }}
          image: "{{ include "ccm.ccmImageRepo" . }}/{{ .Values.opensearch.image.repository }}@{{ .Values.opensearch.image.tag }}"
      {{- else }}
          image: "{{ include "ccm.ccmImageRepo" . }}/{{ .Values.opensearch.image.repository }}:{{ .Values.opensearch.image.tag }}"
      {{- end }}
          imagePullPolicy: {{ .Values.opensearch.image.pullPolicy }}
          command:
            - /bin/sh
            - '-c'
            - |
                cp /tmp/config/config.yml /usr/share/opensearch/config/opensearch-security/config.yml
                /usr/share/opensearch/config.sh
      {{- if eq (include "mychart.caCertExists" .) "true" }}
                cp /usr/share/opensearch/jdk/lib/security/cacerts /tmp/ca/cacerts
                /usr/share/opensearch/jdk/bin/keytool -importcert -noprompt \
                  -alias loop-ca-alias \
                  -file /usr/share/opensearch/config/devops_loop.pem \
                  -keystore /tmp/ca/cacerts \
                  -storepass changeit
      {{- end }}
          env:
            - name: OAUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "ccm.fullname" . }}-opensearch
                  key: oauth-client-secret
          volumeMounts:
          - name: opensearch-config-temp
            mountPath: /tmp/config
            readOnly: false
          - name: opensearch-config
            mountPath: /usr/share/opensearch/config/opensearch-security
            readOnly: false
      {{- if eq (include "mychart.caCertExists" .) "true" }}
          - name: tls-secrets
            mountPath: /usr/share/opensearch/config/devops_loop.pem
            subPath: devops_loop.pem
          - name: opensearch-ca
            mountPath: /tmp/ca
            readOnly: false
      {{- end }}
          securityContext:
            runAsNonRoot: true
        {{- if not (.Capabilities.APIVersions.Has "security.openshift.io/v1") }}
            runAsUser: {{ .Values.securityContext.runAsUser }}
        {{- end }}
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
      {{- end }}
      {{ if .Values.persistence.enabled }}
      {{- if .Values.persistence.opensearch.enabled }}
        - name: prepare-volume
          image: busybox:1.28
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
      {{- if .Values.ccm.initResources }}
          resources: {{- toYaml .Values.ccm.initResources | nindent 12 }}
      {{- end }}
          volumeMounts:
            - name: data
              mountPath: /usr/share/opensearch/data
      {{- end }}
      {{- end }}
      hostname:  "{{ .Values.opensearch.hostname }}"
      serviceAccount: {{ include "ccm.fullname" . }}-sa
      containers:
      - name: {{ .Chart.Name }}-opensearch
      {{- if .Values.image.repoDigests }}
        image: "{{ include "ccm.ccmImageRepo" . }}/{{ .Values.opensearch.image.repository }}@{{ .Values.opensearch.image.tag }}"
      {{- else }}
        image: "{{ include "ccm.ccmImageRepo" . }}/{{ .Values.opensearch.image.repository }}:{{ .Values.opensearch.image.tag }}"
      {{- end }}
        imagePullPolicy: {{ .Values.opensearch.image.pullPolicy }}
      {{- if .Values.probes.readiness.opensearch }}
        readinessProbe:
{{ toYaml .Values.probes.readiness.opensearch | indent 10 }}
      {{- end }}
      {{- if .Values.probes.liveness.opensearch }}
        livenessProbe:
{{ toYaml .Values.probes.liveness.opensearch | indent 10 }}
      {{- end }}
      {{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.Version }}
        startupProbe:
{{ toYaml .Values.probes.startup.opensearch | indent 10 }}
      {{- end }}
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        ports:
          - name: performance
            containerPort: 9600
            protocol: TCP
          - name: http
            containerPort: 9200
            protocol: TCP
        env:
     {{- if and (.Values.global.platform.enabled) (.Values.ingress.cert.selfSigned) }}
          - name: OAUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ include "ccm.fullname" . }}-opensearch
                key: oauth-client-secret
     {{- end }}
          - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "ccm.fullname" . }}-opensearch
                key: opensearch-password
          - name: discovery.type
            value: "single-node"
        volumeMounts:
     {{- if .Values.persistence.enabled }}
     {{- if .Values.persistence.opensearch.enabled }}
          - name: data
            mountPath: /usr/share/opensearch/data
     {{- end }}
     {{- end }}
     {{- if .Values.opensearch.hash }}
          - name: opensearch-users
            mountPath: /usr/share/opensearch/config/opensearch-security/internal_users.yml
            subPath: internal_users.yml
     {{- end }}
     {{- if .Values.global.platform.enabled }}
          - name: opensearch-config
            mountPath: /usr/share/opensearch/config/opensearch-security/config.yml
            subPath: config.yml
          - name: opensearch-roles-mapping
            mountPath: /usr/share/opensearch/config/opensearch-security/roles_mapping.yml
            subPath: roles_mapping.yml
          - name: opensearch-roles
            mountPath: /usr/share/opensearch/config/opensearch-security/roles.yml
            subPath: roles.yml
     {{- if eq (include "mychart.caCertExists" .) "true" }}
          - name: opensearch-ca
            mountPath: /usr/share/opensearch/jdk/lib/security/cacerts
            subPath: cacerts
     {{- end }}
     {{- end }}
        resources:
          {{- toYaml .Values.opensearch.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- if .Values.persistence.enabled }}
{{- if .Values.persistence.opensearch.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app.kubernetes.io/name: {{ include "ccm.name" . }}-opensearch
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.persistence.annotations  }}
      annotations:
{{ toYaml . | indent 8 }}
    {{- end }}
    spec:
      accessModes:
      {{ toYaml .Values.persistence.opensearch.accessModes | indent 4 }}
{{- if .Values.persistence.opensearch.storageClass }}
      storageClassName: '{{ .Values.persistence.opensearch.storageClass }}'
{{- else if .Values.persistence.storageClass }}
      storageClassName: '{{ .Values.persistence.storageClass }}'
{{- else if .Values.global.persistence.rwoStorageClass }}
      storageClassName: {{ .Values.global.persistence.rwoStorageClass | quote }}
{{- else if .Values.global.persistence.rwxStorageClass }}
      storageClassName: {{ .Values.global.persistence.rwxStorageClass | quote }}
{{- end }}
      resources:
        requests:
          storage: "{{ .Values.persistence.opensearch.size }}"
{{- end }}
{{- end }}
{{- end -}}
