{{- if .Values.opensearch.service -}}
{{- if .Values.global.platform.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ccm.fullname" . }}-opensearch-roles-mapping-configmap
  labels:
    {{- include "ccm.labels" . | nindent 4 }}
data:
  roles_mapping.yml: |-
    _meta:
      type: "rolesmapping"
      config_version: 2

    # Define your roles mapping here

    ## Demo roles mapping

    all_access:
      reserved: false
      backend_roles:
      - "ROLE_ADMIN"
      - "admin"
      description: "Maps admin to all_access"

    opensearch_dashboards_user:
      reserved: false
      backend_roles:
      - "ROLE_USER"
      description: "Provides access to all tenants"

    readall:
      reserved: false
      backend_roles:
      - "readall"
      description: "Maps view access"

    own_index:
      reserved: false
      users:
      - "*"
      description: "Allow full access to an index named like the username"

    logstash:
      reserved: false
      backend_roles:
      - "logstash"

    kibana_user:
      reserved: false
      backend_roles:
      - "kibanauser"
      description: "Maps kibanauser to kibana_user"

    manage_snapshots:
      reserved: false
      backend_roles:
      - "snapshotrestore"

    kibana_server:
      reserved: true
      users:
      - "kibanaserver"
{{- end }}
{{- end -}}
