{{- if .Values.opensearch.service -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Release.Name }}-opensearch'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: {{ include "ccm.fullname" . }}-opensearch
type: Opaque
data:
{{- if .Values.global.platform.enabled }}
  oauth-client-secret: {{ print (default .Release.Name .Values.global.passwordSeed) "opensearch-oauth-client-secret" | sha256sum | b64enc | quote }}
{{- end }}
{{- if .Values.opensearch.password }}
  opensearch-password: {{ .Values.opensearch.password | b64enc | quote }}
{{- else }}
  opensearch-password: {{ print (default .Release.Name .Values.global.passwordSeed) "opensearch" | sha256sum | b64enc | quote }}
{{- end }}
{{- end -}}
