#
# Licensed Materials - Property of HCL
# (C) Copyright HCL Technologies Ltd. 2024, 2025.  All Rights Reserved.
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule Contract
#
global:
  cmdKubectl: oc
ingress:
  type: route

networkPolicy:
  enabled: true

containerSecurityContext:
  capabilities:
    # un-do default SYS_CHROOT which OpenShift blocks.  may break SSH. Or
    # it may not.
    add: []
  seccompProfile:
    type: RuntimeDefault
  # "null" is specially processed so we skip adding it, and let
  # OpenShift use its own values
  runAsUser: "null"
  runAsGroup: "null"
podSecurityContext:
  fsGroup: "null"

execution:
  ingress:
    hostPattern: '{{ regexReplaceAll "^([^.]*)" .Values.global.domain "$1-*" }}'

serviceAccount:
  create: true
service:
  ssh:
    # Can't use default LoadBalancer port 9022, it's not in the NodePort
    # allowed range.  By using NodePort, we'll get a failure to deploy to
    # OpenShift if the port is in use...in which case, supply these
    # values separately to the helm command line.
    nodePort: 30322
    type: NodePort
gitea:
  config:
    server:
      SSH_PORT: 30322
