#
# Licensed Materials - Property of HCL
# (C) Copyright HCL Technologies Ltd. 2024, 2025.  All Rights Reserved.
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule Contract
#

## @param initContainers.resources.limits initContainers.limits Kubernetes resource limits for init containers
## @param initContainers.resources.requests.cpu initContainers.requests.cpu Kubernetes cpu resource limits for init containers
## @param initContainers.resources.requests.memory initContainers.requests.memory Kubernetes memory resource limits for init containers
initContainers:
  resources:
    limits: {}
    requests:
      cpu: 100m
      memory: 128Mi

## @section deployment
#
## @param resources Kubernetes resources
resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   {}
  # requests:
  #   cpu: 25m
  #   memory: 128Mi
  #   ephemeral-storage: 64Mi

## @section Persistence
#
## @param persistence.accessModes AccessMode for persistence
persistence:
  accessModes:
    - ReadWriteMany
  storageClass: longhorn

## @param replicaCount number of replicas for the deployment
replicaCount: 3

ingress:
  type: mapping
  cert:
    selfSigned: true
  host:
    enabled: false

networkPolicy:
  enabled: true
  ingress:
    namespaceLabel: kubernetes.io/metadata.name
    namespaceValue: emissary

execution:
  ingress:
    hostPattern: 'in-*.{{ .Values.global.domain }}'
