{{- if not .Values.global.platform.enabled }}
{{- if  .Values.keycloakConfigCli.enabled }}
{{- if  .Values.realm.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloaksrv-realm-configmap
  labels:
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: keycloak
data:
  ccm-realm.json: |-
    {
      "realm": "{{ .Values.realm.name }}",
      "enabled": true,
      "users": [],
      "clients": [
        {
          "clientId": "{{ .Values.realm.clientName.devopsplan }}",
          "enabled": true,
          "baseUrl": "{{ .Values.realm.clientUrl.devopsplan }}",
          "redirectUris": [
            "",
            "{{ .Values.realm.clientUrl.devopsplan }}/*"
          ],
          "webOrigins": [
            "{{ .Values.realm.clientUrl.devopsplan }}/*",
            "{{ .Values.realm.clientUrl.devopsplan }}"
          ],
          "standardFlowEnabled": true,
          "directAccessGrantsEnabled": true,
          "publicClient": true,
          "frontchannelLogout": true,
          "protocol": "openid-connect",
          "attributes": {
            "frontchannel.logout.session.required": "true",
            "use.refresh.tokens": "true",
            "backchannel.logout.session.required": "true",
          },
          "fullScopeAllowed": true,
        },
        {
          "clientId": "{{ .Values.realm.clientName.dashboard }}",
          "enabled": true,
          "rootUrl": "{{ .Values.realm.clientUrl.dashboard }}/",
          "adminUrl": "{{ .Values.realm.clientUrl.dashboard }}/",
          "baseUrl": "{{ .Values.realm.clientUrl.dashboard }}/",
          "redirectUris": [
            "{{ .Values.realm.clientUrl.dashboard }}/*"
          ],
          "webOrigins": [
            "{{ .Values.realm.clientUrl.dashboard }}/*"
          ],
          "standardFlowEnabled": true,
          "directAccessGrantsEnabled": true,
          "publicClient": true,
          "frontchannelLogout": true,
          "protocol": "openid-connect",
          "attributes": {
            "backchannel.logout.session.required": "true",
          },
          "fullScopeAllowed": true,
        }
      ],
      "roles": {
        "realm": []
      }
    }

{{- end }}
{{- end }}
{{- end }}
