global:
  platform:
    enabled: false
  imageRegistry: compass-docker-dev-local.us-artifactory1.nonprod.hclpnp.com

ingress:
  enabled: true
  ingressClassName: emissary
  hostname: keycloak.local
  pathType: ImplementationSpecific
  annotations:
    kubernetes.io/ingress.class: emissary
  tls: false

service:
  type: ClusterIP

auth:
  adminUser: admin
  adminPassword: byjB3HhxYZ

postgresql:
  enabled: true
  auth:
    postgresPassword: swmmHZMnjN
    password: byjB3HhxYZ

