{{- if eq (((.Values.global).platform).enabled) (true) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-platform-config
  labels:
{{ include "sch.metadata.labels.standard" (list . "cm") | indent 4 }}
data:
  platform-values.json: |
    {{- merge .Values.global .Values.platform | toJson | nindent 4 }}
{{- end }}
