{{- if eq (.Values.database.createDatabase) (true) }}
{{- include "sch.config.init" (list . "ibm-ucd-prod.sch.chart.config.values") -}}
{{- $fullName := include "sch.names.fullName" (list .) -}}
{{- $externalImagePrefix := include "{{ .Chart.Name }}.externalImagePrefix" . | trim -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-mysql
spec:
  selector:
    matchLabels:
      app: {{ $fullName }}-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ $fullName }}-mysql
    spec:
      securityContext:
{{- if not (.Capabilities.APIVersions.Has "security.openshift.io/v1") }}
        runAsUser: 1001
        fsGroup: {{ .Values.persistence.fsGroup }}
{{- else }}
        supplementalGroups: [{{ .Values.persistence.fsGroup }}]
{{- end }}
      containers:
      - image: {{ $externalImagePrefix }}mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              {{- if .Values.secret.name }}
              name: {{ .Values.secret.name }}
              {{- else }}
              name: {{ .Release.Name }}-secrets
              {{- end }}
              key: dbpassword
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              {{- if .Values.secret.name }}
              name: {{ .Values.secret.name }}
              {{- else }}
              name: {{ .Release.Name }}-secrets
              {{- end }}
              key: dbpassword
        - name: MYSQL_USER
          value: {{ .Values.database.username }}
        - name: MYSQL_DATABASE
          value: {{ .Values.database.name }}
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-devops-config
          mountPath: /etc/mysql/conf.d/mysql.devops.cnf
          subPath: mysql.devops.cnf
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ $fullName }}-mysql
      - name: mysql-devops-config
        configMap:
          name: {{ .Release.Name }}-mysql-devops-config
{{- end }}
