{{- if (.Capabilities.APIVersions.Has "route.openshift.io/v1") }}
{{- include "sch.config.init" (list . "ibm-ucd-prod.sch.chart.config.values") -}}
{{- $fullName := include "sch.names.fullName" (list .) -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName | quote }}
  labels:
{{ include "sch.metadata.labels.standard" (list . "route") | indent 4 }}
spec:
  {{- if eq (((.Values.global).platform).enabled) (true) }}
  host: {{ .Values.global.domain | quote }}
  path: {{ .Values.ingress.path }}
  {{- else }}
  host: {{ .Values.ingress.host | quote }}
  {{- end }}
  subdomain: ''
  to:
    kind: Service
    name: {{ $fullName | quote }}
    weight: 100
  port:
    {{- if .Values.secureConnections.required }}
    targetPort: https
    {{- else }}
    targetPort: http
    {{- end }}
  {{- if eq (((.Values.global).platform).enabled) (true) }}
  tls:
    termination: edge
    {{- if .Values.global.ibmCertSecretName }}
    {{- $tlsKey := index (lookup "v1" "Secret" .Release.Namespace .Values.global.ibmCertSecretName).data "tls.key" -}}
    {{- $tlsCrt := index (lookup "v1" "Secret" .Release.Namespace .Values.global.ibmCertSecretName).data "tls.crt" -}}
    {{- $caCert := index (lookup "v1" "Secret" .Release.Namespace .Values.global.ibmCertSecretName).data "ca.crt" -}}
    {{- if $tlsKey }}
    key: {{ $tlsKey | b64dec | quote }}
    certificate: {{ $tlsCrt | b64dec | quote }}
    {{- if $caCert }}
    caCertificate: {{ $caCert | b64dec | quote }}
    {{- end }}
    {{- end }}
    {{- end }}
    insecureEdgeTerminationPolicy: Redirect
  {{- else if .Values.secureConnections.required }}
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  {{- else if .Values.ingress.tlsSecret }}
  tls:
    termination: edge
    key: {{ index (lookup "v1" "Secret" .Release.Namespace .Values.ingress.tlsSecret).data "tls.key" | b64dec | quote }}
    certificate: {{ index (lookup "v1" "Secret" .Release.Namespace .Values.ingress.tlsSecret).data "tls.crt" | b64dec | quote }}
    {{- $caCert := index (lookup "v1" "Secret" .Release.Namespace .Values.ingress.tlsSecret).data "ca.crt" -}}
    {{ if $caCert }}caCertificate: {{ $caCert | b64dec | quote }} {{ end }}
    insecureEdgeTerminationPolicy: Redirect
  {{- end }}
  wildcardPolicy: None
status:
  ingress: []
{{- end }}
