{{- if not .Values.secret.name }}
{{- include "sch.config.init" (list . "ibm-ucd-prod.sch.chart.config.values") -}}
{{- $previous := lookup "v1" "Secret" .Release.Namespace (tpl "{{.Release.Name}}-secrets" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-secrets
  labels:
{{ include "sch.metadata.labels.standard" (list . "srv") | indent 4 }}
type: Opaque
data:
  {{- if $previous }}
  initpassword: {{ $previous.data.initpassword }}
  dbpassword: {{ $previous.data.dbpassword }}
  keystorepassword: {{ $previous.data.keystorepassword }}
  {{- else }}
  initpassword: {{ randAlphaNum 16 | b64enc | quote }}
  dbpassword: {{ randAlphaNum 16 | b64enc | quote }}
  keystorepassword: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
{{- end }}
