{{- include "sch.config.init" (list . "ibm-ucd-prod.sch.chart.config.values") -}}
{{- $fullName := include "sch.names.fullName" (list .) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullName | quote }}
  labels:
{{ include "sch.metadata.labels.standard" (list . "") | indent 4 }}
imagePullSecrets:
{{- if (lookup "v1" "Secret" .Release.Namespace "ibm-entitlement-key") }}
  - name: ibm-entitlement-key
{{- end }}
{{- if .Values.image.secret }}
  - name: {{ .Values.image.secret }}
{{- end }}
{{- if eq (((.Values.global).platform).enabled) (true) }}
{{- with .Values.global.imagePullSecrets }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
