{{- if (eq .Values.ingress.type "mapping") }}
{{- if .Values.ingress.cert.selfSigned }}
{{- if .Values.ingress.cert.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: cert
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-cert'
data:
  funcs.sh: |-
    {{- .Files.Get "lib/certificate/funcs.sh" | nindent 4 }}
  secret-curl-funcs.sh: |-
    {{- .Files.Get "lib/certificate/secret-curl-funcs.sh" | nindent 4 }}
  main.sh: |-
    #!/usr/bin/env bash
    set -e

    cd "$(dirname "$0")" || exit 1

    . funcs.sh
    . secret-curl-funcs.sh

    cert-make
    cert-show
{{- end }}
{{- end }}
{{- end }}