{{- if (eq .Values.ingress.type "mapping") }}
{{- if .Values.ingress.cert.selfSigned }}
{{- if .Values.ingress.cert.create }}
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: '10'
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: cert
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-cert'
spec:
  template:
    metadata:
      annotations:
        productID: e3e180b0faae4301b54c5c9b37319e5c
        productMetric: FLOATING_USER
        productName: IBM Rational Test Automation Server Basic
        productVersion: "11.0.5"
        cloudpakName : IBM DevOps for IBM Cloud Paks
        cloudpakId : dedb7a9445a44fb88c927c1658243cd1
        cloudpakMetric : RESOURCE_UNIT
        productCloudpakRatio : "1:1"
        productChargedContainers : All
      labels:
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/managed-by: '{{ .Release.Service }}'
        app.kubernetes.io/name: cert
        app.kubernetes.io/part-of: '{{ .Chart.Name }}'
        app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
        helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - command:
        - /bin/certificate/main.sh
        env:
        - name: INGRESS_DOMAIN
          value: {{ (.Values.ingress.cert).domain | default .Values.global.domain }}
        - name: INGRESS_SECRET
          value: {{ .Values.global.ibmCertSecretName }}
        image: '{{ (default (default .Values.imageRegistry .Values.global.imageRegistry) .Values.init.registry) }}/{{ regexReplaceAll .Values.imageRepoRegex .Values.init.image .Values.imageRepoRepl }}'
        imagePullPolicy: IfNotPresent
        name: main
{{- if .Values.init.resources }}
        resources: {{- toYaml .Values.init.resources | nindent 10 }}
{{- end }}
{{- template "testhub.container.security-context" .Values.containerSecurityContext }}
        volumeMounts:
{{- template "testhub.volumeMounts.kube-api-access" }}
        - mountPath: /bin/certificate/funcs.sh
          name: scripts
          subPath: funcs.sh
        - mountPath: /bin/secret-curl-funcs.sh
          name: scripts
          subPath: secret-curl-funcs.sh
        - mountPath: /bin/certificate/main.sh
          name: scripts
          subPath: main.sh
{{- if include "testhub.ibmImagePullSecret" . }}
      imagePullSecrets:
      - name: '{{ include "testhub.ibmImagePullSecret" . }}'
{{- end }}
      restartPolicy: Never
      hostIPC: false
      hostNetwork: false
      hostPID: false
{{- template "testhub.pod.security-context" $ }}
      serviceAccountName: '{{ .Release.Name }}-cert'
      volumes:
      - configMap:
          defaultMode: 365
          name: '{{ .Release.Name }}-cert'
        name: scripts
{{- template "testhub.volumes.kube-api-access" }}
{{- end }}
{{- end }}
{{- end }}