{{- if include "testhub.frontend.enabled" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-frontend'
data:
  env.json: |-
    {
        "features": {
            "onDemandDeployment": {
                "enabled": false
            }
        }
    }
{{- with .Values.ingress.path }}
  path.conf: |-
    RewriteEngine On

    RewriteRule ^/$ https://${INGRESS_DOMAIN}{{ . }}/ [R,L]

    RewriteRule ^{{ . }}$ https://${INGRESS_DOMAIN}{{ . }}/ [R,L]

    RewriteCond %{REQUEST_URI} !^{{ . }}/
    RewriteRule ^.*$ - [R=404,L]

    RewriteRule ^{{ . }}/(.*)$ /$1 [PT]
{{- end }}
{{- with .Values.frontend.headers }}
  headers.conf: |-
{{- range $key, $val := . }}
    Header set {{ $key }} {{ $val | quote }}
{{- end }}
{{- end }}
{{- end }}
