{{- if include "testhub.frontend.enabled" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-frontend'
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: '{{ .Release.Name }}'
      app.kubernetes.io/name: frontend
      app.kubernetes.io/part-of: '{{ .Chart.Name }}'
  template:
    metadata:
      annotations:
        checksum/config: '{{ include (print $.Template.BasePath "/frontend/configmap.yaml") . | sha256sum }}'
        productID: e3e180b0faae4301b54c5c9b37319e5c
        productMetric: FLOATING_USER
        productName: IBM Rational Test Automation Server Basic
        productVersion: "11.0.5"
        cloudpakName : IBM DevOps for IBM Cloud Paks
        cloudpakId : dedb7a9445a44fb88c927c1658243cd1
        cloudpakMetric : RESOURCE_UNIT
        productCloudpakRatio : "1:1"
        productChargedContainers : All
      labels:
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/name: frontend
        app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
{{- if .Values.priorityClassName }}
      priorityClassName: '{{ .Values.priorityClassName }}'
{{- end }}
      containers:
      - name: main
        image: '{{ (default (default .Values.imageRegistry .Values.global.imageRegistry) .Values.frontend.registry) }}/{{ regexReplaceAll .Values.imageRepoRegex .Values.frontend.image .Values.imageRepoRepl }}'
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: '{{ .Values.ingress.path }}/'
            port: http
          initialDelaySeconds: 5
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: '{{ .Values.ingress.path }}/'
            port: http
{{- if .Values.frontend.resources }}
        resources: {{- toYaml .Values.frontend.resources | nindent 10 }}
{{- end }}
{{- template "testhub.container.security-context" (mergeOverwrite .Values.containerSecurityContext (dict "readOnlyRootFilesystem" false) ) }}
        volumeMounts:
        - name: env
          mountPath: /var/www/html/env.json
          subPath: env.json
          readOnly: true
{{- with .Values.ingress.path }}
        - name: env
          mountPath: /etc/httpd/conf.d/path.conf
          subPath: path.conf
          readOnly: true
{{- end }}
{{- with .Values.frontend.headers }}
        - name: env
          mountPath: /etc/httpd/conf.d/headers.conf
          subPath: headers.conf
          readOnly: true
{{- end }}
{{- if .Values.extensions.script.enabled }}
        - name: artifacts
          mountPath: /var/www/html/artifacts/devops-test-runtime
          readOnly: true
{{- end }}
        env:
        - name: INGRESS_DOMAIN
          value: '{{ .Values.global.domain }}'
{{- if include "testhub.ibmImagePullSecret" . }}
      imagePullSecrets:
      - name: '{{ include "testhub.ibmImagePullSecret" . }}'
{{- end }}
      initContainers:
{{- if .Values.extensions.script.enabled }}
      - image: '{{ (default (default .Values.imageRegistry .Values.global.imageRegistry) .Values.scriptInstall.registry) }}/{{ regexReplaceAll .Values.imageRepoRegex .Values.scriptInstall.image .Values.imageRepoRepl }}'
        imagePullPolicy: Always
        name: script-install-provider
{{- if .Values.scriptInstall.resources }}
        resources: {{- toYaml .Values.scriptInstall.resources | nindent 10 }}
{{- end }}
{{- template "testhub.container.security-context" .Values.containerSecurityContext }}
        volumeMounts:
        - name: ingress
          mountPath: /usr/share/pki/ingress
          readOnly: true
        - name: artifacts
          mountPath: /usr/share/artifacts
          readOnly: false
        env:
        - name: INGRESS_DOMAIN
          value: '{{ .Values.global.domain }}'
        - name: INGRESS_DOMAIN_CONTEXT
          value: '{{ .Values.ingress.path }}'
{{- end }}
{{- template "testhub.initContainers.gateway-isready" $ }}
      hostIPC: false
      hostNetwork: false
      hostPID: false
{{- template "testhub.pod.security-context" $ }}
      serviceAccountName: '{{ .Release.Name }}-frontend'
      volumes:
      - name: ingress
        secret:
          optional: {{ ternary "false" "true" .Values.ingress.cert.selfSigned }}
          secretName: '{{ ternary .Values.global.ibmCertSecretName "none" .Values.ingress.cert.selfSigned }}'
      - name: env
        configMap:
          name: '{{ .Release.Name }}-frontend'
{{- if .Values.extensions.script.enabled }}
      - name: artifacts
        emptyDir: {}
{{- end }}
{{- end }}
