kind: ConfigMap
apiVersion: v1
metadata:
  name: swidtag-conf
  selfLink: /api/v1/namespaces/default/configmaps/swidtag-conf
  labels:
    {{- include "ucv.labels" . | nindent 4 }}
data:
  swidtag: |
    <?xml version="1.0" encoding="UTF-8" standalone="no"?><SoftwareIdentity xmlns="http://standards.iso.org/iso/19770/-2/2015/schema.xsd" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="IBM DevOps Velocity User" tagId="ibm.com-9fd91f4d567b4379a145635ada7a96d0-5.1.0" version="5.1.0" versionScheme="multipartnumeric" xml:lang="en" xsi:schemaLocation="http://standards.iso.org/iso/19770/-2/2015-current/schema.xsd schema.xsd">    <Meta persistentId="9fd91f4d567b4379a145635ada7a96d0"/>    <Meta generator="4-1-20210113"/>    <Entity name="IBM" regid="ibm.com" role="licensor tagCreator softwareCreator"/></SoftwareIdentity>
