{{- if and (not (.Capabilities.APIVersions.Has "route.openshift.io/v1")) (not (eq (((.Values.global).platform).enabled) (true))) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: velocity-ingress
  annotations:
    {{- if eq .Values.ingress.path "/" }}
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- else }}
    ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- end }}
    ingress.kubernetes.io/configuration-snippet: proxy_pass_request_headers on;
    nginx.ingress.kubernetes.io/configuration-snippet: proxy_pass_request_headers on;
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
    {{- if not .Values.ingress.className }}
    kubernetes.io/ingress.class: "nginx"
    {{- end }}
  labels:
    {{- include "ucv.labels" . | nindent 4 }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  tls:
    - secretName: {{ .Values.secrets.tls }}
      hosts:
        - {{ include "ucv.domain" . }}
  defaultBackend:
    service:
      name: velocity-router
      port:
        number: 8080
  rules:
    - host: {{ include "ucv.domain" . }}
      http:
        paths:
          - path: {{ ternary "/" (printf "/%s(/|$)(.*)" (.Values.ingress.path | trimPrefix "/" | trimSuffix "/")) (eq .Values.ingress.path "/") }}
            pathType: Prefix
            backend:
              service:
                name: velocity-router
                port:
                  number: 8080
{{- end }}