apiVersion: v1
kind: ConfigMap
metadata:
  name: plugins-configmap
  labels:
    {{- include "ucv.labels" . | nindent 4 }}
data:
  config: |
    job:
      spec:
        template:
          spec:
            restartPolicy: Never
            serviceAccountName: {{ .Values.serviceAccountName }}
            imagePullSecrets:
              {{- include "ucv.imagePullSecrets" . | nindent 14 }}
            affinity:
              {{- $vars := merge (dict) . -}}
              {{- $_ := set $vars "ucvWorkloadClass" "background" -}}
              {{- include "ucv.nodeAffinity" $vars | nindent 14 }}
    container:
      imagePullPolicy: IfNotPresent
      resources:
        {{- $vars := merge (dict) . -}}
        {{- $_ := set $vars "ucvService" "integrations" -}}
        {{- include "ucv.resources" $vars | nindent 8 }}
      securityContext:
        {{- include "ucv.securityContext" . | nindent 8 }}
