{{- if not (((.Values.global).platform).enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rcl-client
  labels:
    {{- include "ucv.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- $vars := merge (dict) . -}}
      {{- $_ := set $vars "ucvService" "rcl-client" -}}
      {{- include "ucv.selector" $vars | nindent 6 }}
  template:
    metadata:
      labels:
        {{- $vars := merge (dict) . -}}
        {{- $_ := set $vars "ucvService" "rcl-client" -}}
        {{- include "ucv.specTemplateLabels" $vars | nindent 8 }}
      annotations:
        {{- include "ucv.productAnnotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      imagePullSecrets:
        {{- include "ucv.imagePullSecrets" . | nindent 8 }}
      affinity:
        {{- $vars := merge (dict) . -}}
        {{- $_ := set $vars "ucvWorkloadClass" "external" -}}
        {{- include "ucv.nodeAffinity" $vars | nindent 8 }}
      containers:
        - name: rcl-client
          image:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvImageRegistry" .Values.imageRegistry.velocityRegistry -}}
            {{- $_ := set $vars "ucvImageRegistryPath" .Values.imageRegistry.velocityPath -}}
            {{- $_ := set $vars "ucvImageName" "rcl-client" -}}
            {{- $_ := set $vars "ucvImageTag" "5.0.0.98" -}}
            {{- include "ucv.image" $vars | nindent 12 }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4567
          env:
            - name: NODE_OPTIONS
              {{- $vars := merge (dict) . -}}
              {{- $_ := set $vars "ucvService" "rcl-client" -}}
              {{- include "ucv.maxOldSpaceSize" $vars | nindent 14 }}
          resources:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvService" "rcl-client" -}}
            {{- include "ucv.resources" $vars | nindent 12 }}
          securityContext:
            {{- include "ucv.securityContext" . | nindent 12 }}
          livenessProbe:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvService" "rcl-client" -}}
            {{- $_ := set $vars "ucvLivenessPort" 4567 -}}
            {{- include "ucv.livenessProbe" $vars | nindent 12 }}
          readinessProbe:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvService" "rcl-client" -}}
            {{- $_ := set $vars "ucvReadinessPort" 4567 -}}
            {{- include "ucv.readinessProbe" $vars | nindent 12 }}
{{- end }}
