apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-events-ui
  labels:
    {{- include "ucv.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- $vars := merge (dict) . -}}
      {{- $_ := set $vars "ucvService" "release-events-ui" -}}
      {{- include "ucv.selector" $vars | nindent 6 }}
  template:
    metadata:
      labels:
        {{- $vars := merge (dict) . -}}
        {{- $_ := set $vars "ucvService" "release-events-ui" -}}
        {{- include "ucv.specTemplateLabels" $vars | nindent 8 }}
      annotations:
        {{- include "ucv.productAnnotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      imagePullSecrets:
        {{- include "ucv.imagePullSecrets" . | nindent 8 }}
      affinity:
        {{- $vars := merge (dict) . -}}
        {{- $_ := set $vars "ucvWorkloadClass" "transactional" -}}
        {{- include "ucv.nodeAffinity" $vars | nindent 8 }}
      containers:
        - name: release-events-ui
          image:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvImageRegistry" .Values.imageRegistry.velocityRegistry -}}
            {{- $_ := set $vars "ucvImageRegistryPath" .Values.imageRegistry.velocityPath -}}
            {{- $_ := set $vars "ucvImageName" "release-events-ui" -}}
            {{- $_ := set $vars "ucvImageTag" "5.1.6.6" -}}
            {{- include "ucv.image" $vars | nindent 12 }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3010
          env:
            - name: NODE_OPTIONS
              {{- $vars := merge (dict) . -}}
              {{- $_ := set $vars "ucvService" "release-events-ui" -}}
              {{- include "ucv.maxOldSpaceSize" $vars | nindent 14 }}
            - name: NODE_ENV
              value: production
            - name: PORT
              value: '3010'
            - name: LOG_LEVEL
              value: {{ .Values.loglevel }}
            - name: release_events_api__host
              value: {{ template "root.url.releaseEventsApi" . }}
            - name: security_api__host
              value: {{ template "root.url.securityApiHost" . }}
            - name: reporting_consumer__host
              value: {{ template "root.url.reportingConsumer" . }}
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: '0'
            - name: version
              value: {{ .Chart.Version }}
            - name: MARKETING_VERSION
              value: {{ .Values.marketingVersion | quote }}
            - name: OPEN_TELEMETRY
              value: {{ .Values.openTelemetryEnabled }}
            - name: OPEN_TELEMETRY_LOG_LEVEL
              value: {{ .Values.openTelemetryLogLevel }}
            - name: OPEN_TELEMETRY_COLLECTOR
              value: {{ index .Values "opentelemetry-collector" "fullnameOverride" }}
            - name: contextPath
              value: {{ .Values.ingress.path }}
            - name: PLATFORM_PATH
              value: {{ ((.Values.global).platform).path }}
          resources:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvService" "release-events-ui" -}}
            {{- include "ucv.resources" $vars | nindent 12 }}
          securityContext:
            {{- include "ucv.securityContext" . | nindent 12 }}
          livenessProbe:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvService" "release-events-ui" -}}
            {{- $_ := set $vars "ucvLivenessPort" 3010 -}}
            {{- include "ucv.livenessProbe" $vars | nindent 12 }}
          readinessProbe:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvService" "release-events-ui" -}}
            {{- $_ := set $vars "ucvReadinessPort" 3010 -}}
            {{- include "ucv.readinessProbe" $vars | nindent 12 }}
