apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-consumer
  labels:
    {{- include "ucv.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- $vars := merge (dict) . -}}
      {{- $_ := set $vars "ucvService" "reporting-consumer" -}}
      {{- include "ucv.selector" $vars | nindent 6 }}
  template:
    metadata:
      labels:
        {{- $vars := merge (dict) . -}}
        {{- $_ := set $vars "ucvService" "reporting-consumer" -}}
        {{- include "ucv.specTemplateLabels" $vars | nindent 8 }}
      annotations:
        {{- include "ucv.productAnnotations" . | nindent 8 }}
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      imagePullSecrets:
        {{- include "ucv.imagePullSecrets" . | nindent 8 }}
      affinity:
        {{- $vars := merge (dict) . -}}
        {{- $_ := set $vars "ucvWorkloadClass" "transactional" -}}
        {{- include "ucv.nodeAffinity" $vars | nindent 8 }}
      initContainers:
        - name: init-amqp
          image:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvImageRegistry" .Values.imageRegistry.redhat -}}
            {{- $_ := set $vars "ucvImageName" "ubi9/ubi-minimal" -}}
            {{- $_ := set $vars "ucvImageTag" "latest" -}}
            {{- include "ucv.external.image" $vars | nindent 12 }}
          imagePullPolicy: IfNotPresent
          resources:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvService" "init-container" -}}
            {{- include "ucv.resources" $vars | nindent 12 }}
          securityContext:
            {{- include "ucv.securityContext" . | nindent 12 }}
          command: ['sh', '-c', 'until [ "$(curl -s -o /dev/null -w "%{http_code}" http://velocity-rabbitmq:15672)" == "200" ]; do echo waiting for amqp; sleep 5; done;']
        - name: init-security-api
          image:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvImageRegistry" .Values.imageRegistry.redhat -}}
            {{- $_ := set $vars "ucvImageName" "ubi9/ubi-minimal" -}}
            {{- $_ := set $vars "ucvImageTag" "latest" -}}
            {{- include "ucv.external.image" $vars | nindent 12 }}
          imagePullPolicy: IfNotPresent
          resources:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvService" "init-container" -}}
            {{- include "ucv.resources" $vars | nindent 12 }}
          securityContext:
            {{- include "ucv.securityContext" . | nindent 12 }}
          command: ['sh', '-c', 'until [ "$(curl -s http://security-api:3911/ready)" == "ready" ]; do echo waiting for security-api; sleep 5; done;']
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: reporting-consumer
          image:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvImageRegistry" .Values.imageRegistry.velocityRegistry -}}
            {{- $_ := set $vars "ucvImageRegistryPath" .Values.imageRegistry.velocityPath -}}
            {{- $_ := set $vars "ucvImageName" "reporting-consumer" -}}
            {{- $_ := set $vars "ucvImageTag" "5.1.6.6" -}}
            {{- include "ucv.image" $vars | nindent 12 }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6004
          env:
            - name: NODE_OPTIONS
              {{- $vars := merge (dict) . -}}
              {{- $_ := set $vars "ucvService" "reporting-consumer" -}}
              {{- include "ucv.maxOldSpaceSize" $vars | nindent 14 }}
            - name: MONGO_URL
              {{- include "ucv.mongoUrl" . | nindent 14 }}
            - name: MONGO_DB
              value: reporting
            - name: ENCRYPT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.tokens }}
                  key: cipherToken
            - name: HMAC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.tokens }}
                  key: hmacKey
            - name: CONSUMER_URL
              value: {{ template "root.url.reportingConsumer" . }}
            - name: INTERNAL_CONSUMER_URL
              value: 'http://reporting-consumer:6004'
            - name: HELM_VERSION
              value: {{ .Chart.Version }}
            - name: LOG_LEVEL
              value: {{ .Values.loglevel }}
            - name: RABBITMQ_HOST
              value: velocity-rabbitmq
            - name: RABBITMQ_PORT
              value: '5672'
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.rabbit }}
                  key: user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.rabbit }}
                  key: password
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: '0'
            - name: GRAPHQL_URL
              value: http://release-events-api:8080
            - name: BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.tokens }}
                  key: apiToken
            - name: SECURITY_API_URL
              value: http://security-api:3911
            - name: APP_API_URL
              value: http://application-api:3499
            - name: MAP_API_URL
              value: http://multi-app-pipeline-api:9090/v1/multi-app-pipeline
            - name: LEGACY_JENKINS_MIGRATION_PAGE_SIZE
              value: '200'
            - name: LEGACY_JENKINS_MIGRATION_CHUNK_SIZE
              value: '500'
            - name: PLUGINS_INDEX_URL
              value: {{ .Values.pluginIndexUrl }}
            - name: WORKFLOW_FRAMEWORK_ENABLED
              value: 'true'
            - name: KUBE_SERVICE_ACCOUNT_NAME
              value: {{ .Values.serviceAccountName }}
            - name: KUBE_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: KUBE_TOKENS_SECRET_NAME
              value: {{ .Values.secrets.tokens }}
            - name: PLUGIN_DEFAULT_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: plugins-configmap
                  key: config
            - name: PLUGIN_CUSTOM_CONFIG
              value: {{ .Values.pluginCustomConfig }}
            - name: CRD_BETA_RESOURCE
              value: {{ not (.Capabilities.APIVersions.Has "apiextensions.k8s.io/v1") | quote }}
            - name: PRODUCT_VERSION
              value: {{ .Chart.Version }}
            - name: PLUGINS_IMAGE_PULL_SECRET_NAME
              value: {{ .Values.secrets.imagePull }}
            - name: OPEN_TELEMETRY
              value: {{ .Values.openTelemetryEnabled }}
            - name: OPEN_TELEMETRY_LOG_LEVEL
              value: {{ .Values.openTelemetryLogLevel }}
            - name: OPEN_TELEMETRY_COLLECTOR
              value: {{ index .Values "opentelemetry-collector" "fullnameOverride" }}
          resources:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvService" "reporting-consumer" -}}
            {{- include "ucv.resources" $vars | nindent 12 }}
          securityContext:
            {{- include "ucv.securityContext" . | nindent 12 }}
          livenessProbe:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvService" "reporting-consumer" -}}
            {{- $_ := set $vars "ucvLivenessPort" 6004 -}}
            {{- include "ucv.livenessProbe" $vars | nindent 12 }}
          readinessProbe:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvService" "reporting-consumer" -}}
            {{- $_ := set $vars "ucvReadinessPort" 6004 -}}
            {{- include "ucv.readinessProbe" $vars | nindent 12 }}
          {{- include "ucv.mongoVolumeMounts" . | nindent 10 }}
      {{- include "ucv.mongoVolumes" . | nindent 6 }}
