kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.serviceAccountName }}
  labels:
    {{- include "ucv.labels" . | nindent 4 }}
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps", "secrets", "services", "persistentvolumes", "persistentvolumeclaims", "pods", "pods/log", "replicasets", "deployments", "ingresses"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["jobs", "jobs/logs"]
  verbs: ["create", "delete", "get", "list"]