{{- if .Capabilities.APIVersions.Has "route.openshift.io/v1" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: velocity-route
  labels:
    {{- include "ucv.labels" . | nindent 4 }}
  {{- if ne .Values.ingress.path "/" }}
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
  {{- end }}
spec:
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  host: {{- include "ucv.domain" . }}
  path: {{ .Values.ingress.path }}
  port:
    targetPort: 8080
  to:
    kind: Service
    name: velocity-router
    weight: 100
  wildcardPolicy: None
status:
  ingress: []
{{- end }}