apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-api
  labels:
    {{- include "ucv.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- $vars := merge (dict) . -}}
      {{- $_ := set $vars "ucvService" "security-api" -}}
      {{- include "ucv.selector" $vars | nindent 6 }}
  template:
    metadata:
      labels:
        {{- $vars := merge (dict) . -}}
        {{- $_ := set $vars "ucvService" "security-api" -}}
        {{- include "ucv.specTemplateLabels" $vars | nindent 8 }}
      annotations:
        {{- include "ucv.productAnnotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      imagePullSecrets:
        {{- include "ucv.imagePullSecrets" . | nindent 8 }}
      affinity:
        {{- $vars := merge (dict) . -}}
        {{- $_ := set $vars "ucvWorkloadClass" "transactional" -}}
        {{- include "ucv.nodeAffinity" $vars | nindent 8 }}
      containers:
        - name: security-api
          image:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvImageRegistry" .Values.imageRegistry.velocityRegistry -}}
            {{- $_ := set $vars "ucvImageRegistryPath" .Values.imageRegistry.velocityPath -}}
            {{- $_ := set $vars "ucvImageName" "security-api" -}}
            {{- $_ := set $vars "ucvImageTag" "5.1.6.6" -}}
            {{- include "ucv.image" $vars | nindent 12 }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3911
          env:
            - name: NODE_OPTIONS
              {{- $vars := merge (dict) . -}}
              {{- $_ := set $vars "ucvService" "security-api" -}}
              {{- include "ucv.maxOldSpaceSize" $vars | nindent 14 }}
            - name: PORT
              value: '3911'
            - name: MONGO_DB
              value: security
            - name: LOG_LEVEL
              value: {{ .Values.loglevel }}
            - name: MONGO_URL
              {{- include "ucv.mongoUrl" . | nindent 14 }}
            - name: SERVER_HOST
              value: {{ include "ucv.domain" . }}
            - name: SERVER_PORT
              value: {{ quote .Values.url.port }}
            - name: BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.tokens }}
                  key: apiToken
            - name: SECURITY_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.tokens }}
                  key: hmacKey
            - name: ENCRYPT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.tokens }}
                  key: cipherToken
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: '0'
            - name: ACCESS_KEY
              value: {{ .Values.access.key }}
            - name: RCL_CLIENT_URL
              value: http://rcl-client:4567
            - name: RABBITMQ_HOST
              value: velocity-rabbitmq
            - name: RABBITMQ_PORT
              value: '5672'
            - name: OPEN_TELEMETRY
              value: {{ .Values.openTelemetryEnabled }}
            - name: OPEN_TELEMETRY_LOG_LEVEL
              value: {{ .Values.openTelemetryLogLevel }}
            - name: OPEN_TELEMETRY_COLLECTOR
              value: {{ index .Values "opentelemetry-collector" "fullnameOverride" }}
            - name: CONTEXT_PATH
              value: {{ (.Values.ingress).path }}
            - name: OIDC_CONFIG_DOMAIN
              value: {{ (.Values.global).domain }}
            - name: OIDC_CONFIG_ISSUER_PATH
              value: {{ (((.Values.global).platform).oidc).issuerPath }}
            - name: OIDC_CONFIG_AUTH_PATH
              value: {{ (((.Values.global).platform).oidc).authorizationPath }}
            - name: OIDC_CONFIG_USER_PATH
              value: {{ (((.Values.global).platform).oidc).userinfoPath }}
            - name: OIDC_CONFIG_TOKEN_PATH
              value: {{ (((.Values.global).platform).oidc).tokenPath }}
            - name: OIDC_CONFIG_LOGOUT_PATH
              value: {{ (((.Values.global).platform).oidc).logoutPath }}
            - name: OIDC_CONFIG_JWKS_PATH
              value: {{ (((.Values.global).platform).oidc).jwksPath }}
            - name: OIDC_CONFIG_CLIENT_ID
              value: {{ ((.Values.platform).oidc).clientId }}
            - name: OIDC_CONFIG_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{- include "ucv.oidc.client.secret.name" . | indent 1 }}
                  key: oauth-client-secret
                  optional: true
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.rabbit }}
                  key: user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.rabbit }}
                  key: password
            - name: INITIAL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.initialAdminPassword }}
                  key: password
            - name: PLATFORM_PATH
              value: {{ ((.Values.global).platform).path }}
            - name: LDAP_CONNECT_TIMEOUT
              value: {{ quote .Values.ldapConnectTimeout }}
          resources:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvService" "security-api" -}}
            {{- include "ucv.resources" $vars | nindent 12 }}
          securityContext:
            {{- include "ucv.securityContext" . | nindent 12 }}
          livenessProbe:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvService" "security-api" -}}
            {{- $_ := set $vars "ucvLivenessPort" 3911 -}}
            {{- include "ucv.livenessProbe" $vars | nindent 12 }}
          readinessProbe:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvService" "security-api" -}}
            {{- $_ := set $vars "ucvReadinessPort" 3911 -}}
            {{- include "ucv.readinessProbe" $vars | nindent 12 }}
          volumeMounts:
            - name: jwt-keys
              mountPath: /security-api/jwt-keys
            {{- include "ucv.mongoTlsVolumeMount" . | nindent 12 }}
      volumes:
        - name: jwt-keys
          secret:
            secretName: {{ .Values.secrets.jwt }}
            items:
              - key: public.key
                path: public.key
              - key: private.key
                path: private.key
        {{- include "ucv.mongoTlsVolume" . | nindent 8 }}
