apiVersion: v1
kind: Service
metadata:
  name: velocity-rabbitmq
  labels:
    {{- include "ucv.labels" . | nindent 4 }}
spec:
  type: {{ kindIs "invalid" .Values.rabbitmq.nodePort | ternary "ClusterIP" "NodePort" }}
  sessionAffinity: None
  ports:
    - name: epmd
      port: 4369
      targetPort: epmd
    - name: amqp
      port: 5672
      targetPort: amqp
      {{- include "ucv.rabbit.nodePort" . | nindent 6 }}
    - name: dist
      port: {{ .Values.rabbitmq.nodePort | default 31672 | add 20000 }}
      targetPort: dist
    - name: stats
      port: {{ .Values.rabbitmq.managerPort }}
      targetPort: stats
  selector:
    {{- $vars := merge (dict) . -}}
    {{- $_ := set $vars "ucvService" "velocity-rabbitmq" -}}
    {{- include "ucv.selector" $vars | nindent 4 }}
