apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocity-router
  labels:
    {{- include "ucv.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- $vars := merge (dict) . -}}
      {{- $_ := set $vars "ucvService" "velocity-router" -}}
      {{- include "ucv.selector" $vars | nindent 6 }}
  template:
    metadata:
      labels:
        {{- $vars := merge (dict) . -}}
        {{- $_ := set $vars "ucvService" "velocity-router" -}}
        {{- include "ucv.specTemplateLabels" $vars | nindent 8 }}
      annotations:
        {{- include "ucv.productAnnotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      imagePullSecrets:
        {{- include "ucv.imagePullSecrets" . | nindent 8 }}
      affinity:
        {{- $vars := merge (dict) . -}}
        {{- $_ := set $vars "ucvWorkloadClass" "transactional" -}}
        {{- include "ucv.nodeAffinity" $vars | nindent 8 }}
      containers:
        - name: nginx
          image:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvImageRegistry" .Values.imageRegistry.docker -}}
            {{- $_ := set $vars "ucvImageName" "bitnami/nginx" -}}
            {{- $_ := set $vars "ucvImageTag" "1.27.1" -}}
            {{- include "ucv.external.image" $vars | nindent 12 }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-conf
              mountPath: /opt/bitnami/nginx/conf/nginx.conf
              subPath: nginx.conf
            - name: nginx-pid
              mountPath: /opt/bitnami/nginx/pid
          resources:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvService" "velocity-router" -}}
            {{- include "ucv.resources" $vars | nindent 12 }}
          securityContext:
            {{- include "ucv.securityContext" . | nindent 12 }}
          livenessProbe:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvService" "velocity-router" -}}
            {{- $_ := set $vars "ucvLivenessPort" 8080 -}}
            {{- include "ucv.livenessProbe" $vars | nindent 12 }}
          readinessProbe:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvService" "velocity-router" -}}
            {{- $_ := set $vars "ucvReadinessPort" 8080 -}}
            {{- include "ucv.readinessProbe" $vars | nindent 12 }}
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
            - key: nginx.conf
              path: nginx.conf
        - name: nginx-pid
          emptyDir: {}
