{{- if .Values.randomInitialAdminPassword }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ucv-initial-admin-password-gen
  labels:
    {{- include "ucv.labels" . | nindent 4 }}
imagePullSecrets:
  {{- include "ucv.imagePullSecrets" . | nindent 2 }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ucv-initial-admin-password-gen
  labels:
    {{- include "ucv.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ucv-initial-admin-password-gen
  labels:
    {{- include "ucv.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ucv-initial-admin-password-gen
subjects:
- kind: ServiceAccount
  name: ucv-initial-admin-password-gen
  namespace: {{ .Release.Namespace }}

---

apiVersion: batch/v1
kind: Job
metadata:
  name: ucv-initial-admin-password-secret-generator
  labels:
    {{- include "ucv.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      labels:
        {{- $vars := merge (dict) . -}}
        {{- $_ := set $vars "ucvService" "ucv-initial-admin-password-secret-generator" -}}
        {{- include "ucv.specTemplateLabels" $vars | nindent 8 }}
      annotations:
        {{- include "ucv.productAnnotations" . | nindent 8 }}
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      imagePullSecrets:
        {{- include "ucv.imagePullSecrets" . | nindent 8 }}
      affinity:
        {{- $vars := merge (dict) . -}}
        {{- $_ := set $vars "ucvWorkloadClass" "background" -}}
        {{- include "ucv.nodeAffinity" $vars | nindent 8 }}
      restartPolicy: Never
      serviceAccountName: ucv-initial-admin-password-gen
      containers:
        - name: ucv-initial-admin-password-secret-generator
          image:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvImageRegistry" .Values.imageRegistry.docker -}}
            {{- $_ := set $vars "ucvImageName" "bitnami/kubectl" -}}
            {{- $_ := set $vars "ucvImageTag" "1.22.13" -}}
            {{- include "ucv.external.image" $vars | nindent 12 }}
          imagePullPolicy: IfNotPresent
          command:
          - /bin/bash
          - -c
          - |
              SECRET_NAME="{{ .Values.secrets.initialAdminPassword }}"
              EXISTING_SECRET=$(kubectl get secret ${SECRET_NAME} -o name 2>&1)
              if [[ "$EXISTING_SECRET" == "secret/${SECRET_NAME}" ]]; then
                echo "Secret '${SECRET_NAME}' already exists"
                exit 0
              fi
              echo "Creating secret '${SECRET_NAME}'..."
              set -e
              cat <<EOF | kubectl create -f -
                apiVersion: v1
                kind: Secret
                type: Opaque
                metadata:
                  name: '${SECRET_NAME}'
                  labels:
                    {{- include "ucv.labels" . | nindent 20 }}
                stringData:
                  password: {{ randAlphaNum 16 | quote }}
              EOF
          resources:
            {{- $vars := merge (dict) . -}}
            {{- $_ := set $vars "ucvService" "ucv-initial-admin-password-secret-generator" -}}
            {{- include "ucv.resources" $vars | nindent 12 }}
          securityContext:
            {{- include "ucv.securityContext" . | nindent 12 }}
          livenessProbe:
            exec:
              command:
                - kubectl
                - --help
              {{- $vars := merge (dict) . -}}
              {{- $_ := set $vars "ucvService" "ucv-initial-admin-password-secret-generator" -}}
              {{- include "ucv.livenessProbeTimeouts" $vars | nindent 12 }}
          readinessProbe:
            exec:
              command:
                - kubectl
                - --help
              {{- $vars := merge (dict) . -}}
              {{- $_ := set $vars "ucvService" "ucv-initial-admin-password-secret-generator" -}}
              {{- include "ucv.readinessProbeTimeouts" $vars | nindent 12 }}
{{- end }}