#!/usr/bin/env bash
. "$(dirname "${BASH_SOURCE[0]}")/../lib/cli.sh"

# cli.sh does 'set -e' this script needs to override this so
# that commands like:
#   tar ... | grep -v ...
# don't cause the script to exit when grep filters all output
set +e

: "${K3S_STORAGE:=/var/lib/rancher/k3s/storage}"
K3S_PVC_LINKS_DIR=${K3S_PVC_LINKS_DIR:="$(cd "$(dirname "$0")"; pwd)"/pvc-links}

backupFile=
sourceNamespace=
targetNamespace=
sourceRelease=
targetRelease=
skipConfirm=0
volumesDir="$K3S_PVC_LINKS_DIR"
operation=


usage() {
  echo "Usage: $0 <command> [options] <backup-file>"
  echo
  echo "This script is used to manage backups of local persistent volumes."
  echo
  echo "Creating and restoring backups requires metadata to map volume data"
  echo "correctly.  This is stored in a directory which is generated by the"
  echo "create-pvc-links command."
  echo
  echo "Backups are created as tar archives compressed using gzip (.tar.gz)."
  echo
  echo "A restore will work on a compressed or uncompressed tar.  It will run more quickly"
  echo "using an uncompressed tar, at the cost of using more disk space."
  echo
  echo "Commands:"
  echo
  echo "create-pvc-links - create a directory of links to the persistent volumes"
  echo
  echo "-v | --volumes <directory>"
  echo "  Creates links in the specified directory that store the required"
  echo "  metadata.  If not provided, defaults to:"
  echo "    $K3S_PVC_LINKS_DIR"
  echo
  echo "create - archive the volumes into <backup-file>, the options are:"
  echo
  echo "-n | --namespace <namespace>"
  echo "  The namespace to backup, if omitted volumes from all namespaces are included"
  echo "-v | --volumes <directory>"
  echo "  Directory containing links to the volumes, expressed as an absolute path.  Defaults to:"
  echo "    $K3S_PVC_LINKS_DIR"
  echo
  echo "restore - overwite existing volumes with data from <backup_file>, the options are:"
  echo
  echo "-n | --namespace <namespace>[:<target-namespace>]"
  echo "  The namespace to restore, if omitted volumes from all namespaces in the backup"
  echo "  are restored.  If volumes in a backup are being restored into a different namespace, it should"
  echo "  also be specified (separated by a ':')"
  echo "-r | --release <backup-release>:<target-release>"
  echo "  If the release to which the backup is being restored is different to that in the backup,"
  echo "  this should be used to specify the mapping"
  echo "-v | --volumes <directory>"
  echo "  Directory containing links to the volumes, expressed as an absolute path.  Defaults to:"
  echo "    $K3S_PVC_LINKS_DIR"
  echo "-k | --confirm"
  echo "  Skip the confirmation step"
  exit 1
}

parse-release() {
  eval set -- "$(echo "$1" | tr ':' ' ')"
  sourceRelease="$1"
  targetRelease="$2"
}

parse-namespace() {
  eval set -- "$(echo "$1" | tr ':' ' ')"
  sourceNamespace="$1"
  if [ "$2" != "" ]; then
    targetNamespace="$2"
  else
    targetNamespace="$sourceNamespace"
  fi
}

parse-arguments() {
  operation="$1"
  case "$operation" in
    create|restore|create-pvc-links) shift;;
    *)operation=
  esac
  if ! parsed=$(getopt -o n:r:v:k \
	  -l namespace:,release:,volumes:,confirm,help \
	  -n "$(basename "$0")" -- "$@"); then
    usage
  fi
  eval set -- "$parsed"
  while true; do
    case "$1" in
      -n|--namespace) parse-namespace "$2"; shift;;
      -r|--release) parse-release "$2"; shift;;
      -v|--volumes)volumesDir="$2"; shift;;
      -k|--confirm) skipConfirm=1;;
      --help) usage;;
      --) shift; backupFile="$*"; break
    esac
    shift
  done

  if [ "$operation" == "" ]; then
    echo-error "unknown command"; usage
  fi
}

k3s-is-running() {
  systemctl -q is-active k3s.service
}

# $1 - directory
file-count() {
  find "$1" -maxdepth 1 -mindepth 1 | wc -l
}

# $1 - "exists" or "does-not-exist"
validate-backup-file() {
  local flag
  local msg
  case "$1" in
    exists) flag="!"; msg="does not exist";;
    does-not-exist) flag=; msg="already exists";;
    *) echo-error "Invalid parameter to validate-backup-file"; exit 100
  esac

# Shellcheck doesn't understand use of $flag in test
#shellcheck disable=SC2057
  if [ "$backupFile" = "" ]; then
    echo-error "a backup file must be specified"
  elif [ $flag -f "$backupFile" ]; then
    echo-error "the specified backup file ($backupFile) $msg"
  else
    return 0
  fi
  return 1
}


validate-volumes-dir() {
# Shellcheck dislikes the check if there are files that don't match *-pvc-*
#shellcheck disable=SC2010
  if ! echo "$volumesDir" | grep -qe "^/"; then
    echo-error "the volumes directory must be specified as an absolute path"
  elif [ "$volumesDir" = "" ]; then
    echo-error "the volumes directory cannot be /"
  elif [ ! -d "$volumesDir" ]; then
    echo-error "the volumes directory ($volumesDir) does not exist"
  elif ls "$volumesDir" | grep -qv "\-pvc\-"; then
    echo-error "the volumes directory ($volumesDir) contains unexpected content"
  elif [ "$(ls "$volumesDir")" = "" ]; then
    echo-error "the volumes directory ($volumesDir) is empty"
  elif [ "$(file-count "$volumesDir")" -ne "$(file-count "$K3S_STORAGE")" ]; then
    echo-error "mismatched number of volumes and links"
    echo "  K3S storage directory ($K3S_STORAGE) has $(file-count "$K3S_STORAGE") entries"
    echo "  The links directory ($volumesDir) has $(file-count "$volumesDir") entries."
  else
    local errorCount
    errorCount=0
    for f in "$volumesDir"/*; do
      if [ ! -L "$f" ]; then
        echo-error "$f is not a symbolic link"
	errorCount=$(("$errorCount"+1))
      elif [ ! -e "$f" ]; then
        echo-error "$f does not link to a valid directory"
	errorCount=$(("$errorCount"+1))
      elif ! readlink -f "$f" | grep -qE "^$K3S_STORAGE/[^/]+$"; then
        echo-error "$f does not link to a directory under $K3S_STORAGE"
	echo "  $(ls -l "$f")"
	errorCount=$(("$errorCount"+1))
      elif [ ! -d "$(readlink -f "$f")" ]; then
        echo-error "$f does not link to a directory"
	echo "  $(ls -l "$f")"
	errorCount=$(("$errorCount"+1))
      fi
    done
    if [ "$errorCount" -eq 0 ]; then
      return 0
    fi
    echo-error "$errorCount errors validating $volumesDir"
  fi
  return 1
}

assert-restore-parameters-valid() {
  local status
  status=0

  if ! validate-backup-file exists; then
    status=1
  fi
  if ! validate-volumes-dir; then
    status=1
  fi
  if [ "$sourceRelease" != "" ] && [ "$targetRelease" = "" ]; then
    echo-error "no target release is specified (source release is $sourceRelease)"
    status=1
  fi

  if [ "$status" -ne 0 ]; then
    usage
  fi
}

assert-create-parameters-valid() {
  local status
  status=0

  if ! validate-backup-file does-not-exist; then
    status=1
  fi
  if ! validate-volumes-dir; then
    status=1
  fi

  if [ "$status" -ne 0 ]; then
    usage
  fi
}

find-source-directories() {
  tar tf "$backupFile" | grep -v -e ".*$sourceNamespace.*/[^[:space:]]" | grep -e "^\(\./\)\?$sourceNamespace"
}

# $1 source directory
find-target-directory() {
  local target
  # replace the namespace and strip of the leading './' if it's present
  target=$(echo "$1" | sed  "s#\(\./\)\?$sourceNamespace\(-.*\)#$targetNamespace\2#")

  # replace the release
  target=$(echo "$target" | sed "s#\($targetNamespace.*\)$sourceRelease\(.*\)#\1$targetRelease\2#")

  # remove everything after "pvc-"
  target=$(echo "$target" | sed "s#\(.*pvc-\).*#\1#")

  ls -d "$volumesDir/$target"* 2>/dev/null

}

should-proceed() {
  if [ "$skipConfirm" -eq 1 ]; then
    return 0
  fi
  local opt
  while true; do
# Don't care about back-slashes
#shellcheck disable=SC2162
    read -p "Proceed? (y/n) " opt
    case "$opt" in
      y|Y) break;;
      n|N) exit 1;;
      *) echo "Please choose y or n"
    esac
  done
}

restore() {
  local sources
  local target

  assert-restore-parameters-valid

  echo-info Restoring $backupFile
  echo
  echo "Examining backup $backupFile..."

  sources=$(find-source-directories)

  if [ "$sources" = "" ]; then
    if [ "$sourceNamespace" != "" ]; then
      echo-error "No volumes from $sourceNamespace found in the backup"
    else
      echo-error "No volumes found in the backup"
    fi
    exit 1
  fi

  echo-warn "Data in the following volumes will be overwritten:"

  for src in $sources; do
    if target=$(find-target-directory "$src"); then
      echo "  $(basename "$(readlink -f "$target")")"
    else
      echo -e "  ${INFO}No target found for$RESET $(echo "$src" | tr -d './')"
    fi
  done

  echo-warn "The above data will be deleted from $K3S_STORAGE"

  should-proceed

  for src in $sources; do
    if ! target=$(find-target-directory "$src"); then
      continue
    fi
    echo "Deleting data from: $(readlink -f "$target")"
    rm -rf "${target:?target volume directory was empty}"/*
    echo "Copying data from $(echo "$src" | tr -d './') to:"
    echo "  $(basename "$target")"
    tar --numeric-owner --wildcards --transform="s#^$src#$target/#" -xhf "$backupFile" -P "$src"* \
      2>&1 | grep -v "/*: Not found in archive" | grep -v "Exiting"
  done
}

create() {
  assert-create-parameters-valid

  echo-info "Creating $backupFile"
  if [ "$sourceNamespace" = "" ]; then
    echo "  Backing up all volumes linked from $volumesDir"
  else
    echo "  Backing up volumes in namespace $sourceNamespace linked from $volumesDir"
  fi

# Shellcheck will flag that the filenames found in the subshell are not treated as single entity.
#shellcheck disable=SC2046
  tar -cvzhf "$backupFile" -C "$volumesDir" $(cd "$volumesDir" || exit 1; ls -d "$sourceNamespace"*) \
    | grep -v -e ".*$sourceNamespace.*/[^[:space:]]"
}

create-pvc-links() {
  if [ -d "$volumesDir" ] && [ "$(file-count "$volumesDir")" -ne 0 ]; then
    echo "$volumesDir exists but it not empty"
    usage
  elif ! mkdir -p "$volumesDir"; then
    echo "Could not create links directory: $volumesDir"
    usage
  fi

  $RUNUSER kubectl get pvc -A | tail -n +2 | while read line; do
    local linkName
    local pv
    linkName=$(echo "$line" | awk '{print $1"-"$2"-"$4}')
    pv=$(ls -d "$K3S_STORAGE/"$(echo "$line" | awk '{print "*"$4"*"}'))
    ln -s "$pv" "$volumesDir/$linkName"
  done
}

exit-if-root

PATH=$PATH:/usr/local/bin # workaround sudo secure path

parse-arguments "$@"

if [ "$operation" = "create-pvc-links" ]; then
  if ! k3s-is-running; then
    echo-error "k3s is not running"
    echo
    echo "The PVC links cannot be created while k3s is down."
    echo "Please start by running:"
    echo "  sudo systemctl start k3s"
    sud
    echo "And then rerun this script."
    exit 1
  fi
elif k3s-is-running; then
  echo-error "k3s is running"
  case "$operation" in
    create) echo "Cannot create a backup of $volumesDir while k3s is running.";;
    restore) echo "Cannot restore a backup to $volumesDir while k3s is running.";;
    *) echo "Cannot use this script on $volumesDir while k3s is running.";;
  esac
  echo "Before running this script, please stop k3s using:"
  echo "  k3s-killall.sh"
  echo "After the script has completed, it may be restarted using:"
  echo "  sudo systemctl start k3s"
  exit 1
fi

"$operation"
