{{- if eq .Values.global.cmdKubectl "oc" }}
apiVersion: v1
kind: ConfigMap
metadata:
  metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: service-ca
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  name: '{{ .Release.Name }}-service-ca'
{{- end }}
