{{- if (eq .Values.ingress.type "mapping") }}
{{- if .Values.ingress.host.enabled }}
apiVersion: getambassador.io/v2
kind: Host
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Release.Name }}-wildcard'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-wildcard'
spec:
{{- if .Values.global.ambassadorID }}
  ambassador_id: [ '{{ .Values.global.ambassadorID }}' ]
{{- end }}
  hostname: '*'
  tlsSecret:
    name: '{{ .Values.global.ibmCertSecretName }}'
  tls:
    min_tls_version: v1.3
  requestPolicy:
    insecure:
      action: Redirect
{{- end }}
{{- end }}
