{{- if .Values.networkPolicy.enabled }}
{{- if .Values.networkPolicy.egress.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: allow-egress
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-allow-egress'
spec:
  policyTypes:
  - Egress
  podSelector: {}
  egress:
  - to:
{{- range .Values.networkPolicy.egress.cidrs }}
    - ipBlock:
        cidr: {{ . | quote }}
{{- end }}
{{- end }}
{{- end }}
