{{- if (eq .Values.ingress.type "route") }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}-1'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-{{ .Chart.Name }}-1'
spec:
  host: '{{ .Values.global.domain }}'
  path: '{{ .Values.ingress.path }}/api/'
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: 'gateway'
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}-2'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-{{ .Chart.Name }}-2'
spec:
  host: '{{ .Values.global.domain }}'
  path: '{{ .Values.ingress.path }}/datasets/v3/api-docs'
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: 'gateway'
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}-3'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-{{ .Chart.Name }}-3'
spec:
  host: '{{ .Values.global.domain }}'
  path: '{{ .Values.ingress.path }}/extensions/v3/api-docs'
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: 'gateway'
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}-4'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-{{ .Chart.Name }}-4'
spec:
  host: '{{ .Values.global.domain }}'
  path: '{{ .Values.ingress.path }}/jobservice/v3/api-docs'
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: 'gateway'
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}-5'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-{{ .Chart.Name }}-5'
spec:
  host: '{{ .Values.global.domain }}'
  path: '{{ .Values.ingress.path }}/management/'
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: 'gateway'
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}-6'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-{{ .Chart.Name }}-6'
spec:
  host: '{{ .Values.global.domain }}'
  path: '{{ .Values.ingress.path }}/rest/'
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: 'gateway'
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}-7'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-{{ .Chart.Name }}-7'
spec:
  host: '{{ .Values.global.domain }}'
  path: '{{ .Values.ingress.path }}/results/analytics/'
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: 'gateway'
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}-8'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-{{ .Chart.Name }}-8'
spec:
  host: '{{ .Values.global.domain }}'
  path: '{{ .Values.ingress.path }}/results/ftwebreport/'
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: 'gateway'
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}-9'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-{{ .Chart.Name }}-9'
spec:
  host: '{{ .Values.global.domain }}'
  path: '{{ .Values.ingress.path }}/results/rest/'
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: 'gateway'
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}-10'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-{{ .Chart.Name }}-10'
spec:
  host: '{{ .Values.global.domain }}'
  path: '{{ .Values.ingress.path }}/results/static/'
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: 'gateway'
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}-11'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-{{ .Chart.Name }}-11'
spec:
  host: '{{ .Values.global.domain }}'
  path: '{{ .Values.ingress.path }}/results/v3/api-docs'
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: 'gateway'
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}-12'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-{{ .Chart.Name }}-12'
spec:
  host: '{{ .Values.global.domain }}'
  path: '{{ .Values.ingress.path }}/rm/'
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: 'gateway'
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}-13'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-{{ .Chart.Name }}-13'
spec:
  host: '{{ .Values.global.domain }}'
  path: '{{ .Values.ingress.path }}/sse/'
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: 'gateway'
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}-14'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-{{ .Chart.Name }}-14'
spec:
  host: '{{ .Values.global.domain }}'
  path: '{{ .Values.ingress.path }}/sso/'
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: 'gateway'
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}-15'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-{{ .Chart.Name }}-15'
spec:
  host: '{{ .Values.global.domain }}'
  path: '{{ .Values.ingress.path }}/swagger-resources'
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: 'gateway'
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}-16'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-{{ .Chart.Name }}-16'
spec:
  host: '{{ .Values.global.domain }}'
  path: '{{ .Values.ingress.path }}/testassets/v3/api-docs'
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: 'gateway'
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}-17'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-{{ .Chart.Name }}-17'
spec:
  host: '{{ .Values.global.domain }}'
  path: '{{ .Values.ingress.path }}/v3/api-docs'
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: 'gateway'
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}-18'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-{{ .Chart.Name }}-18'
spec:
  host: '{{ .Values.global.domain }}'
  path: '{{ ternary .Values.ingress.path "/" .Values.global.platform.enabled }}'
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: '{{ .Release.Name }}-frontend'
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}-19'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-{{ .Chart.Name }}-19'
spec:
  host: '{{ .Values.global.domain }}'
  path: '{{ .Values.ingress.path }}/management/health'
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: '{{ .Release.Name }}-frontend'
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}-20'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-{{ .Chart.Name }}-20'
spec:
  host: '{{ .Values.global.domain }}'
  path: '{{ .Values.keycloak.path }}/health'
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: '{{ .Release.Name }}-frontend'
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}-21'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-{{ .Chart.Name }}-21'
spec:
  host: '{{ .Values.global.domain }}'
  path: '{{ .Values.keycloak.path }}'
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: '{{ print .Release.Name "-ssocloak" | trunc 20 | trimSuffix "-" }}-http'
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}-22'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-{{ .Chart.Name }}-22'
spec:
  host: '{{ .Values.global.domain }}'
  path: '{{ .Values.ingress.path }}/webhook/'
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: 'tam'
  wildcardPolicy: None
---
{{- end }}
