{{- if include "testhub.ibmImagePullSecret" . }}
{{- if .Values.global.ibmImagePullUsername }}
{{- if .Values.global.ibmImagePullPassword }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: pull
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ include "testhub.ibmImagePullSecret" . }}'
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":%s,\"email\":\"%s\",\"auth\":\"%s\"}}}" (regexReplaceAll "/.*" (default .Values.imageRegistry .Values.global.imageRegistry) "") .Values.global.ibmImagePullUsername (.Values.global.ibmImagePullPassword | quote) .Values.global.ibmImagePullEmail (printf "%s:%s" .Values.global.ibmImagePullUsername .Values.global.ibmImagePullPassword | b64enc) | b64enc }}
{{- end }}
{{- end }}
{{- end }}