{{- if (.Capabilities.APIVersions.Has "getambassador.io/v2") }}
{{- if .Values.platform.redirectRoot }}
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  labels:
    {{- include "devops-platform.labels" (dict "componentName" "frontend-mapping" "context" .) | nindent 4 }}
  name: {{ include "devops-platform.componentFullname" (dict "componentName" "frontend-root-mapping" "context" .) }}
spec:
{{- if .Values.global.ambassadorID }}
  ambassador_id: [ '{{ .Values.global.ambassadorID }}' ]
{{- end }}
  prefix: /
  service: {{ .Values.global.domain }} 
  host_redirect: true
  path_redirect: {{ .Values.global.platform.path }}
  scheme_redirect: https
{{- end }}

---

apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  labels:
    {{- include "devops-platform.labels" (dict "componentName" "frontend-mapping" "context" .) | nindent 4 }}
  name: {{ include "devops-platform.componentFullname" (dict "componentName" "frontend" "context" .) }}
spec:
{{- if .Values.global.ambassadorID }}
  ambassador_id: [ '{{ .Values.global.ambassadorID }}' ]
{{- end }}
  bypass_auth: true
  host: {{ .Values.global.domain }}
  prefix: {{ .Values.global.platform.path }}
  rewrite: ''
  service: http://{{ include "devops-platform.componentFullname" (dict "componentName" "frontend" "context" .) }}:{{ .Values.frontend.service.port }}
  timeout_ms: {{ .Values.frontend.ingress.timeout }}
{{- end }}
