#
# Licensed Materials - Property of HCL
# (C) Copyright HCL Technologies Ltd. 2024, 2025.  All Rights Reserved.
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule Contract
#
{{- if (eq .Values.ingress.type "mapping") }}
{{- if .Values.ingress.host.enabled }}
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Release.Name }}-ssh'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-ssh'
spec:
{{- if .Values.global.ambassadorID }}
  ambassador_id: [ '{{ .Values.global.ambassadorID }}' ]
{{- end }}
  # This port has to match the TCPMapping config, and also be
  # handled by the emissary load balancer.  See the TCPMapping comments
  # for guidance.
  port: {{ default 9022 .Values.gitea.config.server.SSH_PORT }}
  protocol: TCP
  securityModel: INSECURE
  hostBinding:
    namespace:
      from: SELF
{{- end }}
{{- end }}
