#
# Licensed Materials - Property of HCL
# (C) Copyright HCL Technologies Ltd. 2024, 2025.  All Rights Reserved.
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule Contract
#
{{- if (eq .Values.ingress.type "route") }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}-1'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-{{ .Chart.Name }}-1'
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
spec:
  host: '{{ .Values.global.domain }}'
  path: {{ default "/" (default .Values.ingress.mapping.prefix .Values.ingress.path)}}
  # use default rewrite of "/"...is that really the default?
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: '{{ include "gitea.fullname" . }}-http'
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}-2'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-{{ .Chart.Name }}-2'
  annotations:
    haproxy.router.openshift.io/rewrite-target: /v2
spec:
  host: '{{ .Values.global.domain }}'
  # Gross hack for Gitea container registry bogosity
  path: "/v2"
  # rewrite: "/v2" ??
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: '{{ include "gitea.fullname" . }}-http'
  wildcardPolicy: None
# SSH routing is done with a NodePort in gitea/ssh-svc.yaml
{{- end }}
