#
# Licensed Materials - Property of HCL
# (C) Copyright HCL Technologies Ltd. 2024.  All Rights Reserved.
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule Contract
#
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Release.Name }}-control-passwords'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-control-passwords'
type: Opaque
data:
  username: {{ .Values.gitea.admin.username | b64enc | quote }}
{{- if .Values.gitea.existingPassword }}
  password: {{ .Values.gitea.existingPassword | b64enc | quote }}
{{- else }}
  password: {{ print (default .Release.Name .Values.global.passwordSeed) "gitea-admin-password" | sha256sum | b64enc | quote }}
{{- end }}
{{- if (and .Values.global.platform.enabled (not .Values.postgresql.enabled)) }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{.Release.Name}}-control-ini-secrets'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: {{.Release.Name}}-control-ini-secrets
type: Opaque
stringData:
  database: |
    {{- if .Values.postgresql.host }}
    USER={{ .Values.postgresql.username }}
    PASSWD={{ .Values.postgresql.password }}
    {{- else }}
    USER=control
    PASSWD={{- include "devops-platform.postgresql-password" (dict "context" . "existingPwd" .Values.existingPostgresqlPassword "passwordSeed" .Values.global.passwordSeed "componentName" "control") }}
    {{- end }}  
{{- end }}
