apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ tpl (index .Values "ibm-devopsplan-prod" "platform" "opensearch" "oidc" "clientSecret") . }}'
type: Opaque
data:
  oauth-client-secret: {{ print (default .Release.Name .Values.global.passwordSeed) "opensearch-oauth-client-secret" | sha256sum | b64enc | quote }}