{{- if include "testhub.rabbitmq.enabled" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: rabbitmq-config
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-rabbitmq-config'
data:
  rabbitmq.conf: |
    default_user = user
    queue_master_locator = min-masters
    log.connection.level = warning
    vm_memory_high_watermark.absolute = {{ include "testhub.rabbitmq.memoryHighWatermark" .Values.rabbitmq.resources.limits.memory }}
    total_memory_available_override_value = {{ .Values.rabbitmq.resources.limits.memory }}B
{{- end }}
