{{- if include "testhub.rabbitmq.enabled" . }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-rabbitmq'
type: Opaque
data:
{{- if .Values.rabbitmq.existingPassword }}
  rabbitmq-password: {{ .Values.rabbitmq.existingPassword | b64enc | quote }}
{{- else }}
  rabbitmq-password: {{ print (default .Release.Name (default .Values.global.passwordSeed .Values.passwordSeed)) "rabbitmq-password" | sha256sum | b64enc | quote }}
{{- end }}
{{- if .Values.rabbitmq.existingCookie }}
  rabbitmq-erlang-cookie: {{ .Values.rabbitmq.existingCookie | b64enc | quote }}
{{- else }}
  rabbitmq-erlang-cookie: {{ print (default .Release.Name (default .Values.global.passwordSeed .Values.passwordSeed)) "rabbitmq-erlang-cookie" | sha256sum | b64enc | quote }}
{{- end }}
{{- end }}
