{{- if (.Capabilities.APIVersions.Has "getambassador.io/v2") }}
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  labels:
    {{- include "devops-platform.labels" (dict "componentName" "loop-mapping" "context" .) | nindent 4 }}
  name: {{ include "devops-platform.componentFullname" (dict "componentName" "loop" "context" .) }}
spec:
{{- if .Values.global.ambassadorID }}
  ambassador_id: [ '{{ .Values.global.ambassadorID }}' ]
{{- end }}
  bypass_auth: true
  host: {{ .Values.global.domain }}
  prefix: {{ .Values.loop.ingress.path }}
  rewrite: ''
  service: http://{{ include "devops-platform.componentFullname" (dict "componentName" "loop" "context" .) }}:{{ .Values.loop.service.port }}
  timeout_ms: {{ .Values.loop.ingress.timeout }}
{{- end }}
