apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-platform.componentFullname" (dict "componentName" "tenant" "context" .) }}
  labels:
      {{- include "devops-platform.labels" (dict "componentName" "tenant" "context" .) | nindent 6 }}
type: Opaque
data:
{{- if .Values.tenant.existingPostgresqlPassword }}
  postgresql-password: {{ .Values.tenant.existingPostgresqlPassword | b64enc | quote }}
{{- else }}
  postgresql-password: {{ print (default .Release.Name (default .Values.global.passwordSeed .Values.passwordSeed)) "tenant-postgresql" | sha256sum | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: tenant
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ tpl (index .Values "ibm-devops-prod" "postgresql" "dbs" "tenant" "secret") . }}'
type: Opaque
data:
{{ include "devops-platform.postgresql-password-b64" (dict "context" . "existingPwd" (index .Values "tenant" "existingPostgresqlPassword") "passwordSeed" .Values.global.passwordSeed "componentName" "tenant") }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: tenant
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ tpl (index .Values "tenant" "platform" "oidc" "clientSecret") . }}'
type: Opaque
data:
  oauth-client-secret: {{ print (default .Release.Name .Values.global.passwordSeed) "devopstenant-oauth-client-secret" | sha256sum | b64enc | quote }}
