{{- if .Values.nginx.service -}}
{{- if .Values.global.platform.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ccm.fullname" . }}-nginx-configmap
  labels:
    {{- include "ccm.labels" . | nindent 4 }}
data:
  nginx.conf: |-
        worker_processes  1;

        events {
            worker_connections  1024;
        }

        http {
            include       mime.types;
            default_type  application/octet-stream;

            sendfile        on;

            keepalive_timeout  65;

            server {

                client_header_buffer_size 8k;
                large_client_header_buffers 8 16k;
                proxy_buffer_size 128k;
                proxy_buffers 8 256k;
                proxy_busy_buffers_size 256k;

                listen       5603;
                listen [::]:5603 default_server;

                listen 5602 http2 ssl;
                listen [::]:5602 http2 ssl;

                server_name  {{ include "ccm.fullname" . }}-nginx;
                ssl_certificate /etc/nginx/conf/nginx-selfsigned.crt;
                ssl_certificate_key /etc/nginx/conf/nginx-selfsigned.key;
                ssl_protocols       TLSv1.2;
                keepalive_timeout   70;
                client_max_body_size 20m;
                underscores_in_headers on;

                location / {
                    proxy_pass          https://{{ include "ccm.fullname" . }}-dashboards:5601/;
                }

                error_page   500 502 503 504  /50x.html;
                location = /50x.html {
                    root   html;
                }
            }
        }
{{- end }}
{{- end -}}
