{{- if .Values.nginx.service }}
{{- if or .Values.global.sofySolutionContext (and .Values.ingress.enabled (eq .Values.ingress.type "mapping")) }}
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: {{ include "ccm.fullname" . }}-nginx
spec:
{{- if .Values.global.ambassadorID }}
  ambassador_id: [ '{{ .Values.global.emissaryID }}' ]
{{- end }}
  bypass_auth: {{ .Values.disableAccessControl }}
  case_sensitive: false
  host_regex: true
{{- if .Values.global.platform.enabled }}
  host: {{ .Values.global.domain }}
  prefix: '{{ .Values.dashboards.basePath }}.*'
{{- else }}
  host: {{ include "ccm.fullname" . }}-nginx{{ .Values.ingress.suffix }}.{{ default ".*" .Values.global.domain }}
  prefix: /.*
  resolver: {{ include "ccm.fullname" . }}
{{- end }}
  prefix_regex: true
  rewrite: ""
  service: http://{{ include "ccm.fullname" . }}-nginx:5603
  timeout_ms: {{ .Values.nginx.ingressMapping.timeout_ms }}
{{- end }}
{{- end }}
