{{- if .Values.global.platform.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ccm.subchart.fullname" . }}-data-prepper-pipeline
  labels:
    {{- include "data-prepper.labels" . | nindent 4 }}
type: Opaque
stringData:
  pipelines.yaml: |
{{- if .Values.pipelineConfig.enabled }}
    {{- toYaml .Values.pipelineConfig.config | nindent 4 }}
{{- else}}
    build:
      source:
        graphql_source:
{{- if .Values.pipelineConfig.graphql_source.endpoint }}
          endpoint: "{{ .Values.pipelineConfig.graphql_source.endpoint }}"
{{- else}}
{{- if .Values.global.domain }}
          endpoint: "https://{{ .Values.global.domain }}/velocity/release-events-api/graphql"
{{- else}}
          endpoint: "https://{{ template "ccm.subchart.fullname" . }}/release-events-api/graphql"
{{- end }}
{{- end }}
          bearer_token: "{{ .Values.pipelineConfig.graphql_source.bearer_token }}"
          token: "{{ .Values.pipelineConfig.graphql_source.token }}"
          type: "metric"
          batch_size: 100
          collection_interval: 60
          query_name: "build"
{{- if .Values.global.domain }}
          opensearch_dashboards_host: "https://{{ .Values.global.domain }}/opensearch-dashboards"
{{- else}}
          opensearch_dashboards_host: "https://{{ template "ccm.subchart.fullname" . }}/opensearch-dashboards"
{{- end }}
          opensearch_host: "https://{{ template "ccm.subchart.fullname" . }}-opensearch:9200"
          opensearch_username: {{ .Values.opensearch.username }}
          opensearch_password: {{ .Values.opensearch.password }}
          data_fields: ["builds", "items"]
          use_query_template: true
          metadata_index: ".devops_analytics"
      # processor:
      #   - add_entries:
      #       entries:
      #         - key: "dummy"
      #           value: 1
      sink:
        - opensearch:
            hosts: [ "https://{{ template "ccm.subchart.fullname" . }}-opensearch:9200" ]
            insecure: true
            username: {{ .Values.opensearch.username }}
            password: {{ .Values.opensearch.password }}
            index: "{{ .Values.pipelineConfig.opensearch.index }}"
            document_id: "{{ .Values.pipelineConfig.opensearch.document_id }}"

    deployment:
      source:
        graphql_source:
{{- if .Values.pipelineConfig.graphql_source.endpoint }}
          endpoint: "{{ .Values.pipelineConfig.graphql_source.endpoint }}"
{{- else}}
{{- if .Values.global.domain }}
          endpoint: "https://{{ .Values.global.domain }}/velocity/release-events-api/graphql"
{{- else}}
          endpoint: "https://{{ template "ccm.subchart.fullname" . }}/release-events-api/graphql"
{{- end }}
{{- end }}
          bearer_token: "{{ .Values.pipelineConfig.graphql_source.bearer_token }}"
          token: "{{ .Values.pipelineConfig.graphql_source.token }}"
          type: "metric"
          batch_size: 100
          collection_interval: 60
          query_name: "deployment"
          data_fields: ["deployments", "items"]
{{- if .Values.global.domain }}
          opensearch_dashboards_host: "https://{{ .Values.global.domain }}/opensearch-dashboards"
{{- else}}
          opensearch_dashboards_host: "https://{{ template "ccm.subchart.fullname" . }}/opensearch-dashboards"
{{- end }}
          opensearch_host: "https://{{ template "ccm.subchart.fullname" . }}-opensearch:9200"
          opensearch_username: {{ .Values.opensearch.username }}
          opensearch_password: {{ .Values.opensearch.password }}
          use_query_template: true
          metadata_index: ".devops_analytics"
      sink:
        - opensearch:
            hosts: [ "https://{{ template "ccm.subchart.fullname" . }}-opensearch:9200" ]
            insecure: true
            username: {{ .Values.opensearch.username }}
            password: {{ .Values.opensearch.password }}
            index: "analytics_deployment_data"
            document_id: ${/mongo_id}

    issue:
      source:
        graphql_source:
{{- if .Values.pipelineConfig.graphql_source.endpoint }}
          endpoint: "{{ .Values.pipelineConfig.graphql_source.endpoint }}"
{{- else}}
{{- if .Values.global.domain }}
          endpoint: "https://{{ .Values.global.domain }}/velocity/release-events-api/graphql"
{{- else}}
          endpoint: "https://{{ template "ccm.subchart.fullname" . }}/release-events-api/graphql"
{{- end }}
{{- end }}
          bearer_token: "{{ .Values.pipelineConfig.graphql_source.bearer_token }}"
          token: "{{ .Values.pipelineConfig.graphql_source.token }}"
          type: "metric"
          batch_size: 100
          collection_interval: 60
          query_name: "issue"
          data_fields: ["issues"]
{{- if .Values.global.domain }}
          opensearch_dashboards_host: "https://{{ .Values.global.domain }}/opensearch-dashboards"
{{- else}}
          opensearch_dashboards_host: "https://{{ template "ccm.subchart.fullname" . }}/opensearch-dashboards"
{{- end }}
          opensearch_host: "https://{{ template "ccm.subchart.fullname" . }}-opensearch:9200"
          opensearch_username: {{ .Values.opensearch.username }}
          opensearch_password: {{ .Values.opensearch.password }}
          use_query_template: true
          metadata_index: ".devops_analytics"
      # processor:                # To test dlq_file write in sink
      #   - add_entries:
      #       entries:
      #         - key: "_id"
      #           value: "1"
      sink:
        - opensearch:
            hosts: [ "https://{{ template "ccm.subchart.fullname" . }}-opensearch:9200" ]
            insecure: true
            username: {{ .Values.opensearch.username }}
            password: {{ .Values.opensearch.password }}
            index: "analytics_issue_data"
            pipeline: "issue_all_fields_pipeline"
            document_id: ${/mongo_id}

    metric:
      source:
        graphql_source:
{{- if .Values.pipelineConfig.graphql_source.endpoint }}
          endpoint: "{{ .Values.pipelineConfig.graphql_source.endpoint }}"
{{- else}}
{{- if .Values.global.domain }}
          endpoint: "https://{{ .Values.global.domain }}/velocity/release-events-api/graphql"
{{- else}}
          endpoint: "https://{{ template "ccm.subchart.fullname" . }}/release-events-api/graphql"
{{- end }}
{{- end }}
          bearer_token: "{{ .Values.pipelineConfig.graphql_source.bearer_token }}"
          token: "{{ .Values.pipelineConfig.graphql_source.token }}"
          type: "metric"
          batch_size: 100
          collection_interval: 60
          query_name: "metric"
          data_fields: ["metrics", "items"]
{{- if .Values.global.domain }}
          opensearch_dashboards_host: "https://{{ .Values.global.domain }}/opensearch-dashboards"
{{- else}}
          opensearch_dashboards_host: "https://{{ template "ccm.subchart.fullname" . }}/opensearch-dashboards"
{{- end }}
          opensearch_host: "https://{{ template "ccm.subchart.fullname" . }}-opensearch:9200"
          opensearch_username: {{ .Values.opensearch.username }}
          opensearch_password: {{ .Values.opensearch.password }}
          use_query_template: true
          metadata_index: ".devops_analytics"
      sink:
        - opensearch:
            hosts: [ "https://{{ template "ccm.subchart.fullname" . }}-opensearch:9200" ]
            insecure: true
            username: {{ .Values.opensearch.username }}
            password: {{ .Values.opensearch.password }}
            index: "analytics_metric_data"
            document_id: ${/mongo_id}


    commit:
      source:
        graphql_source:
{{- if .Values.pipelineConfig.graphql_source.endpoint }}
          endpoint: "{{ .Values.pipelineConfig.graphql_source.endpoint }}"
{{- else}}
{{- if .Values.global.domain }}
          endpoint: "https://{{ .Values.global.domain }}/velocity/release-events-api/graphql"
{{- else}}
          endpoint: "https://{{ template "ccm.subchart.fullname" . }}/release-events-api/graphql"
{{- end }}
{{- end }}
          bearer_token: "{{ .Values.pipelineConfig.graphql_source.bearer_token }}"
          token: "{{ .Values.pipelineConfig.graphql_source.token }}"
          type: "metric"
          batch_size: 100
          collection_interval: 60
          query_name: "commit"
          data_fields: ["commits"]
{{- if .Values.global.domain }}
          opensearch_dashboards_host: "https://{{ .Values.global.domain }}/opensearch-dashboards"
{{- else}}
          opensearch_dashboards_host: "https://{{ template "ccm.subchart.fullname" . }}/opensearch-dashboards"
{{- end }}
          opensearch_host: "https://{{ template "ccm.subchart.fullname" . }}-opensearch:9200"
          opensearch_username: {{ .Values.opensearch.username }}
          opensearch_password: {{ .Values.opensearch.password }}
          use_query_template: true
          metadata_index: ".devops_analytics"
      sink:
        - opensearch:
            hosts: [ "https://{{ template "ccm.subchart.fullname" . }}-opensearch:9200" ]
            insecure: true
            username: {{ .Values.opensearch.username }}
            password: {{ .Values.opensearch.password }}
            index: "analytics_commit_data"
            document_id: ${/mongo_id}

    pr:
      source:
        graphql_source:
{{- if .Values.pipelineConfig.graphql_source.endpoint }}
          endpoint: "{{ .Values.pipelineConfig.graphql_source.endpoint }}"
{{- else}}
{{- if .Values.global.domain }}
          endpoint: "https://{{ .Values.global.domain }}/velocity/release-events-api/graphql"
{{- else}}
          endpoint: "https://{{ template "ccm.subchart.fullname" . }}/release-events-api/graphql"
{{- end }}
{{- end }}
          bearer_token: "{{ .Values.pipelineConfig.graphql_source.bearer_token }}"
          token: "{{ .Values.pipelineConfig.graphql_source.token }}"
          type: "metric"
          batch_size: 100
          collection_interval: 60
          query_name: "pullrequest"
          data_fields: ["pullRequests"]
{{- if .Values.global.domain }}
          opensearch_dashboards_host: "https://{{ .Values.global.domain }}/opensearch-dashboards"
{{- else}}
          opensearch_dashboards_host: "https://{{ template "ccm.subchart.fullname" . }}/opensearch-dashboards"
{{- end }}
          opensearch_host: "https://{{ template "ccm.subchart.fullname" . }}-opensearch:9200"
          opensearch_username: {{ .Values.opensearch.username }}
          opensearch_password: {{ .Values.opensearch.password }}
          use_query_template: true
          metadata_index: ".devops_analytics"
      sink:
        - opensearch:
            hosts: [ "https://{{ template "ccm.subchart.fullname" . }}-opensearch:9200" ]
            insecure: true
            username: {{ .Values.opensearch.username }}
            password: {{ .Values.opensearch.password }}
            index: "analytics_pullrequest_data"
            document_id: ${/mongo_id}

    vsmmetric:
      source:
        graphql_source:
{{- if .Values.pipelineConfig.graphql_source.endpoint }}
          endpoint: "{{ .Values.pipelineConfig.graphql_source.endpoint }}"
{{- else}}
{{- if .Values.global.domain }}
          endpoint: "https://{{ .Values.global.domain }}/velocity/release-events-api/graphql"
{{- else}}
          endpoint: "https://{{ template "ccm.subchart.fullname" . }}/release-events-api/graphql"
{{- end }}
{{- end }}
          bearer_token: "{{ .Values.pipelineConfig.graphql_source.bearer_token }}"
          token: "{{ .Values.pipelineConfig.graphql_source.token }}"
          type: "metric"
          batch_size: 100
          collection_interval: 60
          query_name: "vsmMetric"
          data_fields: ["vsmMetrics"]
{{- if .Values.global.domain }}
          opensearch_dashboards_host: "https://{{ .Values.global.domain }}/opensearch-dashboards"
{{- else}}
          opensearch_dashboards_host: "https://{{ template "ccm.subchart.fullname" . }}/opensearch-dashboards"
{{- end }}
          opensearch_host: "https://{{ template "ccm.subchart.fullname" . }}-opensearch:9200"
          opensearch_username: {{ .Values.opensearch.username }}
          opensearch_password: {{ .Values.opensearch.password }}
          use_query_template: true
          metadata_index: ".devops_analytics"
      sink:
        - opensearch:
            hosts: [ "https://{{ template "ccm.subchart.fullname" . }}-opensearch:9200" ]
            insecure: true
            username: {{ .Values.opensearch.username }}
            password: {{ .Values.opensearch.password }}
            index: "analytics_vsm_metrics_data"
            document_id: ${/mongo_id}
            flush_timeout: 30

{{- end }}
{{- end -}}
