{{- if include "testhub.cdis.enabled" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: cdis
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-cdis'
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: '{{ .Release.Name }}'
      app.kubernetes.io/name: cdis
      app.kubernetes.io/part-of: '{{ .Chart.Name }}'
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        productID: e3e180b0faae4301b54c5c9b37319e5c
        productMetric: FLOATING_USER
        productName: IBM Rational Test Automation Server Basic
        productVersion: "11.0.5"
        cloudpakName : IBM DevOps for IBM Cloud Paks
        cloudpakId : dedb7a9445a44fb88c927c1658243cd1
        cloudpakMetric : RESOURCE_UNIT
        productCloudpakRatio : "1:1"
        productChargedContainers : All
      labels:
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/name: cdis
        app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
{{- if .Values.priorityClassName }}
      priorityClassName: '{{ .Values.priorityClassName }}'
{{- end }}
      enableServiceLinks: false
      containers:
      - env:
        - name: RABBITMQ_USERNAME
          value: user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              key: rabbitmq-password
              name: '{{ .Release.Name }}-rabbitmq'
        - name: RABBITMQ_HOST
          value: '{{ .Release.Name }}-rabbitmq'
        - name: RABBITMQ_PORT
          value: '5672'
        image: '{{ (default (default .Values.imageRegistry .Values.global.imageRegistry) .Values.cdis.registry) }}/{{ regexReplaceAll .Values.imageRepoRegex .Values.cdis.image .Values.imageRepoRepl }}'
        imagePullPolicy: IfNotPresent
        # startupProbe:
        #   failureThreshold: 20
        #   httpGet:
        #     path: '{{ .Values.ingress.path }}/management/health'
        #     port: http
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: '{{ .Values.ingress.path }}/management/health'
        #     port: http
        # readinessProbe:
        #   httpGet:
        #     path: '{{ .Values.ingress.path }}/management/health'
        #     port: http
        name: main
{{- if .Values.cdis.resources }}
        resources: {{- toYaml .Values.cdis.resources | nindent 10 }}
{{- end }}
{{- template "testhub.container.security-context" .Values.containerSecurityContext }}
{{- if include "testhub.ibmImagePullSecret" . }}
      imagePullSecrets:
      - name: '{{ include "testhub.ibmImagePullSecret" . }}'
{{- end }}
      hostIPC: false
      hostNetwork: false
      hostPID: false
{{- template "testhub.pod.security-context" $ }}
      serviceAccountName: '{{ .Release.Name }}-cdis'
{{- end }}