apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-code-container-mgr-svcact
  namespace: {{ .Release.Namespace }}
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devops-code-container-mgr-pod-creator
rules:
- apiGroups: [""]
  resources: ["services","service","pods","pods/exec","persistentvolumeclaims","persistentvolumes","namespaces","secrets"]
  verbs: ["create", "get", "watch", "list", "delete","patch"]
- apiGroups: ["apps"]
  resources: ["deployments","deployment","replicasets"]
  verbs: ["create", "get", "watch", "list", "delete","patch"]  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devops-code-container-mgr-pod-creator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devops-code-container-mgr-pod-creator
subjects:
- kind: ServiceAccount
  name: devops-code-container-mgr-svcact
  namespace: {{ .Release.Namespace }}