{{- if include "testhub.demo.enabled" . }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: demo
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-demo'
type: Opaque
data:
  user-password: {{ print (default .Release.Name (default .Values.global.passwordSeed .Values.passwordSeed)) "demo-user-password" | sha256sum | b64enc | quote }}
  user-token: ''
  admin-password: {{ print (default .Release.Name (default .Values.global.passwordSeed .Values.passwordSeed)) "demo-admin-password" | sha256sum | b64enc | quote }}
  admin-token: ''
{{- end }}
