apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: '10'
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: postgresql-init
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-postgresql-init'
spec:
  template:
    metadata:
      annotations:
        productID: e3e180b0faae4301b54c5c9b37319e5c
        productMetric: FLOATING_USER
        productName: IBM Rational Test Automation Server Basic
        productVersion: "11.0.5"
        cloudpakName : IBM DevOps for IBM Cloud Paks
        cloudpakId : dedb7a9445a44fb88c927c1658243cd1
        cloudpakMetric : RESOURCE_UNIT
        productCloudpakRatio : "1:1"
        productChargedContainers : All
      labels:
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/managed-by: '{{ .Release.Service }}'
        app.kubernetes.io/name: postgresql-init
        app.kubernetes.io/part-of: '{{ .Chart.Name }}'
        app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
        helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - command:
        - /bin/create-users.sh
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              key: postgresql-password
              name: '{{ .Release.Name }}-postgresql'
        - name: PGUSER
          value: postgres
        image: '{{ (default (default .Values.imageRegistry .Values.global.imageRegistry) .Values.postgresql.registry) }}/{{ regexReplaceAll .Values.imageRepoRegex .Values.postgresql.image .Values.imageRepoRepl }}'
        imagePullPolicy: IfNotPresent
        name: main
{{- if .Values.postgresql.job.resources }}
        resources: {{- toYaml .Values.postgresql.job.resources | nindent 10 }}
{{- end }}
{{- template "testhub.container.security-context" .Values.containerSecurityContext }}
        volumeMounts:
        - name: scripts
          mountPath: /bin/create-users.sh
          subPath: create-users.sh
{{- range $key, $value := .Values.postgresql.dbs }}
{{- if ne $value.state "absent" }}
{{- if not $value.owner }}
        - name: '{{ $key }}-pwd'
          mountPath: /pwds/{{ $key }}
{{- end }}
{{- end }}
{{- end }}
{{- if include "testhub.ibmImagePullSecret" . }}
      imagePullSecrets:
      - name: '{{ include "testhub.ibmImagePullSecret" . }}'
{{- end }}
      initContainers:
{{- template "testhub.initContainers.pg-isready" (merge (dict "dbName" "postgres" "secret" (printf "%s-postgresql" .Release.Name)) .) }}
      restartPolicy: Never
      hostIPC: false
      hostNetwork: false
      hostPID: false
{{- template "testhub.pod.security-context" $ }}
      serviceAccountName: '{{ .Release.Name }}-postgresql'
      volumes:
      - name: scripts
        configMap:
          defaultMode: 365
          name: '{{ .Release.Name }}-postgresql-init-sh'
{{- range $key, $value := .Values.postgresql.dbs }}
{{- if ne $value.state "absent" }}
{{- if not $value.owner }}
      - name: {{ $key }}-pwd
        secret:
          secretName: {{ tpl (default (print "{{ .Release.Name }}-" $key) $value.secret) $ }}
{{- end }}
{{- end }}
{{- end }}
