apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: postgresql-headless
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    service.alpha.kubernetes.io/tolerate-unready-endpoints: 'true'
  name: '{{ .Release.Name }}-postgresql-headless'
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: tcp-postgresql
    port: 5432
    targetPort: tcp-postgresql
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
