{{- if include "testhub.router.enabled" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: router
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-router'
spec:
{{- if gt (int .Values.router.replicaCount) 1 }}
  replicas: {{ .Values.router.replicaCount }}
{{- end }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: '{{ .Release.Name }}'
      app.kubernetes.io/name: router
      app.kubernetes.io/part-of: '{{ .Chart.Name }}'
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        productID: e3e180b0faae4301b54c5c9b37319e5c
        productMetric: FLOATING_USER
        productName: IBM Rational Test Automation Server Basic
        productVersion: "11.0.5"
        cloudpakName : IBM DevOps for IBM Cloud Paks
        cloudpakId : dedb7a9445a44fb88c927c1658243cd1
        cloudpakMetric : RESOURCE_UNIT
        productCloudpakRatio : "1:1"
        productChargedContainers : All
      labels:
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/name: router
        app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
{{- if .Values.priorityClassName }}
      priorityClassName: '{{ .Values.priorityClassName }}'
{{- end }}
      containers:
      - env:
        - name: gateway.addon.addonCredentials
          valueFrom:
            secretKeyRef:
              key: addon-registration-secret
              name: '{{ .Release.Name }}-router'
        - name: INGRESS_DOMAIN
          value: '{{ .Values.global.domain }}'
        - name: KEYCLOAK_AUTH_SERVER_URL
          value: https://$(INGRESS_DOMAIN){{ .Values.keycloak.path }}
        - name: KEYCLOAK_REALM
          value: '{{ .Values.keycloak.realm }}'
        - name: KEYCLOAK_CREDENTIAL_SECRET
          valueFrom:
            secretKeyRef:
              key: oauth-client-secret
              name: '{{ .Release.Name }}-core'
        - name: KEYCLOAK_URLSCONFIG_ENABLED
          value: 'true'
        - name: KEYCLOAK_URLSCONFIG_PUBLICURL
          value: https://$(INGRESS_DOMAIN)
{{- if gt (int .Values.router.replicaCount) 1 }}
        - name: ROUTER_SCALING_ENABLED
          value: 'true'
{{- end }}
        - name: RATIONAL_LICENSE_FILE
          value: '{{ default .Values.global.rationalLicenseKeyServer .Values.rationalLicenseKeyServer }}'
        - name: OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: oauth-client-secret
              name: '{{ .Release.Name }}-core'
        - name: SPRING_APPLICATION_JSON
          value: >
            {
              "server": {
                "forward-headers-strategy": "NATIVE"
              },
              "spring": {
                "webflux": {
                  "base-path": "{{ .Values.ingress.path }}"
                },
                "cloud": {
                  "loadbalancer": {
                    "health-check": {
                      "path": {
                        "keycloak": "{{ .Values.keycloak.path }}/realms/{{ .Values.keycloak.realm }}"
                      }
                    }
                  }
                },
                "security": {
                  "oauth2": {
                    "resourceserver": {
                      "jwt": {
                        "issuer-uri": "https://$(INGRESS_DOMAIN){{ .Values.keycloak.path }}/realms/{{ .Values.keycloak.realm }}"
                      }
                    },
                    "client": {
                      "registration": {
                        "keycloak": {
                          "client-id": "testserver",
                          "client-secret": "$(OAUTH_CLIENT_SECRET)",
                          "authorization-grant-type": "authorization_code",
                          "redirectUri": "{baseUrl}/sso/oauth2/code/{registrationId}"
                        }
                      },
                      "provider": {
                        "keycloak": {
                          "issuer-uri": "https://$(INGRESS_DOMAIN){{ .Values.keycloak.path }}/realms/{{ .Values.keycloak.realm }}",
                          "user-name-attribute": "sub"
                        }
                      }
                    }
                  }
                }
              },
              "gateway": {
                "content-security-policy-external-list": "{{ .Values.router.contentSecurityPolicyExternalList }}",
                "cors": {
{{- if .Values.router.allowedOrigin }}
                  "allowed-origin-patterns": "https://$(INGRESS_DOMAIN),{{ .Values.router.allowedOrigin }}",
{{- else }}
                  "allowed-origin-patterns": "",
{{- end }}
                  "allowed-methods": "*",
                  "allowed-headers": "*",
                  "exposed-headers": "Authorization,Link,X-Total-Count",
                  "allow-credentials": "true",
                  "max-age": "1800"
                }
              },
              "router" : {
                "rateLimit": {{ .Values.router.rateLimit | toPrettyJson | indent 15 }}
              }
            }
        - name: SPRING_PROFILES_ACTIVE
          value: prod,automation,swagger
{{- range $key, $value := .Values.router.extraEnv }}
        - name: {{ $key }}
          value: {{ tpl $value $ | quote }}
{{- end }}
        image: '{{ (default (default .Values.imageRegistry .Values.global.imageRegistry) .Values.router.registry) }}/{{ regexReplaceAll .Values.imageRepoRegex .Values.router.image .Values.imageRepoRepl }}'
        imagePullPolicy: IfNotPresent
        startupProbe:
          failureThreshold: 20
          httpGet:
            path: '{{ .Values.ingress.path }}/management/health'
            port: http
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: '{{ .Values.ingress.path }}/management/health'
            port: http
        readinessProbe:
          httpGet:
            path: '{{ .Values.ingress.path }}/management/health'
            port: http
        name: main
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
{{- if .Values.router.resources }}
        resources: {{- toYaml .Values.router.resources | nindent 10 }}
{{- end }}
{{- template "testhub.container.security-context" .Values.containerSecurityContext }}
        volumeMounts:
{{- if gt (int .Values.router.replicaCount) 1 }}
{{- template "testhub.volumeMounts.kube-api-access" }}
{{- end }}
{{- template "testhub.volumeMounts.trust-store" $ }}
{{- if include "testhub.ibmImagePullSecret" . }}
      imagePullSecrets:
      - name: '{{ include "testhub.ibmImagePullSecret" . }}'
{{- end }}
      initContainers:
{{- template "testhub.initContainers.trust-store" $ }}
      - name: keycloak
        command:
        - sh
        - -ec
        - |
          ./wait.sh $KEYCLOAK_URL/realms/$REALM_NAME/
          ./client-delete.sh
        env:
{{- template "testhub.container.keycloak-init-sh-env" $ }}
        - name: CLIENT_ID
          value: internal
{{- template "testhub.container.keycloak-init-sh-trailer" $ }}
{{- template "testhub.initContainers.core-isready" $ }}
      hostIPC: false
      hostNetwork: false
      hostPID: false
{{- template "testhub.pod.security-context" $ }}
      serviceAccountName: '{{ .Release.Name }}-router'
      volumes:
{{- if gt (int .Values.router.replicaCount) 1 }}
{{- template "testhub.volumes.kube-api-access" }}
{{- end }}
{{- template "testhub.volumes.trust-store" $ }}
{{- template "testhub.volumes.keycloak-init-sh" $ }}
{{- end }}
