{{- if include "testhub.router.enabled" . }}
{{- if gt (int .Values.router.replicaCount) 1 }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: router
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-router'
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: '{{ .Release.Name }}-endpoints'
subjects:
- kind: ServiceAccount
  name: '{{ .Release.Name }}-router'
  namespace: '{{ .Release.Namespace }}'
{{- end }}
{{- end }}
