{{- if include "testhub.router.enabled" . }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: router
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: '{{ .Release.Name }}-router'
type: Opaque
data:
{{- if .Values.router.existingAddOnRegistrationSecret }}
  addon-registration-secret: {{ .Values.router.existingAddOnRegistrationSecret | b64enc | quote }}
{{- else }}
  addon-registration-secret: {{ print (default .Release.Name (default .Values.global.passwordSeed .Values.passwordSeed)) "addon-registration-secret" | sha256sum | b64enc | quote }}
{{- end }}
{{- end }}
