{{- if include "testhub.router.enabled" . }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ regexReplaceAll "-.*" .Chart.AppVersion "" }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
  name: gateway
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
{{- if gt (int .Values.router.replicaCount) 1 }}
  - name: hazelcast
    port: 5701
{{- end }}
  selector:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/name: router
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
{{- end }}
